// Electronics Classic — Color Palettes
// Palette #1 matches config.ts defaults exactly.
// Valentina will expand this to 16 palettes later.

import type { ColorPalette } from "@/types/templates/config-schema";

export const electronicsClassicPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. AZUL CLÁSICO — Default, matches config.ts verbatim
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "azul-clasico",
    name: "Azul Clásico",
    description: "El azul electrónica clásico — profesional, confiable y moderno",
    style: "corporate",
    preview: ["#0079EB", "#FFFFFF", "#444444", "#F5F5F5", "#0082FB"],
    colors: {
      primary: "#0079EB",
      secondary: "#0082FB",
      background: "#FFFFFF",
      textPrimary: "#111111",
      textSecondary: "#333333",
      textMuted: "#666666",
      textSubtle: "#999999",
      textFooter: "#6B7280",
      textBreadcrumb: "#9CA3AF",
      textSummerSale: "#666666",
      headerBg: "#0079EB",
      sectionBg: "#FAFAFA",
      cardBg: "#FFFFFF",
      surface: "#F5F5F5",
      searchBg: "#F5F5F5",
      reviewBg: "#FAFAFA",
      paginationBg: "#F5F5F5",
      specBadgeBg: "#F5F5F5",
      border: "#E5E7EB",
      borderLight: "#F3F4F6",
      borderInput: "#D1D5DB",
      borderMid: "#E5E7EB",
      navBorder: "#1e1e1e",
      buttonBg: "#444444",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#EF4444",
      badgeText: "#FFFFFF",
      ratingStar: "#FBBF24",
      ratingBarBg: "#E5E7EB",
      tabActive: "#0079EB",
      categoryActiveBg: "#0079EB",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F5F5F5",
      popularBg1: "#EAEAEA",
      popularBg2: "#CDCDCD",
      popularBg3: "#9A9A9A",
      popularText0: "#111111",
      popularText1: "#111111",
      popularText2: "#111111",
      popularText3: "#FFFFFF",
      filterActiveBg: "#0079EB",
      filterActiveBorder: "#0079EB",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#F5F5F5",
      promoBannerTo: "#EAEAEA",
      promoBannerText: "#111111",
      promoBannerSubtext: "#666666",
      topBarBg: "#0082FB",
      topBarText: "#FFFFFF",
      shopTitleColor: "#0079EB",
      imageBg: "#F5F5F5",
      categoryOverlayBg: "rgba(0,0,0,0.6)",
      categoryOverlayText: "#FFFFFF",
    },
  },
];
