// Electronics Classic — Color Palettes
// 16 pre-built palettes designed by Valentina (UI/UX).
// Palette #1 (azul-clasico) matches config.ts defaults exactly.
// ALL palettes include the full electronics-classic token set.
// WCAG AA (4.5:1) verified for all critical text/background pairs.

import type { ColorPalette } from "@/types/templates/config-schema";

export const electronicsClassicPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. AZUL CLÁSICO — Default, matches config.ts verbatim
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "azul-clasico",
    name: "Azul Clásico",
    description: "El azul electrónica clásico — profesional, confiable y moderno",
    style: "corporate",
    preview: ["#0079EB", "#FFFFFF", "#444444", "#F5F5F5", "#0082FB"],
    colors: {
      primary: "#0079EB",
      secondary: "#0082FB",
      background: "#FFFFFF",
      textPrimary: "#111111",
      textSecondary: "#333333",
      textMuted: "#666666",
      textSubtle: "#999999",
      textFooter: "#6B7280",
      textBreadcrumb: "#9CA3AF",
      textSummerSale: "#666666",
      headerBg: "#0079EB",
      sectionBg: "#FAFAFA",
      cardBg: "#FFFFFF",
      surface: "#F5F5F5",
      searchBg: "#F5F5F5",
      reviewBg: "#FAFAFA",
      paginationBg: "#F5F5F5",
      specBadgeBg: "#F5F5F5",
      border: "#E5E7EB",
      borderLight: "#F3F4F6",
      borderInput: "#D1D5DB",
      borderMid: "#E5E7EB",
      navBorder: "#1e1e1e",
      buttonBg: "#444444",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#0079EB",
      badgeText: "#FFFFFF",
      ratingStar: "#FBBF24",
      ratingBarBg: "#E5E7EB",
      tabActive: "#0079EB",
      categoryActiveBg: "#0079EB",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F5F5F5",
      popularBg1: "#EAEAEA",
      popularBg2: "#CDCDCD",
      popularBg3: "#9A9A9A",
      popularText0: "#111111",
      popularText1: "#111111",
      popularText2: "#111111",
      popularText3: "#FFFFFF",
      filterActiveBg: "#0079EB",
      filterActiveBorder: "#0079EB",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#F5F5F5",
      promoBannerTo: "#EAEAEA",
      promoBannerText: "#111111",
      promoBannerSubtext: "#666666",
      topBarBg: "#0082FB",
      topBarText: "#FFFFFF",
      shopTitleColor: "#0079EB",
      imageBg: "#F5F5F5",
      categoryOverlayBg: "rgba(0,0,0,0.6)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. NOCHE TECH — Dark premium with silver accents (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "noche-tech",
    name: "Noche Tech",
    description: "Oscuridad premium con acentos plateados — para marcas tech de alto nivel",
    style: "premium",
    preview: ["#0D1117", "#C0C8D8", "#161B22", "#E6EDF3", "#58A6FF"],
    colors: {
      primary: "#58A6FF",
      secondary: "#C0C8D8",
      background: "#0D1117",
      textPrimary: "#E6EDF3",
      textSecondary: "#B0BAC8",
      textMuted: "#8B949E",
      textSubtle: "#C0C8D8",
      textFooter: "#7D8590",
      textBreadcrumb: "#484F58",
      textSummerSale: "#7D8590",
      headerBg: "#0D1117",
      sectionBg: "#0D1117",
      cardBg: "#161B22",
      surface: "#1C2128",
      searchBg: "#161B22",
      reviewBg: "#161B22",
      paginationBg: "#161B22",
      specBadgeBg: "#1C2128",
      border: "#30363D",
      borderLight: "#21262D",
      borderInput: "#484F58",
      borderMid: "#30363D",
      navBorder: "#21262D",
      buttonBg: "#58A6FF",
      buttonText: "#0D1117",
      footerBg: "#010409",
      badgeBg: "#58A6FF",
      badgeText: "#0D1117",
      ratingStar: "#E3B341",
      ratingBarBg: "#30363D",
      tabActive: "#58A6FF",
      categoryActiveBg: "#58A6FF",
      categoryActiveText: "#0D1117",
      popularBg0: "#3A4A5C",
      popularBg1: "#2C3A4C",
      popularBg2: "#1E2A3C",
      popularBg3: "#101C2C",
      popularText0: "#E6EDF3",
      popularText1: "#E6EDF3",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#58A6FF",
      filterActiveBorder: "#58A6FF",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#1C2128",
      promoBannerTo: "#161B22",
      promoBannerText: "#E6EDF3",
      promoBannerSubtext: "#8B949E",
      topBarBg: "#010409",
      topBarText: "#C0C8D8",
      shopTitleColor: "#58A6FF",
      imageBg: "#1C2128",
      categoryOverlayBg: "rgba(0,0,0,0.75)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. ROJO GAMER — Bold red/black for gaming stores
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "rojo-gamer",
    name: "Rojo Gamer",
    description: "Rojo intenso sobre negro — energía gaming sin compromiso",
    style: "brutalist",
    preview: ["#E81224", "#1A1A1A", "#FF3A4A", "#F0F0F0", "#2A2A2A"],
    colors: {
      primary: "#E81224",
      secondary: "#FF3A4A",
      background: "#F5F5F5",
      textPrimary: "#111111",
      textSecondary: "#333333",
      textMuted: "#666666",
      textSubtle: "#888888",
      textFooter: "#AAAAAA",
      textBreadcrumb: "#999999",
      textSummerSale: "#666666",
      headerBg: "#1A1A1A",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      surface: "#F0F0F0",
      searchBg: "#F0F0F0",
      reviewBg: "#FAFAFA",
      paginationBg: "#F0F0F0",
      specBadgeBg: "#F0F0F0",
      border: "#E0E0E0",
      borderLight: "#F0F0F0",
      borderInput: "#CCCCCC",
      borderMid: "#E0E0E0",
      navBorder: "#2A2A2A",
      buttonBg: "#E81224",
      buttonText: "#FFFFFF",
      footerBg: "#111111",
      badgeBg: "#E81224",
      badgeText: "#FFFFFF",
      ratingStar: "#FFB800",
      ratingBarBg: "#E0E0E0",
      tabActive: "#E81224",
      categoryActiveBg: "#E81224",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F5F5F5",
      popularBg1: "#E8E8E8",
      popularBg2: "#CCCCCC",
      popularBg3: "#999999",
      popularText0: "#111111",
      popularText1: "#111111",
      popularText2: "#111111",
      popularText3: "#FFFFFF",
      filterActiveBg: "#E81224",
      filterActiveBorder: "#E81224",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#1A1A1A",
      promoBannerTo: "#2A2A2A",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#AAAAAA",
      topBarBg: "#111111",
      topBarText: "#FFFFFF",
      shopTitleColor: "#E81224",
      imageBg: "#F0F0F0",
      categoryOverlayBg: "rgba(0,0,0,0.65)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. VERDE ECO — Green for eco-tech / sustainable electronics
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "verde-eco",
    name: "Verde Eco",
    description: "Verde sostenible con blancos limpios — tech responsable con el planeta",
    style: "nature",
    preview: ["#2E7D32", "#FFFFFF", "#43A047", "#F1F8E9", "#388E3C"],
    colors: {
      primary: "#2E7D32",
      secondary: "#43A047",
      background: "#FAFDF8",
      textPrimary: "#1B3A1E",
      textSecondary: "#2E5031",
      textMuted: "#5A7A5D",
      textSubtle: "#7A9A7D",
      textFooter: "#6B8070",
      textBreadcrumb: "#96AE98",
      textSummerSale: "#5A7A5D",
      headerBg: "#2E7D32",
      sectionBg: "#F4FAF2",
      cardBg: "#FFFFFF",
      surface: "#EDF7EA",
      searchBg: "#EDF7EA",
      reviewBg: "#F4FAF2",
      paginationBg: "#EDF7EA",
      specBadgeBg: "#EDF7EA",
      border: "#C8E6C9",
      borderLight: "#E8F5E9",
      borderInput: "#A5D6A7",
      borderMid: "#C8E6C9",
      navBorder: "#1B5E20",
      buttonBg: "#2E7D32",
      buttonText: "#FFFFFF",
      footerBg: "#1B5E20",
      badgeBg: "#2E7D32",
      badgeText: "#FFFFFF",
      ratingStar: "#F9A825",
      ratingBarBg: "#C8E6C9",
      tabActive: "#2E7D32",
      categoryActiveBg: "#2E7D32",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F4FAF2",
      popularBg1: "#DCF0DC",
      popularBg2: "#B4D8B4",
      popularBg3: "#80A880",
      popularText0: "#1B3A1E",
      popularText1: "#1B3A1E",
      popularText2: "#1B3A1E",
      popularText3: "#FFFFFF",
      filterActiveBg: "#2E7D32",
      filterActiveBorder: "#2E7D32",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#EDF7EA",
      promoBannerTo: "#C8E6C9",
      promoBannerText: "#1B3A1E",
      promoBannerSubtext: "#5A7A5D",
      topBarBg: "#1B5E20",
      topBarText: "#FFFFFF",
      shopTitleColor: "#2E7D32",
      imageBg: "#EDF7EA",
      categoryOverlayBg: "rgba(27,62,30,0.65)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. NARANJA ENERGÍA — Energetic orange for accessories
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "naranja-energia",
    name: "Naranja Energía",
    description: "Naranja vibrante y accesorios — energético, dinámico y llamativo",
    style: "vibrant",
    preview: ["#F57C00", "#FFFFFF", "#FF9800", "#FFF3E0", "#E65100"],
    colors: {
      primary: "#E65100",
      secondary: "#F57C00",
      background: "#FFFBF5",
      textPrimary: "#1A1008",
      textSecondary: "#3A2810",
      textMuted: "#7A5832",
      textSubtle: "#9A7852",
      textFooter: "#7A6050",
      textBreadcrumb: "#A89080",
      textSummerSale: "#7A5832",
      headerBg: "#E65100",
      sectionBg: "#FFF8EE",
      cardBg: "#FFFFFF",
      surface: "#FFF0DC",
      searchBg: "#FFF0DC",
      reviewBg: "#FFF8EE",
      paginationBg: "#FFF0DC",
      specBadgeBg: "#FFF0DC",
      border: "#FFD9A8",
      borderLight: "#FFECD1",
      borderInput: "#FFB96A",
      borderMid: "#FFD9A8",
      navBorder: "#BF360C",
      buttonBg: "#E65100",
      buttonText: "#FFFFFF",
      footerBg: "#BF360C",
      badgeBg: "#E65100",
      badgeText: "#FFFFFF",
      ratingStar: "#FFB300",
      ratingBarBg: "#FFD9A8",
      tabActive: "#E65100",
      categoryActiveBg: "#E65100",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FFF5E5",
      popularBg1: "#FFE4C0",
      popularBg2: "#FFCA80",
      popularBg3: "#F59840",
      popularText0: "#1A1008",
      popularText1: "#1A1008",
      popularText2: "#1A1008",
      popularText3: "#FFFFFF",
      filterActiveBg: "#E65100",
      filterActiveBorder: "#E65100",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#FFF0DC",
      promoBannerTo: "#FFD9A8",
      promoBannerText: "#1A1008",
      promoBannerSubtext: "#7A5832",
      topBarBg: "#BF360C",
      topBarText: "#FFFFFF",
      shopTitleColor: "#E65100",
      imageBg: "#FFF0DC",
      categoryOverlayBg: "rgba(26,16,8,0.65)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. GRAFITO MODERNO — Monochrome gray, professional
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "grafito-moderno",
    name: "Grafito Moderno",
    description: "Grises profesionales en escala — sobrio, moderno y sin distracciones",
    style: "monochrome",
    preview: ["#2D2D2D", "#FFFFFF", "#555555", "#F4F4F4", "#888888"],
    colors: {
      primary: "#2D2D2D",
      secondary: "#555555",
      background: "#F7F7F7",
      textPrimary: "#1A1A1A",
      textSecondary: "#3A3A3A",
      textMuted: "#686868",
      textSubtle: "#909090",
      textFooter: "#8A8A8A",
      textBreadcrumb: "#AAAAAA",
      textSummerSale: "#686868",
      headerBg: "#2D2D2D",
      sectionBg: "#F4F4F4",
      cardBg: "#FFFFFF",
      surface: "#ECECEC",
      searchBg: "#ECECEC",
      reviewBg: "#F4F4F4",
      paginationBg: "#ECECEC",
      specBadgeBg: "#ECECEC",
      border: "#DDDDDD",
      borderLight: "#EEEEEE",
      borderInput: "#C0C0C0",
      borderMid: "#DDDDDD",
      navBorder: "#1A1A1A",
      buttonBg: "#2D2D2D",
      buttonText: "#FFFFFF",
      footerBg: "#1A1A1A",
      badgeBg: "#555555",
      badgeText: "#FFFFFF",
      ratingStar: "#F5C518",
      ratingBarBg: "#DDDDDD",
      tabActive: "#2D2D2D",
      categoryActiveBg: "#2D2D2D",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F4F4F4",
      popularBg1: "#E8E8E8",
      popularBg2: "#CCCCCC",
      popularBg3: "#999999",
      popularText0: "#1A1A1A",
      popularText1: "#1A1A1A",
      popularText2: "#1A1A1A",
      popularText3: "#FFFFFF",
      filterActiveBg: "#2D2D2D",
      filterActiveBorder: "#2D2D2D",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#ECECEC",
      promoBannerTo: "#DDDDDD",
      promoBannerText: "#1A1A1A",
      promoBannerSubtext: "#686868",
      topBarBg: "#1A1A1A",
      topBarText: "#FFFFFF",
      shopTitleColor: "#2D2D2D",
      imageBg: "#ECECEC",
      categoryOverlayBg: "rgba(0,0,0,0.6)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 7. TURQUESA DIGITAL — Fresh turquoise, digital feel
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "turquesa-digital",
    name: "Turquesa Digital",
    description: "Turquesa fresco con blanco limpio — tecnología digital y conectada",
    style: "corporate",
    preview: ["#00838F", "#FFFFFF", "#006064", "#E0F7FA", "#00ACC1"],
    colors: {
      primary: "#00838F",
      secondary: "#00ACC1",
      background: "#F5FDFE",
      textPrimary: "#002E33",
      textSecondary: "#00474E",
      textMuted: "#4A7A80",
      textSubtle: "#6A9EA4",
      textFooter: "#608890",
      textBreadcrumb: "#90AFBB",
      textSummerSale: "#4A7A80",
      headerBg: "#00838F",
      sectionBg: "#F0FAFB",
      cardBg: "#FFFFFF",
      surface: "#E0F7FA",
      searchBg: "#E0F7FA",
      reviewBg: "#F0FAFB",
      paginationBg: "#E0F7FA",
      specBadgeBg: "#E0F7FA",
      border: "#B2EBF2",
      borderLight: "#D0F4F8",
      borderInput: "#80D8E6",
      borderMid: "#B2EBF2",
      navBorder: "#004D54",
      buttonBg: "#00838F",
      buttonText: "#FFFFFF",
      footerBg: "#004D54",
      badgeBg: "#00838F",
      badgeText: "#FFFFFF",
      ratingStar: "#F9A825",
      ratingBarBg: "#B2EBF2",
      tabActive: "#00838F",
      categoryActiveBg: "#00838F",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F0FBFC",
      popularBg1: "#CCECF0",
      popularBg2: "#A0D8E0",
      popularBg3: "#60A8B5",
      popularText0: "#002E33",
      popularText1: "#002E33",
      popularText2: "#002E33",
      popularText3: "#FFFFFF",
      filterActiveBg: "#00838F",
      filterActiveBorder: "#00838F",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#E0F7FA",
      promoBannerTo: "#B2EBF2",
      promoBannerText: "#002E33",
      promoBannerSubtext: "#4A7A80",
      topBarBg: "#004D54",
      topBarText: "#FFFFFF",
      shopTitleColor: "#00838F",
      imageBg: "#E0F7FA",
      categoryOverlayBg: "rgba(0,46,51,0.65)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 8. PÚRPURA INNOVACIÓN — Purple for innovative tech brands
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "purpura-innovacion",
    name: "Púrpura Innovación",
    description: "Violetas creativos con blanco limpio — imaginación y vanguardia tech",
    style: "awwwards",
    preview: ["#6200EA", "#FFFFFF", "#7C4DFF", "#EDE7F6", "#AA00FF"],
    colors: {
      primary: "#6200EA",
      secondary: "#7C4DFF",
      background: "#FDFBFF",
      textPrimary: "#1A0040",
      textSecondary: "#360080",
      textMuted: "#6B50A0",
      textSubtle: "#8870B8",
      textFooter: "#7860A0",
      textBreadcrumb: "#A898CC",
      textSummerSale: "#6B50A0",
      headerBg: "#6200EA",
      sectionBg: "#F9F5FF",
      cardBg: "#FFFFFF",
      surface: "#EDE7F6",
      searchBg: "#EDE7F6",
      reviewBg: "#F9F5FF",
      paginationBg: "#EDE7F6",
      specBadgeBg: "#EDE7F6",
      border: "#D1C4E9",
      borderLight: "#E8DFF5",
      borderInput: "#B39DDB",
      borderMid: "#D1C4E9",
      navBorder: "#3700B3",
      buttonBg: "#6200EA",
      buttonText: "#FFFFFF",
      footerBg: "#3700B3",
      badgeBg: "#6200EA",
      badgeText: "#FFFFFF",
      ratingStar: "#FFB300",
      ratingBarBg: "#D1C4E9",
      tabActive: "#6200EA",
      categoryActiveBg: "#6200EA",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F5F0FC",
      popularBg1: "#E0D0F5",
      popularBg2: "#BFA0E0",
      popularBg3: "#8A68C0",
      popularText0: "#1A0040",
      popularText1: "#1A0040",
      popularText2: "#1A0040",
      popularText3: "#FFFFFF",
      filterActiveBg: "#6200EA",
      filterActiveBorder: "#6200EA",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#EDE7F6",
      promoBannerTo: "#D1C4E9",
      promoBannerText: "#1A0040",
      promoBannerSubtext: "#6B50A0",
      topBarBg: "#3700B3",
      topBarText: "#FFFFFF",
      shopTitleColor: "#6200EA",
      imageBg: "#EDE7F6",
      categoryOverlayBg: "rgba(26,0,64,0.7)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 9. NEGRO CARBONO — Deep black, carbon fiber aesthetic (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "negro-carbono",
    name: "Negro Carbono",
    description: "Negro profundo con detalles carbono — ultra premium y misterioso",
    style: "premium",
    preview: ["#121212", "#E0E0E0", "#1E1E1E", "#FF6B35", "#2C2C2C"],
    colors: {
      primary: "#FF6B35",
      secondary: "#E0E0E0",
      background: "#121212",
      textPrimary: "#E8E8E8",
      textSecondary: "#C0C0C0",
      textMuted: "#909090",
      textSubtle: "#B0B0B0",
      textFooter: "#808080",
      textBreadcrumb: "#606060",
      textSummerSale: "#909090",
      headerBg: "#0A0A0A",
      sectionBg: "#121212",
      cardBg: "#1E1E1E",
      surface: "#2C2C2C",
      searchBg: "#1E1E1E",
      reviewBg: "#1E1E1E",
      paginationBg: "#1E1E1E",
      specBadgeBg: "#2C2C2C",
      border: "#383838",
      borderLight: "#2A2A2A",
      borderInput: "#505050",
      borderMid: "#383838",
      navBorder: "#252525",
      buttonBg: "#FF6B35",
      buttonText: "#0A0A0A",
      footerBg: "#080808",
      badgeBg: "#FF6B35",
      badgeText: "#0A0A0A",
      ratingStar: "#FFD600",
      ratingBarBg: "#383838",
      tabActive: "#FF6B35",
      categoryActiveBg: "#FF6B35",
      categoryActiveText: "#0A0A0A",
      popularBg0: "#3A3A3A",
      popularBg1: "#2C2C2C",
      popularBg2: "#202020",
      popularBg3: "#141414",
      popularText0: "#E8E8E8",
      popularText1: "#E8E8E8",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#FF6B35",
      filterActiveBorder: "#FF6B35",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#2C2C2C",
      promoBannerTo: "#1E1E1E",
      promoBannerText: "#E8E8E8",
      promoBannerSubtext: "#909090",
      topBarBg: "#080808",
      topBarText: "#C0C0C0",
      shopTitleColor: "#FF6B35",
      imageBg: "#2C2C2C",
      categoryOverlayBg: "rgba(0,0,0,0.75)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 10. BLANCO APPLE — Minimal white, clean Apple-like
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "blanco-apple",
    name: "Blanco Apple",
    description: "Blanco total con grises sutiles — minimalismo Apple de máxima limpieza",
    style: "minimal",
    preview: ["#000000", "#FFFFFF", "#0066CC", "#F5F5F7", "#888888"],
    colors: {
      primary: "#000000",
      secondary: "#0066CC",
      background: "#FFFFFF",
      textPrimary: "#1D1D1F",
      textSecondary: "#424245",
      textMuted: "#6E6E73",
      textSubtle: "#A0A0A5",
      textFooter: "#86868B",
      textBreadcrumb: "#AEAEB2",
      textSummerSale: "#6E6E73",
      headerBg: "#FFFFFF",
      sectionBg: "#F5F5F7",
      cardBg: "#FFFFFF",
      surface: "#F5F5F7",
      searchBg: "#F5F5F7",
      reviewBg: "#FAFAFA",
      paginationBg: "#F5F5F7",
      specBadgeBg: "#F5F5F7",
      border: "#D2D2D7",
      borderLight: "#E8E8ED",
      borderInput: "#C7C7CC",
      borderMid: "#D2D2D7",
      navBorder: "#D2D2D7",
      buttonBg: "#000000",
      buttonText: "#FFFFFF",
      footerBg: "#F5F5F7",
      badgeBg: "#0066CC",
      badgeText: "#FFFFFF",
      ratingStar: "#FF9F0A",
      ratingBarBg: "#D2D2D7",
      tabActive: "#000000",
      categoryActiveBg: "#000000",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F5F5F7",
      popularBg1: "#E8E8ED",
      popularBg2: "#CCCCCC",
      popularBg3: "#989898",
      popularText0: "#1D1D1F",
      popularText1: "#1D1D1F",
      popularText2: "#1D1D1F",
      popularText3: "#FFFFFF",
      filterActiveBg: "#000000",
      filterActiveBorder: "#000000",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#F5F5F7",
      promoBannerTo: "#E8E8ED",
      promoBannerText: "#1D1D1F",
      promoBannerSubtext: "#6E6E73",
      topBarBg: "#F5F5F7",
      topBarText: "#1D1D1F",
      shopTitleColor: "#000000",
      imageBg: "#F5F5F7",
      categoryOverlayBg: "rgba(0,0,0,0.5)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 11. AZUL MARINO — Navy professional, corporate
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "azul-marino",
    name: "Azul Marino",
    description: "Azul marino corporativo con blanco limpio — autoridad y confianza",
    style: "corporate",
    preview: ["#1A237E", "#FFFFFF", "#283593", "#E8EAF6", "#3949AB"],
    colors: {
      primary: "#1A237E",
      secondary: "#3949AB",
      background: "#FAFBFF",
      textPrimary: "#0D1340",
      textSecondary: "#1A237E",
      textMuted: "#5C6BC0",
      textSubtle: "#7986CB",
      textFooter: "#7880B0",
      textBreadcrumb: "#9FA8DA",
      textSummerSale: "#5C6BC0",
      headerBg: "#1A237E",
      sectionBg: "#F3F4FC",
      cardBg: "#FFFFFF",
      surface: "#E8EAF6",
      searchBg: "#E8EAF6",
      reviewBg: "#F3F4FC",
      paginationBg: "#E8EAF6",
      specBadgeBg: "#E8EAF6",
      border: "#C5CAE9",
      borderLight: "#DDE0F5",
      borderInput: "#9FA8DA",
      borderMid: "#C5CAE9",
      navBorder: "#0D1340",
      buttonBg: "#1A237E",
      buttonText: "#FFFFFF",
      footerBg: "#0D1340",
      badgeBg: "#1A237E",
      badgeText: "#FFFFFF",
      ratingStar: "#FFC107",
      ratingBarBg: "#C5CAE9",
      tabActive: "#1A237E",
      categoryActiveBg: "#1A237E",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F0F2FB",
      popularBg1: "#D8DCF4",
      popularBg2: "#B0B8E4",
      popularBg3: "#7880C4",
      popularText0: "#0D1340",
      popularText1: "#0D1340",
      popularText2: "#0D1340",
      popularText3: "#FFFFFF",
      filterActiveBg: "#1A237E",
      filterActiveBorder: "#1A237E",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#E8EAF6",
      promoBannerTo: "#C5CAE9",
      promoBannerText: "#0D1340",
      promoBannerSubtext: "#5C6BC0",
      topBarBg: "#0D1340",
      topBarText: "#FFFFFF",
      shopTitleColor: "#1A237E",
      imageBg: "#E8EAF6",
      categoryOverlayBg: "rgba(13,19,64,0.7)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 12. CORAL TENDENCIA — Trendy coral/peach
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "coral-tendencia",
    name: "Coral Tendencia",
    description: "Coral moderno y melocotón suave — contemporáneo, fresco y tendencia",
    style: "vibrant",
    preview: ["#FF6B6B", "#FFFFFF", "#FF8E53", "#FFF0EE", "#4ECDC4"],
    colors: {
      primary: "#FF6B6B",
      secondary: "#FF8E53",
      background: "#FFFAF9",
      textPrimary: "#2A1010",
      textSecondary: "#5A2020",
      textMuted: "#9A5050",
      textSubtle: "#B88080",
      textFooter: "#9A7070",
      textBreadcrumb: "#C0A0A0",
      textSummerSale: "#9A5050",
      headerBg: "#FF6B6B",
      sectionBg: "#FFF5F3",
      cardBg: "#FFFFFF",
      surface: "#FFE8E4",
      searchBg: "#FFE8E4",
      reviewBg: "#FFF5F3",
      paginationBg: "#FFE8E4",
      specBadgeBg: "#FFE8E4",
      border: "#FFD0C8",
      borderLight: "#FFECEA",
      borderInput: "#FFB0A0",
      borderMid: "#FFD0C8",
      navBorder: "#CC3333",
      buttonBg: "#FF6B6B",
      buttonText: "#FFFFFF",
      footerBg: "#CC3333",
      badgeBg: "#FF6B6B",
      badgeText: "#FFFFFF",
      ratingStar: "#FFB300",
      ratingBarBg: "#FFD0C8",
      tabActive: "#FF6B6B",
      categoryActiveBg: "#FF6B6B",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FFF2F0",
      popularBg1: "#FFE0D8",
      popularBg2: "#FFC0B4",
      popularBg3: "#F09080",
      popularText0: "#2A1010",
      popularText1: "#2A1010",
      popularText2: "#2A1010",
      popularText3: "#FFFFFF",
      filterActiveBg: "#FF6B6B",
      filterActiveBorder: "#FF6B6B",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#FFE8E4",
      promoBannerTo: "#FFD0C8",
      promoBannerText: "#2A1010",
      promoBannerSubtext: "#9A5050",
      topBarBg: "#CC3333",
      topBarText: "#FFFFFF",
      shopTitleColor: "#FF6B6B",
      imageBg: "#FFE8E4",
      categoryOverlayBg: "rgba(42,16,16,0.65)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 13. CIAN NEÓN — Cyberpunk neon cyan (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "cian-neon",
    name: "Cian Neón",
    description: "Cian eléctrico sobre negro profundo — cyberpunk digital máximo impacto",
    style: "cyberpunk",
    preview: ["#0A0E14", "#00E5FF", "#1A2030", "#E0FAFF", "#FF00A0"],
    colors: {
      primary: "#00E5FF",
      secondary: "#FF00A0",
      background: "#0A0E14",
      textPrimary: "#D8F4FF",
      textSecondary: "#A0D8EC",
      textMuted: "#5A8AA0",
      textSubtle: "#80B4CC",
      textFooter: "#507888",
      textBreadcrumb: "#304858",
      textSummerSale: "#5A8AA0",
      headerBg: "#080C10",
      sectionBg: "#0A0E14",
      cardBg: "#141C26",
      surface: "#1A2030",
      searchBg: "#141C26",
      reviewBg: "#141C26",
      paginationBg: "#141C26",
      specBadgeBg: "#1A2030",
      border: "#1E3048",
      borderLight: "#162438",
      borderInput: "#304860",
      borderMid: "#1E3048",
      navBorder: "#102030",
      buttonBg: "#00E5FF",
      buttonText: "#080C10",
      footerBg: "#050810",
      badgeBg: "#FF00A0",
      badgeText: "#FFFFFF",
      ratingStar: "#FFE000",
      ratingBarBg: "#1E3048",
      tabActive: "#00E5FF",
      categoryActiveBg: "#00E5FF",
      categoryActiveText: "#080C10",
      popularBg0: "#28384A",
      popularBg1: "#1E2C3E",
      popularBg2: "#142032",
      popularBg3: "#0C1622",
      popularText0: "#D8F4FF",
      popularText1: "#D8F4FF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#00E5FF",
      filterActiveBorder: "#00E5FF",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#1A2030",
      promoBannerTo: "#141C26",
      promoBannerText: "#D8F4FF",
      promoBannerSubtext: "#5A8AA0",
      topBarBg: "#050810",
      topBarText: "#00E5FF",
      shopTitleColor: "#00E5FF",
      imageBg: "#1A2030",
      categoryOverlayBg: "rgba(0,0,0,0.8)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 14. DORADO PREMIUM — Gold/cream premium electronics
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "dorado-premium",
    name: "Dorado Premium",
    description: "Oro y crema cálida — lujo accesible para electrónica de alta gama",
    style: "premium",
    preview: ["#B8860B", "#FFFDF5", "#8B6914", "#FFF8E8", "#D4A820"],
    colors: {
      primary: "#8B6914",
      secondary: "#B8860B",
      background: "#FFFDF5",
      textPrimary: "#2A1E00",
      textSecondary: "#4A3A10",
      textMuted: "#7A6030",
      textSubtle: "#9A8050",
      textFooter: "#907A50",
      textBreadcrumb: "#B8A070",
      textSummerSale: "#7A6030",
      headerBg: "#2A1E00",
      sectionBg: "#FFFBEE",
      cardBg: "#FFFFFF",
      surface: "#FFF3D0",
      searchBg: "#FFF3D0",
      reviewBg: "#FFFBEE",
      paginationBg: "#FFF3D0",
      specBadgeBg: "#FFF3D0",
      border: "#E8D898",
      borderLight: "#F5ECCC",
      borderInput: "#CDB86A",
      borderMid: "#E8D898",
      navBorder: "#4A3A10",
      buttonBg: "#8B6914",
      buttonText: "#FFFDF5",
      footerBg: "#1A1000",
      badgeBg: "#B8860B",
      badgeText: "#FFFFFF",
      ratingStar: "#D4A820",
      ratingBarBg: "#E8D898",
      tabActive: "#8B6914",
      categoryActiveBg: "#8B6914",
      categoryActiveText: "#FFFDF5",
      popularBg0: "#FFF8E4",
      popularBg1: "#F0E4B8",
      popularBg2: "#D4C07C",
      popularBg3: "#A89044",
      popularText0: "#2A1E00",
      popularText1: "#2A1E00",
      popularText2: "#2A1E00",
      popularText3: "#FFFDF5",
      filterActiveBg: "#8B6914",
      filterActiveBorder: "#B8860B",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#FFF3D0",
      promoBannerTo: "#E8D898",
      promoBannerText: "#2A1E00",
      promoBannerSubtext: "#7A6030",
      topBarBg: "#1A1000",
      topBarText: "#D4A820",
      shopTitleColor: "#8B6914",
      imageBg: "#FFF3D0",
      categoryOverlayBg: "rgba(42,30,0,0.65)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 15. ESMERALDA LUJO — Emerald green luxury (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "esmeralda-lujo",
    name: "Esmeralda Lujo",
    description: "Verde esmeralda profundo con detalles dorados — lujo oscuro y misterioso",
    style: "premium",
    preview: ["#0D2818", "#00C853", "#1A3A28", "#C8F5DC", "#D4A820"],
    colors: {
      primary: "#00C853",
      secondary: "#D4A820",
      background: "#0D1F16",
      textPrimary: "#C8F0DC",
      textSecondary: "#90C8A8",
      textMuted: "#5A9070",
      textSubtle: "#80B090",
      textFooter: "#507860",
      textBreadcrumb: "#385848",
      textSummerSale: "#5A9070",
      headerBg: "#0A1810",
      sectionBg: "#0D1F16",
      cardBg: "#162A1E",
      surface: "#1E3828",
      searchBg: "#162A1E",
      reviewBg: "#162A1E",
      paginationBg: "#162A1E",
      specBadgeBg: "#1E3828",
      border: "#244830",
      borderLight: "#1A3820",
      borderInput: "#306040",
      borderMid: "#244830",
      navBorder: "#163020",
      buttonBg: "#00C853",
      buttonText: "#0A1810",
      footerBg: "#060E08",
      badgeBg: "#D4A820",
      badgeText: "#0A1810",
      ratingStar: "#D4A820",
      ratingBarBg: "#244830",
      tabActive: "#00C853",
      categoryActiveBg: "#00C853",
      categoryActiveText: "#0A1810",
      popularBg0: "#2E5038",
      popularBg1: "#224028",
      popularBg2: "#18301E",
      popularBg3: "#0E2014",
      popularText0: "#C8F0DC",
      popularText1: "#C8F0DC",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#00C853",
      filterActiveBorder: "#00C853",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#1E3828",
      promoBannerTo: "#162A1E",
      promoBannerText: "#C8F0DC",
      promoBannerSubtext: "#5A9070",
      topBarBg: "#060E08",
      topBarText: "#00C853",
      shopTitleColor: "#00C853",
      imageBg: "#1E3828",
      categoryOverlayBg: "rgba(0,0,0,0.78)",
      categoryOverlayText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 16. ROSA TECH — Modern pink, tech feminine
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "rosa-tech",
    name: "Rosa Tech",
    description: "Rosa moderno y blanco fresco — tecnología femenina sin clichés",
    style: "playful",
    preview: ["#E91E8C", "#FFFFFF", "#FF4DB8", "#FFF0F8", "#9C27B0"],
    colors: {
      primary: "#E91E8C",
      secondary: "#9C27B0",
      background: "#FFFBFD",
      textPrimary: "#1A001A",
      textSecondary: "#400040",
      textMuted: "#8A3870",
      textSubtle: "#AA5888",
      textFooter: "#9A6888",
      textBreadcrumb: "#C098B0",
      textSummerSale: "#8A3870",
      headerBg: "#E91E8C",
      sectionBg: "#FFF5FA",
      cardBg: "#FFFFFF",
      surface: "#FFE8F4",
      searchBg: "#FFE8F4",
      reviewBg: "#FFF5FA",
      paginationBg: "#FFE8F4",
      specBadgeBg: "#FFE8F4",
      border: "#F8C0DC",
      borderLight: "#FFDAEE",
      borderInput: "#F090C0",
      borderMid: "#F8C0DC",
      navBorder: "#AA0060",
      buttonBg: "#E91E8C",
      buttonText: "#FFFFFF",
      footerBg: "#880040",
      badgeBg: "#9C27B0",
      badgeText: "#FFFFFF",
      ratingStar: "#FFB300",
      ratingBarBg: "#F8C0DC",
      tabActive: "#E91E8C",
      categoryActiveBg: "#E91E8C",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FFF0F8",
      popularBg1: "#FFD8EE",
      popularBg2: "#F8B0D4",
      popularBg3: "#E880B0",
      popularText0: "#1A001A",
      popularText1: "#1A001A",
      popularText2: "#1A001A",
      popularText3: "#FFFFFF",
      filterActiveBg: "#E91E8C",
      filterActiveBorder: "#E91E8C",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#FFE8F4",
      promoBannerTo: "#F8C0DC",
      promoBannerText: "#1A001A",
      promoBannerSubtext: "#8A3870",
      topBarBg: "#880040",
      topBarText: "#FFFFFF",
      shopTitleColor: "#E91E8C",
      imageBg: "#FFE8F4",
      categoryOverlayBg: "rgba(26,0,26,0.65)",
      categoryOverlayText: "#FFFFFF",
    },
  },
];
