// Furniture Dark Template — Color Palettes
// 16 palettes covering furniture/interior design aesthetics.
// Palette #1 (carbon-elegante) matches config.ts defaults EXACTLY.
// Dark palettes (~6): carbon-elegante, roble-natural, oliva-nordico,
//   grafito-industrial, verde-bosque, negro-zen
// Light palettes (~10): marmol-blanco, terracota-rustico, azul-marino-clasico,
//   crema-parisino, arena-mediterraneo, burdeos-opulento, gris-escandinavo,
//   cobre-art-deco, lavanda-suave, mostaza-retro

import type { ColorPalette } from "@/types/templates/config-schema";

export const furnitureDarkPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. CARBON ELEGANTE — Original furniture-dark default (DARK)
  //    Matches config.ts colors EXACTLY — do not change any value.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "carbon-elegante",
    name: "Carbón Elegante",
    description: "Negro profundo con acento amarillo verdoso — el original oscuro y sofisticado",
    style: "premium",
    preview: ["#EFF422", "#181818", "#F5F5F4", "#4D4D4D", "#B0BA38"],
    colors: {
      primary: "#EFF422",
      secondary: "#4D4D4D",
      background: "#181818",
      cardBg: "#F5F5F4",
      border: "#333333",
      surface: "#4D4D4D",
      searchBg: "#4D4D4D",
      textMuted: "#A0A0A0",
      textPrimary: "#FFFFFF",
      headerBg: "#181818",
      sectionBg: "#181818",
      buttonBg: "#EFF422",
      buttonText: "#181818",
      footerBg: "#181818",
      badgeBg: "#EFF422",
      badgeText: "#181818",
      navBorder: "#333333",
      textSecondary: "#D0D0D0",
      textSubtle: "#A8A8A8",
      textFooter: "#666666",
      borderLight: "#242424",
      borderInput: "#444444",
      borderMid: "#4A4A4A",
      ratingBarBg: "#333333",
      ratingStar: "#EFF422",
      paginationBg: "#4D4D4D",
      textSummerSale: "#A8A8A8",
      textBreadcrumb: "#A8A8A8",
      tabActive: "#EFF422",
      categoryActiveBg: "#5A5A5A",
      categoryActiveText: "#EFF422",
      specBadgeBg: "#242424",
      reviewBg: "#242424",
      popularBg0: "#3A3A3A",
      popularBg1: "#2E2E2E",
      popularBg2: "#222222",
      popularBg3: "#1A1A1A",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. ROBLE NATURAL — Warm oak/wood tones on dark background (DARK)
  //    Deep warm browns + amber accent — artisan woodcraft aesthetic.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "roble-natural",
    name: "Roble Natural",
    description: "Tonos de roble cálido sobre fondo oscuro — artesanía en madera premium",
    style: "warm",
    preview: ["#C8922A", "#1C1510", "#F0E4C8", "#3A2C1C", "#8B5E1A"],
    colors: {
      primary: "#C8922A",
      secondary: "#3A2C1C",
      background: "#1C1510",
      cardBg: "#F0E4C8",
      border: "#2E2218",
      surface: "#3A2C1C",
      searchBg: "#3A2C1C",
      textMuted: "#9A7A50",
      textPrimary: "#F0E4C8",
      headerBg: "#161008",
      sectionBg: "#161008",
      buttonBg: "#C8922A",
      buttonText: "#161008",
      footerBg: "#100C06",
      badgeBg: "#C8922A",
      badgeText: "#161008",
      navBorder: "#2E2218",
      textSecondary: "#D4B888",
      textSubtle: "#A88A5C",
      textFooter: "#6A502C",
      borderLight: "#221A10",
      borderInput: "#3A2C1C",
      borderMid: "#443220",
      ratingBarBg: "#2E2218",
      ratingStar: "#C8922A",
      paginationBg: "#3A2C1C",
      textSummerSale: "#9A7A50",
      textBreadcrumb: "#9A7A50",
      tabActive: "#C8922A",
      categoryActiveBg: "#4A3828",
      categoryActiveText: "#C8922A",
      specBadgeBg: "#221A10",
      reviewBg: "#221A10",
      popularBg0: "#3E3020",
      popularBg1: "#322618",
      popularBg2: "#261C12",
      popularBg3: "#1A120C",
      popularText0: "#F0E4C8",
      popularText1: "#F0E4C8",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. MARMOL BLANCO — Light marble/white elegant (LIGHT)
  //    Crisp white with cool marble veins — high-end showroom feel.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "marmol-blanco",
    name: "Mármol Blanco",
    description: "Blanco mármol con detalles grafito — elegancia de showroom de lujo",
    style: "minimal",
    preview: ["#2C2C2C", "#FAFAFA", "#FFFFFF", "#E8E4E0", "#8A8A8A"],
    colors: {
      primary: "#2C2C2C",
      secondary: "#6A6A6A",
      background: "#FAFAFA",
      cardBg: "#FFFFFF",
      border: "#E0DCD8",
      surface: "#F0EEEC",
      searchBg: "#F0EEEC",
      textMuted: "#7A7A7A",
      textPrimary: "#1A1A1A",
      headerBg: "#FFFFFF",
      sectionBg: "#F5F3F1",
      buttonBg: "#2C2C2C",
      buttonText: "#FFFFFF",
      footerBg: "#1A1A1A",
      badgeBg: "#2C2C2C",
      badgeText: "#FFFFFF",
      navBorder: "#E0DCD8",
      textSecondary: "#3A3A3A",
      textSubtle: "#5A5A5A",
      textFooter: "#A0A0A0",
      borderLight: "#EEECE8",
      borderInput: "#D0CCC8",
      borderMid: "#C4C0BC",
      ratingBarBg: "#E0DCD8",
      ratingStar: "#C8A050",
      paginationBg: "#F0EEEC",
      textSummerSale: "#7A7A7A",
      textBreadcrumb: "#7A7A7A",
      tabActive: "#2C2C2C",
      categoryActiveBg: "#2C2C2C",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F0EEEC",
      reviewBg: "#F5F3F1",
      popularBg0: "#ECEAE6",
      popularBg1: "#DCD8D2",
      popularBg2: "#C4BEB8",
      popularBg3: "#A09894",
      popularText0: "#1A1A1A",
      popularText1: "#1A1A1A",
      popularText2: "#1A1A1A",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. OLIVA NORDICO — Olive/sage nordic on dark (DARK)
  //    Muted olive greens with charcoal — Scandinavian nature aesthetic.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "oliva-nordico",
    name: "Oliva Nórdico",
    description: "Oliva y salvia sobre oscuro — naturaleza nórdica sofisticada",
    style: "nature",
    preview: ["#A0B862", "#161A10", "#ECF0DC", "#2A3020", "#5A6A3A"],
    colors: {
      primary: "#A0B862",
      secondary: "#2A3020",
      background: "#161A10",
      cardBg: "#ECF0DC",
      border: "#222A18",
      surface: "#2A3020",
      searchBg: "#2A3020",
      textMuted: "#7A8C5A",
      textPrimary: "#ECF0DC",
      headerBg: "#10140C",
      sectionBg: "#10140C",
      buttonBg: "#A0B862",
      buttonText: "#10140C",
      footerBg: "#0C1008",
      badgeBg: "#A0B862",
      badgeText: "#0C1008",
      navBorder: "#222A18",
      textSecondary: "#C0CC9A",
      textSubtle: "#8A9C6A",
      textFooter: "#506038",
      borderLight: "#1A2014",
      borderInput: "#2A3020",
      borderMid: "#323C26",
      ratingBarBg: "#222A18",
      ratingStar: "#A0B862",
      paginationBg: "#2A3020",
      textSummerSale: "#8A9C6A",
      textBreadcrumb: "#8A9C6A",
      tabActive: "#A0B862",
      categoryActiveBg: "#363E28",
      categoryActiveText: "#A0B862",
      specBadgeBg: "#1A2014",
      reviewBg: "#1A2014",
      popularBg0: "#323C24",
      popularBg1: "#28301C",
      popularBg2: "#1E2414",
      popularBg3: "#141A0E",
      popularText0: "#ECF0DC",
      popularText1: "#ECF0DC",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. TERRACOTA RUSTICO — Earthy terracotta/clay warm (LIGHT)
  //    Sun-baked terracotta on warm cream — Mediterranean village charm.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "terracota-rustico",
    name: "Terracota Rústico",
    description: "Terracota y arcilla sobre crema cálida — encanto mediterráneo rústico",
    style: "warm",
    preview: ["#C05A2A", "#FAF0E8", "#FFFFFF", "#F0D8C8", "#8B3A14"],
    colors: {
      primary: "#C05A2A",
      secondary: "#8B3A14",
      background: "#FAF0E8",
      cardBg: "#FFFFFF",
      border: "#E8D0BC",
      surface: "#F0D8C8",
      searchBg: "#F0D8C8",
      textMuted: "#9A6A50",
      textPrimary: "#2C1408",
      headerBg: "#FFFFFF",
      sectionBg: "#FAF0E8",
      buttonBg: "#C05A2A",
      buttonText: "#FFFFFF",
      footerBg: "#2C1408",
      badgeBg: "#C05A2A",
      badgeText: "#FFFFFF",
      navBorder: "#E8D0BC",
      textSecondary: "#4A2010",
      textSubtle: "#7A4A30",
      textFooter: "#C8A080",
      borderLight: "#F0D8C8",
      borderInput: "#D8B89A",
      borderMid: "#C8A080",
      ratingBarBg: "#E8D0BC",
      ratingStar: "#E08020",
      paginationBg: "#F0D8C8",
      textSummerSale: "#9A6A50",
      textBreadcrumb: "#9A6A50",
      tabActive: "#C05A2A",
      categoryActiveBg: "#C05A2A",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F0D8C8",
      reviewBg: "#FDF4EE",
      popularBg0: "#F0D8C8",
      popularBg1: "#E4C4A8",
      popularBg2: "#CCAA88",
      popularBg3: "#A88060",
      popularText0: "#2C1408",
      popularText1: "#2C1408",
      popularText2: "#2C1408",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. AZUL MARINO CLASICO — Navy classic furniture (LIGHT)
  //    Deep navy with gold — timeless British club room elegance.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "azul-marino-clasico",
    name: "Azul Marino Clásico",
    description: "Azul marino profundo con oro — elegancia clásica de salón inglés",
    style: "corporate",
    preview: ["#1A3A6E", "#F5F7FA", "#FFFFFF", "#C8A840", "#E8EDF5"],
    colors: {
      primary: "#1A3A6E",
      secondary: "#4A6A9E",
      background: "#F5F7FA",
      cardBg: "#FFFFFF",
      border: "#D0D8E8",
      surface: "#E8EDF5",
      searchBg: "#E8EDF5",
      textMuted: "#6A7A9A",
      textPrimary: "#0A1C3A",
      headerBg: "#FFFFFF",
      sectionBg: "#F5F7FA",
      buttonBg: "#1A3A6E",
      buttonText: "#FFFFFF",
      footerBg: "#0A1C3A",
      badgeBg: "#1A3A6E",
      badgeText: "#FFFFFF",
      navBorder: "#D0D8E8",
      textSecondary: "#1E3A6A",
      textSubtle: "#4A5A78",
      textFooter: "#8090B0",
      borderLight: "#E8EDF5",
      borderInput: "#C0CCDC",
      borderMid: "#B0BCCE",
      ratingBarBg: "#D0D8E8",
      ratingStar: "#C8A840",
      paginationBg: "#E8EDF5",
      textSummerSale: "#6A7A9A",
      textBreadcrumb: "#6A7A9A",
      tabActive: "#1A3A6E",
      categoryActiveBg: "#1A3A6E",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#E8EDF5",
      reviewBg: "#F0F3F8",
      popularBg0: "#E4EAF4",
      popularBg1: "#CDD8ED",
      popularBg2: "#B0C0DE",
      popularBg3: "#8A9EC4",
      popularText0: "#0A1C3A",
      popularText1: "#0A1C3A",
      popularText2: "#0A1C3A",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 7. CREMA PARISINO — Cream/beige Parisian elegance (LIGHT)
  //    Warm champagne and dusty rose — Haussmanian Parisian chic.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "crema-parisino",
    name: "Crema Parisino",
    description: "Crema champán con rosa polvo — elegancia parisina con carácter francés",
    style: "minimal",
    preview: ["#9A6A58", "#FAF6F0", "#FFFFFF", "#F0E4D8", "#C8A898"],
    colors: {
      primary: "#9A6A58",
      secondary: "#7A4A38",
      background: "#FAF6F0",
      cardBg: "#FFFFFF",
      border: "#EAE0D4",
      surface: "#F4EDE4",
      searchBg: "#F4EDE4",
      textMuted: "#9A8070",
      textPrimary: "#2A1C14",
      headerBg: "#FFFFFF",
      sectionBg: "#FAF6F0",
      buttonBg: "#9A6A58",
      buttonText: "#FFFFFF",
      footerBg: "#2A1C14",
      badgeBg: "#9A6A58",
      badgeText: "#FFFFFF",
      navBorder: "#EAE0D4",
      textSecondary: "#4A3028",
      textSubtle: "#7A6058",
      textFooter: "#C0A898",
      borderLight: "#F0E8DC",
      borderInput: "#D8C8BC",
      borderMid: "#C8B8A8",
      ratingBarBg: "#EAE0D4",
      ratingStar: "#C8903A",
      paginationBg: "#F4EDE4",
      textSummerSale: "#9A8070",
      textBreadcrumb: "#9A8070",
      tabActive: "#9A6A58",
      categoryActiveBg: "#9A6A58",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F4EDE4",
      reviewBg: "#FDF8F4",
      popularBg0: "#F0E4D8",
      popularBg1: "#E4D0C4",
      popularBg2: "#CDB8A8",
      popularBg3: "#A89080",
      popularText0: "#2A1C14",
      popularText1: "#2A1C14",
      popularText2: "#2A1C14",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 8. GRAFITO INDUSTRIAL — Dark industrial gray (DARK)
  //    Pure anthracite palette — brutalist warehouse furniture showroom.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "grafito-industrial",
    name: "Grafito Industrial",
    description: "Antracita puro y concreto oscuro — showroom industrial urbano sin concesiones",
    style: "corporate",
    preview: ["#E8E8E8", "#141414", "#F4F4F4", "#383838", "#888888"],
    colors: {
      primary: "#E8E8E8",
      secondary: "#383838",
      background: "#141414",
      cardBg: "#F4F4F4",
      border: "#2C2C2C",
      surface: "#282828",
      searchBg: "#282828",
      textMuted: "#888888",
      textPrimary: "#F4F4F4",
      headerBg: "#0E0E0E",
      sectionBg: "#0E0E0E",
      buttonBg: "#E8E8E8",
      buttonText: "#141414",
      footerBg: "#0A0A0A",
      badgeBg: "#E8E8E8",
      badgeText: "#141414",
      navBorder: "#2C2C2C",
      textSecondary: "#C4C4C4",
      textSubtle: "#909090",
      textFooter: "#5A5A5A",
      borderLight: "#1E1E1E",
      borderInput: "#3A3A3A",
      borderMid: "#404040",
      ratingBarBg: "#2C2C2C",
      ratingStar: "#E8E8E8",
      paginationBg: "#282828",
      textSummerSale: "#909090",
      textBreadcrumb: "#909090",
      tabActive: "#E8E8E8",
      categoryActiveBg: "#484848",
      categoryActiveText: "#141414",
      specBadgeBg: "#1E1E1E",
      reviewBg: "#1E1E1E",
      popularBg0: "#343434",
      popularBg1: "#282828",
      popularBg2: "#1C1C1C",
      popularBg3: "#141414",
      popularText0: "#F4F4F4",
      popularText1: "#F4F4F4",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 9. VERDE BOSQUE — Deep forest green luxury (DARK)
  //    Hunting lodge deep greens + ivory — aristocratic natural luxury.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "verde-bosque",
    name: "Verde Bosque",
    description: "Verdes profundos y marfil — lujo forestal aristocrático con carácter inglés",
    style: "nature",
    preview: ["#7EC86A", "#0C180E", "#E8F4E0", "#1A3020", "#3A6040"],
    colors: {
      primary: "#7EC86A",
      secondary: "#2A4A30",
      background: "#0C180E",
      cardBg: "#E8F4E0",
      border: "#162418",
      surface: "#1A3020",
      searchBg: "#1A3020",
      textMuted: "#5A8A60",
      textPrimary: "#E0F0D8",
      headerBg: "#081208",
      sectionBg: "#081208",
      buttonBg: "#7EC86A",
      buttonText: "#081208",
      footerBg: "#040C04",
      badgeBg: "#7EC86A",
      badgeText: "#081208",
      navBorder: "#162418",
      textSecondary: "#B0D4A8",
      textSubtle: "#7AA87A",
      textFooter: "#3A6040",
      borderLight: "#0E1E10",
      borderInput: "#243C28",
      borderMid: "#2E4A32",
      ratingBarBg: "#162418",
      ratingStar: "#7EC86A",
      paginationBg: "#1A3020",
      textSummerSale: "#7AA87A",
      textBreadcrumb: "#7AA87A",
      tabActive: "#7EC86A",
      categoryActiveBg: "#243E2A",
      categoryActiveText: "#7EC86A",
      specBadgeBg: "#0E1E10",
      reviewBg: "#0E1E10",
      popularBg0: "#2C4C30",
      popularBg1: "#223C28",
      popularBg2: "#182E1E",
      popularBg3: "#0E2014",
      popularText0: "#E0F0D8",
      popularText1: "#E0F0D8",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 10. ARENA MEDITERRANEO — Sandy Mediterranean warm (LIGHT)
  //    Warm sand, turquoise accents — coastal Mediterranean villa.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "arena-mediterraneo",
    name: "Arena Mediterráneo",
    description: "Arena cálida con toques de turquesa — villa mediterránea costera",
    style: "tropical",
    preview: ["#2A8A7A", "#FAF4EC", "#FFFFFF", "#F0E0C0", "#A08840"],
    colors: {
      primary: "#2A8A7A",
      secondary: "#4A7060",
      background: "#FAF4EC",
      cardBg: "#FFFFFF",
      border: "#EAD8B8",
      surface: "#F0E4CC",
      searchBg: "#F0E4CC",
      textMuted: "#8A7058",
      textPrimary: "#201808",
      headerBg: "#FFFFFF",
      sectionBg: "#FAF4EC",
      buttonBg: "#2A8A7A",
      buttonText: "#FFFFFF",
      footerBg: "#201808",
      badgeBg: "#2A8A7A",
      badgeText: "#FFFFFF",
      navBorder: "#EAD8B8",
      textSecondary: "#3A2C14",
      textSubtle: "#6A5840",
      textFooter: "#B8A080",
      borderLight: "#F0E0C8",
      borderInput: "#D8C0A0",
      borderMid: "#C8A880",
      ratingBarBg: "#EAD8B8",
      ratingStar: "#C08820",
      paginationBg: "#F0E4CC",
      textSummerSale: "#8A7058",
      textBreadcrumb: "#8A7058",
      tabActive: "#2A8A7A",
      categoryActiveBg: "#2A8A7A",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F0E4CC",
      reviewBg: "#FDF6EC",
      popularBg0: "#EEE0C4",
      popularBg1: "#E0CC9C",
      popularBg2: "#C8B07C",
      popularBg3: "#A89060",
      popularText0: "#201808",
      popularText1: "#201808",
      popularText2: "#201808",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 11. BURDEOS OPULENTO — Burgundy/wine rich (LIGHT)
  //    Deep burgundy with champagne — opulent dining room statement pieces.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "burdeos-opulento",
    name: "Burdeos Opulento",
    description: "Burdeos y champaña — piezas de comedor opulento y sala de lujo",
    style: "premium",
    preview: ["#8A1A2E", "#FAF6F8", "#FFFFFF", "#F8E8EC", "#D4A0A8"],
    colors: {
      primary: "#8A1A2E",
      secondary: "#6A0A1E",
      background: "#FAF6F8",
      cardBg: "#FFFFFF",
      border: "#EAD4D8",
      surface: "#F4E8EC",
      searchBg: "#F4E8EC",
      textMuted: "#9A7080",
      textPrimary: "#1E0810",
      headerBg: "#FFFFFF",
      sectionBg: "#FAF6F8",
      buttonBg: "#8A1A2E",
      buttonText: "#FFFFFF",
      footerBg: "#1E0810",
      badgeBg: "#8A1A2E",
      badgeText: "#FFFFFF",
      navBorder: "#EAD4D8",
      textSecondary: "#38101C",
      textSubtle: "#6A4050",
      textFooter: "#C0A0A8",
      borderLight: "#F4E0E4",
      borderInput: "#D8C0C4",
      borderMid: "#C8ACAC",
      ratingBarBg: "#EAD4D8",
      ratingStar: "#C04040",
      paginationBg: "#F4E8EC",
      textSummerSale: "#9A7080",
      textBreadcrumb: "#9A7080",
      tabActive: "#8A1A2E",
      categoryActiveBg: "#8A1A2E",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F4E8EC",
      reviewBg: "#FDF0F4",
      popularBg0: "#F0DCE0",
      popularBg1: "#E4C4CC",
      popularBg2: "#CCACB4",
      popularBg3: "#A88890",
      popularText0: "#1E0810",
      popularText1: "#1E0810",
      popularText2: "#1E0810",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 12. GRIS ESCANDINAVO — Light Scandinavian gray minimal (LIGHT)
  //    Cool white-gray, Nordic minimalism — clean Scandinavian interiors.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "gris-escandinavo",
    name: "Gris Escandinavo",
    description: "Blancos y grises nórdicos — minimalismo escandinavo limpio y funcional",
    style: "minimal",
    preview: ["#4A5A6A", "#F7F8F9", "#FFFFFF", "#E8EAF0", "#8A9AAA"],
    colors: {
      primary: "#4A5A6A",
      secondary: "#2A3A4A",
      background: "#F7F8F9",
      cardBg: "#FFFFFF",
      border: "#DDE0E8",
      surface: "#ECEEF4",
      searchBg: "#ECEEF4",
      textMuted: "#7A8A9A",
      textPrimary: "#18222A",
      headerBg: "#FFFFFF",
      sectionBg: "#F4F5F8",
      buttonBg: "#4A5A6A",
      buttonText: "#FFFFFF",
      footerBg: "#18222A",
      badgeBg: "#4A5A6A",
      badgeText: "#FFFFFF",
      navBorder: "#DDE0E8",
      textSecondary: "#2A3A4A",
      textSubtle: "#5A6A7A",
      textFooter: "#9AAAB8",
      borderLight: "#ECEEF4",
      borderInput: "#CDD0DA",
      borderMid: "#BDC0CC",
      ratingBarBg: "#DDE0E8",
      ratingStar: "#C09040",
      paginationBg: "#ECEEF4",
      textSummerSale: "#7A8A9A",
      textBreadcrumb: "#7A8A9A",
      tabActive: "#4A5A6A",
      categoryActiveBg: "#4A5A6A",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#ECEEF4",
      reviewBg: "#F4F5F8",
      popularBg0: "#E8EAF0",
      popularBg1: "#D8DCE6",
      popularBg2: "#C0C4D0",
      popularBg3: "#9CA2B0",
      popularText0: "#18222A",
      popularText1: "#18222A",
      popularText2: "#18222A",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 13. NEGRO ZEN — Matte black zen/Japanese (DARK)
  //    Pure obsidian black with ink-wash accents — Japanese wabi-sabi.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "negro-zen",
    name: "Negro Zen",
    description: "Negro obsidiana con toques wabi-sabi — sobriedad japonesa en muebles",
    style: "minimal",
    preview: ["#E8DCC8", "#0E0E0E", "#F0ECD8", "#2A2A28", "#6A6454"],
    colors: {
      primary: "#E8DCC8",
      secondary: "#3A3A38",
      background: "#0E0E0E",
      cardBg: "#F0ECD8",
      border: "#242420",
      surface: "#2A2A28",
      searchBg: "#2A2A28",
      textMuted: "#807A6A",
      textPrimary: "#F0ECD8",
      headerBg: "#0A0A0A",
      sectionBg: "#0A0A0A",
      buttonBg: "#E8DCC8",
      buttonText: "#0A0A0A",
      footerBg: "#060606",
      badgeBg: "#E8DCC8",
      badgeText: "#0A0A0A",
      navBorder: "#242420",
      textSecondary: "#C0B8A4",
      textSubtle: "#908870",
      textFooter: "#585048",
      borderLight: "#1C1C1A",
      borderInput: "#3A3A38",
      borderMid: "#404040",
      ratingBarBg: "#242420",
      ratingStar: "#C8A840",
      paginationBg: "#2A2A28",
      textSummerSale: "#908870",
      textBreadcrumb: "#908870",
      tabActive: "#E8DCC8",
      categoryActiveBg: "#3E3E3C",
      categoryActiveText: "#E8DCC8",
      specBadgeBg: "#1C1C1A",
      reviewBg: "#1C1C1A",
      popularBg0: "#343430",
      popularBg1: "#282824",
      popularBg2: "#1C1C1A",
      popularBg3: "#121210",
      popularText0: "#F0ECD8",
      popularText1: "#F0ECD8",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 14. COBRE ART DECO — Copper/bronze art deco (LIGHT)
  //    Warm copper on ivory — 1920s Art Deco glamour and opulence.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "cobre-art-deco",
    name: "Cobre Art Déco",
    description: "Cobre y bronce sobre marfil — glamour Art Déco de los años veinte",
    style: "premium",
    preview: ["#B8682A", "#FAF5EC", "#FFFFFF", "#F0E0C0", "#E0A850"],
    colors: {
      primary: "#B8682A",
      secondary: "#8A4818",
      background: "#FAF5EC",
      cardBg: "#FFFFFF",
      border: "#EEE0C4",
      surface: "#F4EAD4",
      searchBg: "#F4EAD4",
      textMuted: "#9A7850",
      textPrimary: "#1C0E04",
      headerBg: "#FFFFFF",
      sectionBg: "#FAF5EC",
      buttonBg: "#B8682A",
      buttonText: "#FFFFFF",
      footerBg: "#1C0E04",
      badgeBg: "#B8682A",
      badgeText: "#FFFFFF",
      navBorder: "#EEE0C4",
      textSecondary: "#3A200C",
      textSubtle: "#7A5830",
      textFooter: "#C0A060",
      borderLight: "#F0E4CC",
      borderInput: "#D8C0A0",
      borderMid: "#C8A87A",
      ratingBarBg: "#EEE0C4",
      ratingStar: "#D08820",
      paginationBg: "#F4EAD4",
      textSummerSale: "#9A7850",
      textBreadcrumb: "#9A7850",
      tabActive: "#B8682A",
      categoryActiveBg: "#B8682A",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F4EAD4",
      reviewBg: "#FDF7EE",
      popularBg0: "#EEE0C4",
      popularBg1: "#E2CCA4",
      popularBg2: "#C8A878",
      popularBg3: "#A88048",
      popularText0: "#1C0E04",
      popularText1: "#1C0E04",
      popularText2: "#1C0E04",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 15. LAVANDA SUAVE — Soft lavender, modern romantic (LIGHT)
  //    Misty lavender with rose gold — contemporary romantic interior design.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "lavanda-suave",
    name: "Lavanda Suave",
    description: "Lavanda suave con oro rosado — diseño interior romántico contemporáneo",
    style: "playful",
    preview: ["#8A5AA0", "#FAF6FC", "#FFFFFF", "#F0E4F8", "#C89ABE"],
    colors: {
      primary: "#8A5AA0",
      secondary: "#6A3A80",
      background: "#FAF6FC",
      cardBg: "#FFFFFF",
      border: "#E8D8F0",
      surface: "#F4E8FC",
      searchBg: "#F4E8FC",
      textMuted: "#907890",
      textPrimary: "#1E0A28",
      headerBg: "#FFFFFF",
      sectionBg: "#FAF6FC",
      buttonBg: "#8A5AA0",
      buttonText: "#FFFFFF",
      footerBg: "#1E0A28",
      badgeBg: "#8A5AA0",
      badgeText: "#FFFFFF",
      navBorder: "#E8D8F0",
      textSecondary: "#3A1848",
      textSubtle: "#6A4A78",
      textFooter: "#C0A0C8",
      borderLight: "#F0E0F8",
      borderInput: "#D8C0E8",
      borderMid: "#C8A8D8",
      ratingBarBg: "#E8D8F0",
      ratingStar: "#C070A0",
      paginationBg: "#F4E8FC",
      textSummerSale: "#907890",
      textBreadcrumb: "#907890",
      tabActive: "#8A5AA0",
      categoryActiveBg: "#8A5AA0",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F4E8FC",
      reviewBg: "#FBF3FE",
      popularBg0: "#EEE0F8",
      popularBg1: "#E0CCED",
      popularBg2: "#C8AEDD",
      popularBg3: "#A888C0",
      popularText0: "#1E0A28",
      popularText1: "#1E0A28",
      popularText2: "#1E0A28",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 16. MOSTAZA RETRO — Mustard yellow retro (LIGHT)
  //    Warm mustard + chocolate brown — 70s retro interior revival.
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "mostaza-retro",
    name: "Mostaza Retro",
    description: "Mostaza cálida y chocolate — revival del interiorismo retro de los 70",
    style: "vibrant",
    preview: ["#C8901A", "#FAF4E4", "#FFFFFF", "#F8E8B0", "#8A5A10"],
    colors: {
      primary: "#C8901A",
      secondary: "#8A5A10",
      background: "#FAF4E4",
      cardBg: "#FFFFFF",
      border: "#EEE0B0",
      surface: "#F4E8C0",
      searchBg: "#F4E8C0",
      textMuted: "#9A7A40",
      textPrimary: "#1E0E00",
      headerBg: "#FFFFFF",
      sectionBg: "#FAF4E4",
      buttonBg: "#C8901A",
      buttonText: "#FFFFFF",
      footerBg: "#1E0E00",
      badgeBg: "#C8901A",
      badgeText: "#FFFFFF",
      navBorder: "#EEE0B0",
      textSecondary: "#3A2400",
      textSubtle: "#7A5820",
      textFooter: "#C0A050",
      borderLight: "#F4E8CC",
      borderInput: "#D8C090",
      borderMid: "#C8A870",
      ratingBarBg: "#EEE0B0",
      ratingStar: "#E07818",
      paginationBg: "#F4E8C0",
      textSummerSale: "#9A7A40",
      textBreadcrumb: "#9A7A40",
      tabActive: "#C8901A",
      categoryActiveBg: "#C8901A",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F4E8C0",
      reviewBg: "#FDF8E8",
      popularBg0: "#F0E4A8",
      popularBg1: "#E4D088",
      popularBg2: "#CCB060",
      popularBg3: "#A88830",
      popularText0: "#1E0E00",
      popularText1: "#1E0E00",
      popularText2: "#1E0E00",
      popularText3: "#FFFFFF",
    },
  },
];
