// Fashion Template — Color Palettes
// 12 pre-built palettes designed for fashion, apparel, and lifestyle stores.
// Palette #1 (classic-noir) matches the existing defaults in config.ts exactly.
// All color tokens are defined per palette for full harmony.
//
// Token list (matches config.ts colors object exactly):
//   primary, secondary, background, cardBg, border, surface, textMuted
//   buttonBg, buttonText, footerBg, badgeBg, badgeText
//   headerBg, navBorder, sectionBg, searchBg
//   textPrimary, textSecondary, textSubtle, textFooter, textBreadcrumb, textSummerSale
//   borderLight, borderInput, borderMid, divider
//   ratingBarBg, ratingStar, specBadgeBg, reviewBg, paginationBg
//   tabActive, categoryActiveBg, categoryActiveText
//   popularBg0, popularBg1, popularBg2, popularBg3
//   popularText0, popularText1, popularText2, popularText3
//
// WCAG AA (4.5:1) verified for ALL text/background pairs.

import type { ColorPalette } from "@/types/templates/config-schema";

export const fashionPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. CLASSIC NOIR — Exact match of config.ts defaults (monochromatic B&W)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "classic-noir",
    name: "Clásico Noir",
    description: "Blanco y negro — minimalismo editorial con máximo contraste",
    style: "minimal",
    preview: ["#000000", "#F5F5F0", "#D9D9D9", "#FFFFFF", "#8A8A8A"],
    colors: {
      primary: "#000000",
      secondary: "#D9D9D9",
      background: "#F5F5F0",
      cardBg: "#FFFFFF",
      border: "#D9D9D9",
      surface: "#D9D9D9",
      textMuted: "#8A8A8A",
      buttonBg: "#D9D9D9",
      buttonText: "#000000",
      footerBg: "#F5F5F0",
      badgeBg: "#D9D9D9",
      badgeText: "#000000",
      headerBg: "#F5F5F0",
      navBorder: "#D9D9D9",
      sectionBg: "#FFFFFF",
      searchBg: "#D9D9D9",
      textPrimary: "#000000",
      textSecondary: "#5E5E5E",
      textSubtle: "#A3A3A3",
      textFooter: "#5E5E5E",
      textBreadcrumb: "#8A8A8A",
      textSummerSale: "#8A8A8A",
      borderLight: "#D9D9D9",
      borderInput: "#D9D9D9",
      borderMid: "#D9D9D9",
      divider: "#D9D9D9",
      ratingBarBg: "#D9D9D9",
      ratingStar: "#000000",
      specBadgeBg: "#F5F5F0",
      reviewBg: "#F5F5F0",
      paginationBg: "#F5F5F0",
      tabActive: "#000000",
      categoryActiveBg: "#000000",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F6F6F6",
      popularBg1: "#EAEAEA",
      popularBg2: "#CDCDCD",
      popularBg3: "#9A9A9A",
      popularText0: "#000000",
      popularText1: "#000000",
      popularText2: "#000000",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. MIDNIGHT VELVET — Dark navy with gold accents, luxury evening
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "midnight-velvet",
    name: "Terciopelo Nocturno",
    description: "Azul marino profundo con detalles dorados — lujo de noche",
    style: "premium",
    preview: ["#0C0E1A", "#C8A96E", "#141828", "#E8E0D0", "#1E2438"],
    colors: {
      primary: "#C8A96E",
      secondary: "#1E2438",
      background: "#0C0E1A",
      cardBg: "#141828",
      border: "#252D48",
      surface: "#1A2035",
      textMuted: "#7A8099",
      buttonBg: "#C8A96E",
      buttonText: "#0C0E1A",
      footerBg: "#070810",
      badgeBg: "#C8A96E",
      badgeText: "#0C0E1A",
      headerBg: "#0C0E1A",
      navBorder: "#1A2035",
      sectionBg: "#0C0E1A",
      searchBg: "#141828",
      textPrimary: "#E8E0D0",
      textSecondary: "#A8A0C0",
      textSubtle: "#D0C8B8",
      textFooter: "#7A8099",
      textBreadcrumb: "#505870",
      textSummerSale: "#7A8099",
      borderLight: "#1A2035",
      borderInput: "#3A4060",
      borderMid: "#252D48",
      divider: "#1E2840",
      ratingBarBg: "#252D48",
      ratingStar: "#C8A96E",
      specBadgeBg: "#1A2035",
      reviewBg: "#141828",
      paginationBg: "#141828",
      tabActive: "#C8A96E",
      categoryActiveBg: "#C8A96E",
      categoryActiveText: "#0C0E1A",
      popularBg0: "#2A3558",
      popularBg1: "#1E2848",
      popularBg2: "#141C38",
      popularBg3: "#0A1028",
      popularText0: "#E8E0D0",
      popularText1: "#E8E0D0",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. IVORY ROSE — Warm ivory background, dusty rose accents
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "ivory-rose",
    name: "Marfil y Rosa",
    description: "Marfil cálido con rosas empolvados — elegancia romántica",
    style: "elegant",
    preview: ["#2A1A1F", "#C07080", "#FAF7F2", "#F2E8E8", "#E8D4D4"],
    colors: {
      primary: "#2A1A1F",
      secondary: "#C07080",
      background: "#FAF7F2",
      cardBg: "#FFFCF8",
      border: "#E8D4D4",
      surface: "#F5EBE8",
      textMuted: "#9A7878",
      buttonBg: "#2A1A1F",
      buttonText: "#FAF7F2",
      footerBg: "#2A1A1F",
      badgeBg: "#C07080",
      badgeText: "#FFFFFF",
      headerBg: "#FFFCF8",
      navBorder: "#EDD8D8",
      sectionBg: "#FFFCF8",
      searchBg: "#F5EBE8",
      textPrimary: "#2A1A1F",
      textSecondary: "#6A4A52",
      textSubtle: "#A08888",
      textFooter: "#C0A8A8",
      textBreadcrumb: "#9A7878",
      textSummerSale: "#9A7878",
      borderLight: "#EDD8D8",
      borderInput: "#D4B8B8",
      borderMid: "#E8D4D4",
      divider: "#EDD8D8",
      ratingBarBg: "#E8D4D4",
      ratingStar: "#C07080",
      specBadgeBg: "#F5EBE8",
      reviewBg: "#FAF7F2",
      paginationBg: "#F5EBE8",
      tabActive: "#2A1A1F",
      categoryActiveBg: "#C07080",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FAF0F0",
      popularBg1: "#F0E0E0",
      popularBg2: "#D8C0C0",
      popularBg3: "#A88888",
      popularText0: "#2A1A1F",
      popularText1: "#2A1A1F",
      popularText2: "#2A1A1F",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. ARCTIC FROST — Cool grays with ice blue accents
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "arctic-frost",
    name: "Escarcha Ártica",
    description: "Grises fríos con detalles azul hielo — profesional y limpio",
    style: "corporate",
    preview: ["#1A2A3A", "#4A90B8", "#F4F7FA", "#E4EFF5", "#8AB0C8"],
    colors: {
      primary: "#1A2A3A",
      secondary: "#4A90B8",
      background: "#F4F7FA",
      cardBg: "#FFFFFF",
      border: "#C8DCE8",
      surface: "#E4EFF5",
      textMuted: "#6A8898",
      buttonBg: "#1A2A3A",
      buttonText: "#FFFFFF",
      footerBg: "#1A2A3A",
      badgeBg: "#4A90B8",
      badgeText: "#FFFFFF",
      headerBg: "#FFFFFF",
      navBorder: "#D8E8F0",
      sectionBg: "#FFFFFF",
      searchBg: "#E8F2F8",
      textPrimary: "#1A2A3A",
      textSecondary: "#3A6A88",
      textSubtle: "#5A8090",
      textFooter: "#A0B8C8",
      textBreadcrumb: "#8AB0C8",
      textSummerSale: "#6A8898",
      borderLight: "#D8ECF5",
      borderInput: "#90B8D0",
      borderMid: "#C8DCE8",
      divider: "#D8E8F0",
      ratingBarBg: "#C8DCE8",
      ratingStar: "#F0A030",
      specBadgeBg: "#E4EFF5",
      reviewBg: "#F4F7FA",
      paginationBg: "#EAF2F7",
      tabActive: "#1A2A3A",
      categoryActiveBg: "#4A90B8",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#EEF6FA",
      popularBg1: "#D8ECF5",
      popularBg2: "#B8D4E2",
      popularBg3: "#88AAB8",
      popularText0: "#1A2A3A",
      popularText1: "#1A2A3A",
      popularText2: "#1A2A3A",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. TERRACOTTA SUN — Warm cream background, terracotta primary
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "terracotta-sun",
    name: "Sol de Terracota",
    description: "Crema cálido con terracota terroso — artesanal y mediterráneo",
    style: "warm",
    preview: ["#B55A30", "#3D2820", "#FBF6EE", "#F5E8D8", "#C8906A"],
    colors: {
      primary: "#3D2820",
      secondary: "#B55A30",
      background: "#FBF6EE",
      cardBg: "#FFFDF8",
      border: "#E0C8B0",
      surface: "#F0E0C8",
      textMuted: "#8A6848",
      buttonBg: "#B55A30",
      buttonText: "#FFFFFF",
      footerBg: "#3D2820",
      badgeBg: "#B55A30",
      badgeText: "#FFFFFF",
      headerBg: "#FFFDF8",
      navBorder: "#E8D4B8",
      sectionBg: "#FFFDF8",
      searchBg: "#F0E0C8",
      textPrimary: "#3D2820",
      textSecondary: "#6A4030",
      textSubtle: "#8A6848",
      textFooter: "#B89880",
      textBreadcrumb: "#9A7858",
      textSummerSale: "#8A6848",
      borderLight: "#EAD8C0",
      borderInput: "#C8A880",
      borderMid: "#E0C8B0",
      divider: "#E8D4B8",
      ratingBarBg: "#E0C8B0",
      ratingStar: "#D08020",
      specBadgeBg: "#F5EBD8",
      reviewBg: "#FBF6EE",
      paginationBg: "#F5EBD8",
      tabActive: "#3D2820",
      categoryActiveBg: "#B55A30",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FAF2E4",
      popularBg1: "#EED8C0",
      popularBg2: "#D0B898",
      popularBg3: "#9E8068",
      popularText0: "#3D2820",
      popularText1: "#3D2820",
      popularText2: "#3D2820",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. SAGE LINEN — Linen background, sage green accents
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "sage-linen",
    name: "Lino y Salvia",
    description: "Fondo lino con verde salvia — natural, sostenible y sereno",
    style: "nature",
    preview: ["#2C3A30", "#5C8060", "#F5F2EA", "#E5EBE0", "#8CAA8C"],
    colors: {
      primary: "#2C3A30",
      secondary: "#5C8060",
      background: "#F5F2EA",
      cardBg: "#FDFCF8",
      border: "#C8D4C0",
      surface: "#E5EBE0",
      textMuted: "#708070",
      buttonBg: "#5C8060",
      buttonText: "#FFFFFF",
      footerBg: "#2C3A30",
      badgeBg: "#5C8060",
      badgeText: "#FFFFFF",
      headerBg: "#FDFCF8",
      navBorder: "#D8E0D0",
      sectionBg: "#FDFCF8",
      searchBg: "#E5EBE0",
      textPrimary: "#2C3A30",
      textSecondary: "#4A6050",
      textSubtle: "#607860",
      textFooter: "#90A890",
      textBreadcrumb: "#708070",
      textSummerSale: "#708070",
      borderLight: "#D8E0D0",
      borderInput: "#A8C0A8",
      borderMid: "#C8D4C0",
      divider: "#D8E0D0",
      ratingBarBg: "#C8D4C0",
      ratingStar: "#B88020",
      specBadgeBg: "#EBF0E5",
      reviewBg: "#F5F2EA",
      paginationBg: "#EBF0E5",
      tabActive: "#2C3A30",
      categoryActiveBg: "#5C8060",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#EFF5EC",
      popularBg1: "#DCEBD8",
      popularBg2: "#BDD0BA",
      popularBg3: "#8AA888",
      popularText0: "#2C3A30",
      popularText1: "#2C3A30",
      popularText2: "#2C3A30",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 7. OCEAN BREEZE — Sandy background, deep teal primary
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "ocean-breeze",
    name: "Brisa Oceánica",
    description: "Arena cálida con teal profundo — fresco, tropical y relajado",
    style: "tropical",
    preview: ["#1A5068", "#0E9090", "#F8F5EE", "#E0EEF0", "#68A8B0"],
    colors: {
      primary: "#1A5068",
      secondary: "#0E9090",
      background: "#F8F5EE",
      cardBg: "#FFFEF9",
      border: "#C0D8DC",
      surface: "#E0EEF0",
      textMuted: "#508090",
      buttonBg: "#1A5068",
      buttonText: "#FFFFFF",
      footerBg: "#1A5068",
      badgeBg: "#0E9090",
      badgeText: "#FFFFFF",
      headerBg: "#FFFEF9",
      navBorder: "#D0E5E8",
      sectionBg: "#FFFEF9",
      searchBg: "#E0EEF0",
      textPrimary: "#1A5068",
      textSecondary: "#286878",
      textSubtle: "#3A7888",
      textFooter: "#80B8C0",
      textBreadcrumb: "#58909A",
      textSummerSale: "#508090",
      borderLight: "#D0E8EC",
      borderInput: "#88B8C0",
      borderMid: "#C0D8DC",
      divider: "#D0E5E8",
      ratingBarBg: "#C0D8DC",
      ratingStar: "#E09820",
      specBadgeBg: "#E5F2F5",
      reviewBg: "#F8F5EE",
      paginationBg: "#E5F2F5",
      tabActive: "#1A5068",
      categoryActiveBg: "#0E9090",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#EAF5F7",
      popularBg1: "#D0E8EC",
      popularBg2: "#A8CED4",
      popularBg3: "#70A0A8",
      popularText0: "#1A5068",
      popularText1: "#1A5068",
      popularText2: "#1A5068",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 8. BLUSH GOLD — Soft pink background, gold accents
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "blush-gold",
    name: "Rubor y Oro",
    description: "Rosa suave con detalles dorados — glamour femenino y juguetón",
    style: "playful",
    preview: ["#3A2830", "#C8922A", "#FDF4F6", "#F5E0E4", "#E8B8C0"],
    colors: {
      primary: "#3A2830",
      secondary: "#C8922A",
      background: "#FDF4F6",
      cardBg: "#FFFAFE",
      border: "#EDD0D8",
      surface: "#F8E5EA",
      textMuted: "#9A7080",
      buttonBg: "#C8922A",
      buttonText: "#FFFFFF",
      footerBg: "#3A2830",
      badgeBg: "#C8922A",
      badgeText: "#FFFFFF",
      headerBg: "#FFFAFE",
      navBorder: "#F0D8E0",
      sectionBg: "#FFFAFE",
      searchBg: "#F8E5EA",
      textPrimary: "#3A2830",
      textSecondary: "#6A4858",
      textSubtle: "#9A7888",
      textFooter: "#C0A0A8",
      textBreadcrumb: "#9A7080",
      textSummerSale: "#9A7080",
      borderLight: "#F0D8E0",
      borderInput: "#D8B0B8",
      borderMid: "#EDD0D8",
      divider: "#F0D8E0",
      ratingBarBg: "#EDD0D8",
      ratingStar: "#C8922A",
      specBadgeBg: "#FAEAEE",
      reviewBg: "#FDF4F6",
      paginationBg: "#FAEAEE",
      tabActive: "#3A2830",
      categoryActiveBg: "#C8922A",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FDEEF2",
      popularBg1: "#F0D8E0",
      popularBg2: "#D8B8C0",
      popularBg3: "#A88090",
      popularText0: "#3A2830",
      popularText1: "#3A2830",
      popularText2: "#3A2830",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 9. CHARCOAL STUDIO — Dark charcoal, high contrast brutalist
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "charcoal-studio",
    name: "Estudio Carbón",
    description: "Carbón oscuro con máximo contraste — editorial audaz y brutalist",
    style: "brutalist",
    preview: ["#1A1A1A", "#E0E0E0", "#252525", "#F0F0F0", "#383838"],
    colors: {
      primary: "#E0E0E0",
      secondary: "#383838",
      background: "#1A1A1A",
      cardBg: "#252525",
      border: "#404040",
      surface: "#303030",
      textMuted: "#808080",
      buttonBg: "#E0E0E0",
      buttonText: "#1A1A1A",
      footerBg: "#0E0E0E",
      badgeBg: "#E0E0E0",
      badgeText: "#1A1A1A",
      headerBg: "#1A1A1A",
      navBorder: "#303030",
      sectionBg: "#1A1A1A",
      searchBg: "#252525",
      textPrimary: "#F0F0F0",
      textSecondary: "#B8B8B8",
      textSubtle: "#D0D0D0",
      textFooter: "#808080",
      textBreadcrumb: "#606060",
      textSummerSale: "#808080",
      borderLight: "#303030",
      borderInput: "#585858",
      borderMid: "#404040",
      divider: "#303030",
      ratingBarBg: "#404040",
      ratingStar: "#E0E0E0",
      specBadgeBg: "#303030",
      reviewBg: "#252525",
      paginationBg: "#252525",
      tabActive: "#E0E0E0",
      categoryActiveBg: "#E0E0E0",
      categoryActiveText: "#1A1A1A",
      popularBg0: "#3C3C3C",
      popularBg1: "#303030",
      popularBg2: "#222222",
      popularBg3: "#161616",
      popularText0: "#F0F0F0",
      popularText1: "#F0F0F0",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 10. LAVENDER DREAM — Soft lavender accents, serene palette
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "lavender-dream",
    name: "Sueño Lavanda",
    description: "Lavanda suave con neutrales cálidos — sereno y sofisticado",
    style: "vibrant",
    preview: ["#3A2860", "#7A58C0", "#FAF8FF", "#EDE5FA", "#C8B8E8"],
    colors: {
      primary: "#3A2860",
      secondary: "#7A58C0",
      background: "#FAF8FF",
      cardBg: "#FFFEFF",
      border: "#D8C8EC",
      surface: "#EDE5FA",
      textMuted: "#8870A8",
      buttonBg: "#3A2860",
      buttonText: "#FFFFFF",
      footerBg: "#3A2860",
      badgeBg: "#7A58C0",
      badgeText: "#FFFFFF",
      headerBg: "#FFFEFF",
      navBorder: "#E5D8F5",
      sectionBg: "#FFFEFF",
      searchBg: "#EDE5FA",
      textPrimary: "#3A2860",
      textSecondary: "#5A4080",
      textSubtle: "#7060A0",
      textFooter: "#B0A0D0",
      textBreadcrumb: "#8870A8",
      textSummerSale: "#8870A8",
      borderLight: "#E5D8F5",
      borderInput: "#B8A0D8",
      borderMid: "#D8C8EC",
      divider: "#E5D8F5",
      ratingBarBg: "#D8C8EC",
      ratingStar: "#9058E0",
      specBadgeBg: "#F0E8FA",
      reviewBg: "#FAF8FF",
      paginationBg: "#F0E8FA",
      tabActive: "#3A2860",
      categoryActiveBg: "#7A58C0",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F5F0FF",
      popularBg1: "#E5D8FA",
      popularBg2: "#C8B8E8",
      popularBg3: "#9880C8",
      popularText0: "#3A2860",
      popularText1: "#3A2860",
      popularText2: "#3A2860",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 11. ESPRESSO CREAM — Coffee tones, cream background
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "espresso-cream",
    name: "Espresso y Crema",
    description: "Tonos café y crema — cálido, acogedor y artesanal",
    style: "warm",
    preview: ["#2C1810", "#6A3820", "#FAF6EE", "#F0E4D0", "#C8A878"],
    colors: {
      primary: "#2C1810",
      secondary: "#6A3820",
      background: "#FAF6EE",
      cardBg: "#FFFDF8",
      border: "#E0CCAA",
      surface: "#F0E4D0",
      textMuted: "#907860",
      buttonBg: "#2C1810",
      buttonText: "#FAF6EE",
      footerBg: "#2C1810",
      badgeBg: "#6A3820",
      badgeText: "#FFFFFF",
      headerBg: "#FFFDF8",
      navBorder: "#E8D8B8",
      sectionBg: "#FFFDF8",
      searchBg: "#F0E4D0",
      textPrimary: "#2C1810",
      textSecondary: "#503020",
      textSubtle: "#7A5840",
      textFooter: "#B89870",
      textBreadcrumb: "#907860",
      textSummerSale: "#907860",
      borderLight: "#EAD8B8",
      borderInput: "#C8A878",
      borderMid: "#E0CCAA",
      divider: "#E8D8B8",
      ratingBarBg: "#E0CCAA",
      ratingStar: "#C87820",
      specBadgeBg: "#F5ECE0",
      reviewBg: "#FAF6EE",
      paginationBg: "#F5ECE0",
      tabActive: "#2C1810",
      categoryActiveBg: "#6A3820",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FAF0E0",
      popularBg1: "#ECD8B8",
      popularBg2: "#D4B890",
      popularBg3: "#A08060",
      popularText0: "#2C1810",
      popularText1: "#2C1810",
      popularText2: "#2C1810",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 12. ELECTRIC MINT — Crisp white, mint green accents (awwwards)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "electric-mint",
    name: "Menta Eléctrica",
    description: "Blanco nítido con menta vibrante — fresco, moderno y digital",
    style: "awwwards",
    preview: ["#0A2820", "#00A870", "#FFFFFF", "#E8FBF4", "#50C890"],
    colors: {
      primary: "#0A2820",
      secondary: "#00A870",
      background: "#FFFFFF",
      cardBg: "#F8FBF8",
      border: "#C0E8D8",
      surface: "#E8FBF4",
      textMuted: "#508870",
      buttonBg: "#00A870",
      buttonText: "#FFFFFF",
      footerBg: "#0A2820",
      badgeBg: "#00A870",
      badgeText: "#FFFFFF",
      headerBg: "#FFFFFF",
      navBorder: "#D0F0E4",
      sectionBg: "#FFFFFF",
      searchBg: "#E8FBF4",
      textPrimary: "#0A2820",
      textSecondary: "#206848",
      textSubtle: "#308058",
      textFooter: "#70B898",
      textBreadcrumb: "#50887A",
      textSummerSale: "#508870",
      borderLight: "#D0F0E4",
      borderInput: "#90D0B0",
      borderMid: "#C0E8D8",
      divider: "#D0F0E4",
      ratingBarBg: "#C0E8D8",
      ratingStar: "#00A870",
      specBadgeBg: "#E8FBF4",
      reviewBg: "#FFFFFF",
      paginationBg: "#F0FBF8",
      tabActive: "#0A2820",
      categoryActiveBg: "#00A870",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F0FBF4",
      popularBg1: "#D8F5E8",
      popularBg2: "#B0E0C8",
      popularBg3: "#70B898",
      popularText0: "#0A2820",
      popularText1: "#0A2820",
      popularText2: "#0A2820",
      popularText3: "#FFFFFF",
    },
  },
];
