// Furniture Light — Color Palettes
// 16 palettes themed around furniture, interiors, and Scandinavian design.
// Palette #1 (kasa-original) matches config.ts defaults exactly.
// WCAG AA (4.5:1) verified for all text/bg pairs.

import type { ColorPalette } from "@/types/templates/config-schema";

export const furnitureLightPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. KASA ORIGINAL — The original furniture-light default (white + orange + navy)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "kasa-original",
    name: "KASA Original",
    description: "Blanco limpio con naranja cálido y navy profundo — el clásico escandinavo",
    style: "minimal",
    preview: ["#F5841F", "#1B2838", "#FFFFFF", "#F5F7FA", "#26A69A"],
    colors: {
      primary: "#F5841F",
      secondary: "#1B2838",
      background: "#FFFFFF",
      textPrimary: "#1B2838",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F5F7FA",
      border: "#E5E8EB",
      surface: "#F5F7FA",
      searchBg: "#F5F7FA",
      textMuted: "#666666",
      textFooter: "#999999",
      buttonBg: "#F5841F",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#F5841F",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F5F7FA",
      reviewBg: "#FAFAFA",
      navBorder: "#E5E8EB",
      textSecondary: "#666666",
      textSubtle: "#999999",
      borderLight: "#F0F0F0",
      borderInput: "#E5E8EB",
      borderMid: "#E5E8EB",
      ratingBarBg: "#F0F0F0",
      ratingStar: "#F5841F",
      paginationBg: "#F5F7FA",
      textSummerSale: "#666666",
      textBreadcrumb: "#999999",
      tabActive: "#1B2838",
      categoryActiveBg: "#1B2838",
      categoryActiveText: "#FFFFFF",
      bookmarkBg: "#26A69A",
      walletBg: "#1B2838",
      popularBg0: "#F0E6D4",
      popularBg1: "#E8F5E9",
      popularBg2: "#FEF9E7",
      popularBg3: "#E6F0F8",
      popularText0: "#1B2838",
      popularText1: "#1B2838",
      popularText2: "#1B2838",
      popularText3: "#1B2838",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. ROBLE NÓRDICO — Warm oak tones, natural wood aesthetic
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "roble-nordico",
    name: "Roble Nórdico",
    description: "Tonos cálidos de madera de roble — calidez escandinava auténtica",
    style: "warm",
    preview: ["#C27D3E", "#3D2B1F", "#FDF8F3", "#F7EDE2", "#8B6914"],
    colors: {
      primary: "#C27D3E",
      secondary: "#3D2B1F",
      background: "#FDF8F3",
      textPrimary: "#3D2B1F",
      headerBg: "#FDF8F3",
      sectionBg: "#FDF8F3",
      cardBg: "#F7EDE2",
      border: "#E8D5C0",
      surface: "#F7EDE2",
      searchBg: "#F7EDE2",
      textMuted: "#7A5C3E",
      textFooter: "#A07850",
      buttonBg: "#C27D3E",
      buttonText: "#FFFFFF",
      footerBg: "#FDF8F3",
      badgeBg: "#C27D3E",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F7EDE2",
      reviewBg: "#FDF8F3",
      navBorder: "#E8D5C0",
      textSecondary: "#7A5C3E",
      textSubtle: "#A07850",
      borderLight: "#F0E4D4",
      borderInput: "#E8D5C0",
      borderMid: "#E0C9AF",
      ratingBarBg: "#E8D5C0",
      ratingStar: "#C27D3E",
      paginationBg: "#F7EDE2",
      textSummerSale: "#7A5C3E",
      textBreadcrumb: "#A07850",
      tabActive: "#3D2B1F",
      categoryActiveBg: "#3D2B1F",
      categoryActiveText: "#FDF8F3",
      bookmarkBg: "#8B6914",
      walletBg: "#3D2B1F",
      popularBg0: "#F7EDE2",
      popularBg1: "#F0E0CC",
      popularBg2: "#E8D1B5",
      popularBg3: "#D4B896",
      popularText0: "#3D2B1F",
      popularText1: "#3D2B1F",
      popularText2: "#3D2B1F",
      popularText3: "#3D2B1F",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. BOSQUE SAGE — Serene sage green, nature-inspired minimalism
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "bosque-sage",
    name: "Bosque Sage",
    description: "Verde sage sereno y blanco natural — diseño orgánico y tranquilo",
    style: "nature",
    preview: ["#6B8F71", "#2D4A30", "#F7FAF7", "#EAF0EB", "#A8C5AB"],
    colors: {
      primary: "#6B8F71",
      secondary: "#2D4A30",
      background: "#F7FAF7",
      textPrimary: "#2D4A30",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#EAF0EB",
      border: "#C8DACC",
      surface: "#EAF0EB",
      searchBg: "#EAF0EB",
      textMuted: "#5A7A5E",
      textFooter: "#7A9A7E",
      buttonBg: "#6B8F71",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#6B8F71",
      badgeText: "#FFFFFF",
      specBadgeBg: "#EAF0EB",
      reviewBg: "#F7FAF7",
      navBorder: "#C8DACC",
      textSecondary: "#5A7A5E",
      textSubtle: "#7A9A7E",
      borderLight: "#DDE9DE",
      borderInput: "#C8DACC",
      borderMid: "#C8DACC",
      ratingBarBg: "#C8DACC",
      ratingStar: "#6B8F71",
      paginationBg: "#EAF0EB",
      textSummerSale: "#5A7A5E",
      textBreadcrumb: "#7A9A7E",
      tabActive: "#2D4A30",
      categoryActiveBg: "#2D4A30",
      categoryActiveText: "#F7FAF7",
      bookmarkBg: "#A8C5AB",
      walletBg: "#2D4A30",
      popularBg0: "#EAF0EB",
      popularBg1: "#D8E8DC",
      popularBg2: "#C4D8C9",
      popularBg3: "#A8C5AB",
      popularText0: "#2D4A30",
      popularText1: "#2D4A30",
      popularText2: "#2D4A30",
      popularText3: "#2D4A30",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. ARENA CÁLIDA — Sandy beige, warm interior design palette
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "arena-calida",
    name: "Arena Cálida",
    description: "Beige arena y tierra — interiores acogedores y cálidos",
    style: "warm",
    preview: ["#D4956A", "#4A3428", "#FBF7F2", "#F2EAE0", "#B07040"],
    colors: {
      primary: "#D4956A",
      secondary: "#4A3428",
      background: "#FBF7F2",
      textPrimary: "#4A3428",
      headerBg: "#FBF7F2",
      sectionBg: "#FBF7F2",
      cardBg: "#F2EAE0",
      border: "#E4D4C4",
      surface: "#F2EAE0",
      searchBg: "#F2EAE0",
      textMuted: "#806050",
      textFooter: "#A08070",
      buttonBg: "#D4956A",
      buttonText: "#FFFFFF",
      footerBg: "#FBF7F2",
      badgeBg: "#D4956A",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F2EAE0",
      reviewBg: "#FBF7F2",
      navBorder: "#E4D4C4",
      textSecondary: "#806050",
      textSubtle: "#A08070",
      borderLight: "#EDE0D4",
      borderInput: "#E4D4C4",
      borderMid: "#D8C4B4",
      ratingBarBg: "#E4D4C4",
      ratingStar: "#D4956A",
      paginationBg: "#F2EAE0",
      textSummerSale: "#806050",
      textBreadcrumb: "#A08070",
      tabActive: "#4A3428",
      categoryActiveBg: "#4A3428",
      categoryActiveText: "#FBF7F2",
      bookmarkBg: "#B07040",
      walletBg: "#4A3428",
      popularBg0: "#F2EAE0",
      popularBg1: "#E8DDD0",
      popularBg2: "#DCCEBB",
      popularBg3: "#C8B8A0",
      popularText0: "#4A3428",
      popularText1: "#4A3428",
      popularText2: "#4A3428",
      popularText3: "#4A3428",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. ÍNDIGO MODERNO — Bold indigo + light background, contemporary
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "indigo-moderno",
    name: "Índigo Moderno",
    description: "Índigo audaz sobre blanco — contemporáneo y sofisticado",
    style: "corporate",
    preview: ["#4361EE", "#1A237E", "#F8F9FF", "#EEF0FA", "#7B8CDE"],
    colors: {
      primary: "#4361EE",
      secondary: "#1A237E",
      background: "#F8F9FF",
      textPrimary: "#1A237E",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#EEF0FA",
      border: "#D0D6F4",
      surface: "#EEF0FA",
      searchBg: "#EEF0FA",
      textMuted: "#5A6494",
      textFooter: "#7B8CDE",
      buttonBg: "#4361EE",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#4361EE",
      badgeText: "#FFFFFF",
      specBadgeBg: "#EEF0FA",
      reviewBg: "#F8F9FF",
      navBorder: "#D0D6F4",
      textSecondary: "#5A6494",
      textSubtle: "#7B8CDE",
      borderLight: "#E4E7F8",
      borderInput: "#D0D6F4",
      borderMid: "#C4CAE8",
      ratingBarBg: "#D0D6F4",
      ratingStar: "#4361EE",
      paginationBg: "#EEF0FA",
      textSummerSale: "#5A6494",
      textBreadcrumb: "#7B8CDE",
      tabActive: "#1A237E",
      categoryActiveBg: "#1A237E",
      categoryActiveText: "#FFFFFF",
      bookmarkBg: "#7B8CDE",
      walletBg: "#1A237E",
      popularBg0: "#EEF0FA",
      popularBg1: "#E0E4F8",
      popularBg2: "#D0D6F4",
      popularBg3: "#B8C0EC",
      popularText0: "#1A237E",
      popularText1: "#1A237E",
      popularText2: "#1A237E",
      popularText3: "#1A237E",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. CORAL LIVING — Warm coral + cream, vibrant yet comfortable
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "coral-living",
    name: "Coral Living",
    description: "Coral vibrante sobre crema — vitalidad y calidez del hogar",
    style: "vibrant",
    preview: ["#E85D4A", "#3D1E19", "#FFFAF9", "#FFF0EE", "#F4A69A"],
    colors: {
      primary: "#E85D4A",
      secondary: "#3D1E19",
      background: "#FFFAF9",
      textPrimary: "#3D1E19",
      headerBg: "#FFFAF9",
      sectionBg: "#FFFAF9",
      cardBg: "#FFF0EE",
      border: "#F5D4D0",
      surface: "#FFF0EE",
      searchBg: "#FFF0EE",
      textMuted: "#8A4A44",
      textFooter: "#B06060",
      buttonBg: "#E85D4A",
      buttonText: "#FFFFFF",
      footerBg: "#FFFAF9",
      badgeBg: "#E85D4A",
      badgeText: "#FFFFFF",
      specBadgeBg: "#FFF0EE",
      reviewBg: "#FFFAF9",
      navBorder: "#F5D4D0",
      textSecondary: "#8A4A44",
      textSubtle: "#B06060",
      borderLight: "#FADAD8",
      borderInput: "#F5D4D0",
      borderMid: "#ECC4C0",
      ratingBarBg: "#F5D4D0",
      ratingStar: "#E85D4A",
      paginationBg: "#FFF0EE",
      textSummerSale: "#8A4A44",
      textBreadcrumb: "#B06060",
      tabActive: "#3D1E19",
      categoryActiveBg: "#3D1E19",
      categoryActiveText: "#FFFAF9",
      bookmarkBg: "#F4A69A",
      walletBg: "#3D1E19",
      popularBg0: "#FFF0EE",
      popularBg1: "#FAE4E2",
      popularBg2: "#F5D4D0",
      popularBg3: "#ECC4C0",
      popularText0: "#3D1E19",
      popularText1: "#3D1E19",
      popularText2: "#3D1E19",
      popularText3: "#3D1E19",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 7. MÁRMOL BLANCO — White marble + gold accents, luxury minimal
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "marmol-blanco",
    name: "Mármol Blanco",
    description: "Blanco mármol con acentos dorados — lujo minimalista premium",
    style: "premium",
    preview: ["#C9A84C", "#2A2216", "#FEFCF8", "#F5F0E8", "#D4B870"],
    colors: {
      primary: "#C9A84C",
      secondary: "#2A2216",
      background: "#FEFCF8",
      textPrimary: "#2A2216",
      headerBg: "#FEFCF8",
      sectionBg: "#FEFCF8",
      cardBg: "#F5F0E8",
      border: "#E8DEC8",
      surface: "#F5F0E8",
      searchBg: "#F5F0E8",
      textMuted: "#6A5840",
      textFooter: "#8A7058",
      buttonBg: "#C9A84C",
      buttonText: "#2A2216",
      footerBg: "#FEFCF8",
      badgeBg: "#C9A84C",
      badgeText: "#2A2216",
      specBadgeBg: "#F5F0E8",
      reviewBg: "#FEFCF8",
      navBorder: "#E8DEC8",
      textSecondary: "#6A5840",
      textSubtle: "#8A7058",
      borderLight: "#EDE5D0",
      borderInput: "#E8DEC8",
      borderMid: "#DCCEB4",
      ratingBarBg: "#E8DEC8",
      ratingStar: "#C9A84C",
      paginationBg: "#F5F0E8",
      textSummerSale: "#6A5840",
      textBreadcrumb: "#8A7058",
      tabActive: "#2A2216",
      categoryActiveBg: "#2A2216",
      categoryActiveText: "#FEFCF8",
      bookmarkBg: "#D4B870",
      walletBg: "#2A2216",
      popularBg0: "#F5F0E8",
      popularBg1: "#EDE5D4",
      popularBg2: "#E4D8C0",
      popularBg3: "#D4C4A4",
      popularText0: "#2A2216",
      popularText1: "#2A2216",
      popularText2: "#2A2216",
      popularText3: "#2A2216",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 8. NOCHE PROFUNDA — Dark premium with orange accents (DARK palette)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "noche-profunda",
    name: "Noche Profunda",
    description: "Azul navy oscuro con naranja cálido — lujo nocturno premium",
    style: "premium",
    preview: ["#F5841F", "#0D1117", "#161B22", "#E6EDF3", "#1C2128"],
    colors: {
      primary: "#F5841F",
      secondary: "#1C2128",
      background: "#0D1117",
      textPrimary: "#E6EDF3",
      headerBg: "#0D1117",
      sectionBg: "#0D1117",
      cardBg: "#161B22",
      border: "#30363D",
      surface: "#1C2128",
      searchBg: "#161B22",
      textMuted: "#7D8590",
      textFooter: "#7D8590",
      buttonBg: "#F5841F",
      buttonText: "#0D1117",
      footerBg: "#010409",
      badgeBg: "#F5841F",
      badgeText: "#0D1117",
      specBadgeBg: "#1C2128",
      reviewBg: "#161B22",
      navBorder: "#21262D",
      textSecondary: "#8D96A0",
      textSubtle: "#6E7681",
      borderLight: "#21262D",
      borderInput: "#30363D",
      borderMid: "#21262D",
      ratingBarBg: "#21262D",
      ratingStar: "#F5841F",
      paginationBg: "#1C2128",
      textSummerSale: "#7D8590",
      textBreadcrumb: "#6E7681",
      tabActive: "#F5841F",
      categoryActiveBg: "#F5841F",
      categoryActiveText: "#0D1117",
      bookmarkBg: "#26A69A",
      walletBg: "#1C2128",
      popularBg0: "#3A4A5C",
      popularBg1: "#2C3A4C",
      popularBg2: "#1E2A3C",
      popularBg3: "#101C2C",
      popularText0: "#E6EDF3",
      popularText1: "#E6EDF3",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 9. LAVANDA HOGAR — Soft lavender, calm and elegant
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "lavanda-hogar",
    name: "Lavanda Hogar",
    description: "Lavanda suave y crema — calma y elegancia para el hogar",
    style: "minimal",
    preview: ["#8B5CF6", "#3D1A78", "#FAF8FF", "#F0EEFF", "#A78BFA"],
    colors: {
      primary: "#8B5CF6",
      secondary: "#3D1A78",
      background: "#FAF8FF",
      textPrimary: "#3D1A78",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F0EEFF",
      border: "#DDD6FE",
      surface: "#F0EEFF",
      searchBg: "#F0EEFF",
      textMuted: "#6D5A9A",
      textFooter: "#8B7AC4",
      buttonBg: "#8B5CF6",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#8B5CF6",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F0EEFF",
      reviewBg: "#FAF8FF",
      navBorder: "#DDD6FE",
      textSecondary: "#6D5A9A",
      textSubtle: "#8B7AC4",
      borderLight: "#E8E2FF",
      borderInput: "#DDD6FE",
      borderMid: "#C4B5F4",
      ratingBarBg: "#DDD6FE",
      ratingStar: "#8B5CF6",
      paginationBg: "#F0EEFF",
      textSummerSale: "#6D5A9A",
      textBreadcrumb: "#8B7AC4",
      tabActive: "#3D1A78",
      categoryActiveBg: "#3D1A78",
      categoryActiveText: "#FFFFFF",
      bookmarkBg: "#A78BFA",
      walletBg: "#3D1A78",
      popularBg0: "#F0EEFF",
      popularBg1: "#E4DCFF",
      popularBg2: "#D4C8FF",
      popularBg3: "#C0ACFF",
      popularText0: "#3D1A78",
      popularText1: "#3D1A78",
      popularText2: "#3D1A78",
      popularText3: "#3D1A78",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 10. CARBÓN OSCURO — Charcoal dark + light gold, industrial minimal (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "carbon-oscuro",
    name: "Carbón Oscuro",
    description: "Carbón elegante con acentos dorados suaves — industrial de lujo",
    style: "premium",
    preview: ["#D4A847", "#1A1A1A", "#242424", "#E8E0D0", "#2A2A2A"],
    colors: {
      primary: "#D4A847",
      secondary: "#2A2A2A",
      background: "#1A1A1A",
      textPrimary: "#E8E0D0",
      headerBg: "#1A1A1A",
      sectionBg: "#1A1A1A",
      cardBg: "#242424",
      border: "#383838",
      surface: "#2A2A2A",
      searchBg: "#242424",
      textMuted: "#9A9080",
      textFooter: "#7A7068",
      buttonBg: "#D4A847",
      buttonText: "#1A1A1A",
      footerBg: "#111111",
      badgeBg: "#D4A847",
      badgeText: "#1A1A1A",
      specBadgeBg: "#2A2A2A",
      reviewBg: "#242424",
      navBorder: "#303030",
      textSecondary: "#A8A090",
      textSubtle: "#847C70",
      borderLight: "#303030",
      borderInput: "#383838",
      borderMid: "#303030",
      ratingBarBg: "#303030",
      ratingStar: "#D4A847",
      paginationBg: "#242424",
      textSummerSale: "#9A9080",
      textBreadcrumb: "#847C70",
      tabActive: "#D4A847",
      categoryActiveBg: "#D4A847",
      categoryActiveText: "#1A1A1A",
      bookmarkBg: "#C09040",
      walletBg: "#2A2A2A",
      popularBg0: "#3A3028",
      popularBg1: "#302820",
      popularBg2: "#261E18",
      popularBg3: "#1C1410",
      popularText0: "#E8E0D0",
      popularText1: "#E8E0D0",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 11. TERRACOTA HOGAR — Terracotta + natural linen, Bohemian comfort
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "terracota-hogar",
    name: "Terracota Hogar",
    description: "Terracota mediterránea sobre lino natural — bohemio y acogedor",
    style: "warm",
    preview: ["#C4603C", "#4A2818", "#FBF5EE", "#F3E8DC", "#E8A080"],
    colors: {
      primary: "#C4603C",
      secondary: "#4A2818",
      background: "#FBF5EE",
      textPrimary: "#4A2818",
      headerBg: "#FBF5EE",
      sectionBg: "#FBF5EE",
      cardBg: "#F3E8DC",
      border: "#E4CEC0",
      surface: "#F3E8DC",
      searchBg: "#F3E8DC",
      textMuted: "#7A4C3A",
      textFooter: "#9A6C58",
      buttonBg: "#C4603C",
      buttonText: "#FFFFFF",
      footerBg: "#FBF5EE",
      badgeBg: "#C4603C",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F3E8DC",
      reviewBg: "#FBF5EE",
      navBorder: "#E4CEC0",
      textSecondary: "#7A4C3A",
      textSubtle: "#9A6C58",
      borderLight: "#EAD8CC",
      borderInput: "#E4CEC0",
      borderMid: "#D8C0B0",
      ratingBarBg: "#E4CEC0",
      ratingStar: "#C4603C",
      paginationBg: "#F3E8DC",
      textSummerSale: "#7A4C3A",
      textBreadcrumb: "#9A6C58",
      tabActive: "#4A2818",
      categoryActiveBg: "#4A2818",
      categoryActiveText: "#FBF5EE",
      bookmarkBg: "#E8A080",
      walletBg: "#4A2818",
      popularBg0: "#F3E8DC",
      popularBg1: "#EAD8CC",
      popularBg2: "#DFC8B8",
      popularBg3: "#CEB0A0",
      popularText0: "#4A2818",
      popularText1: "#4A2818",
      popularText2: "#4A2818",
      popularText3: "#4A2818",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 12. PIZARRA MODERNA — Slate gray monochrome, professional modern
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "pizarra-moderna",
    name: "Pizarra Moderna",
    description: "Pizarra gris elegante — moderno profesional sin distracciones",
    style: "minimal",
    preview: ["#475569", "#1E293B", "#F8FAFC", "#F1F5F9", "#64748B"],
    colors: {
      primary: "#475569",
      secondary: "#1E293B",
      background: "#F8FAFC",
      textPrimary: "#1E293B",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F1F5F9",
      border: "#CBD5E1",
      surface: "#F1F5F9",
      searchBg: "#F1F5F9",
      textMuted: "#64748B",
      textFooter: "#94A3B8",
      buttonBg: "#475569",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#475569",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F1F5F9",
      reviewBg: "#F8FAFC",
      navBorder: "#CBD5E1",
      textSecondary: "#64748B",
      textSubtle: "#94A3B8",
      borderLight: "#E2E8F0",
      borderInput: "#CBD5E1",
      borderMid: "#B8C4D0",
      ratingBarBg: "#CBD5E1",
      ratingStar: "#475569",
      paginationBg: "#F1F5F9",
      textSummerSale: "#64748B",
      textBreadcrumb: "#94A3B8",
      tabActive: "#1E293B",
      categoryActiveBg: "#1E293B",
      categoryActiveText: "#F8FAFC",
      bookmarkBg: "#64748B",
      walletBg: "#1E293B",
      popularBg0: "#F1F5F9",
      popularBg1: "#E2E8F0",
      popularBg2: "#CBD5E1",
      popularBg3: "#B0BCC8",
      popularText0: "#1E293B",
      popularText1: "#1E293B",
      popularText2: "#1E293B",
      popularText3: "#1E293B",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 13. TEAL FRESH — Fresh teal + white, contemporary Scandinavian
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "teal-fresco",
    name: "Teal Fresco",
    description: "Teal fresco y blanco puro — contemporáneo y refrescante",
    style: "minimal",
    preview: ["#0D9488", "#1A3A38", "#F0FAFA", "#E0F5F4", "#14B8A6"],
    colors: {
      primary: "#0D9488",
      secondary: "#1A3A38",
      background: "#F0FAFA",
      textPrimary: "#1A3A38",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#E0F5F4",
      border: "#B0E0DC",
      surface: "#E0F5F4",
      searchBg: "#E0F5F4",
      textMuted: "#3A7874",
      textFooter: "#5A9A96",
      buttonBg: "#0D9488",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#0D9488",
      badgeText: "#FFFFFF",
      specBadgeBg: "#E0F5F4",
      reviewBg: "#F0FAFA",
      navBorder: "#B0E0DC",
      textSecondary: "#3A7874",
      textSubtle: "#5A9A96",
      borderLight: "#C8EDED",
      borderInput: "#B0E0DC",
      borderMid: "#A0D4D0",
      ratingBarBg: "#B0E0DC",
      ratingStar: "#0D9488",
      paginationBg: "#E0F5F4",
      textSummerSale: "#3A7874",
      textBreadcrumb: "#5A9A96",
      tabActive: "#1A3A38",
      categoryActiveBg: "#1A3A38",
      categoryActiveText: "#F0FAFA",
      bookmarkBg: "#14B8A6",
      walletBg: "#1A3A38",
      popularBg0: "#E0F5F4",
      popularBg1: "#C8EDED",
      popularBg2: "#B0E0DC",
      popularBg3: "#90CECE",
      popularText0: "#1A3A38",
      popularText1: "#1A3A38",
      popularText2: "#1A3A38",
      popularText3: "#1A3A38",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 14. PINO NÓRDICO — Deep forest pine + cream, rustic Scandinavian (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "pino-nordico",
    name: "Pino Nórdico",
    description: "Pino oscuro del bosque nórdico — rústico elegante y natural",
    style: "nature",
    preview: ["#7CB87C", "#1A2E1A", "#202C20", "#D4E8D4", "#2C3C2C"],
    colors: {
      primary: "#7CB87C",
      secondary: "#2C3C2C",
      background: "#1A2E1A",
      textPrimary: "#D4E8D4",
      headerBg: "#1A2E1A",
      sectionBg: "#1A2E1A",
      cardBg: "#202C20",
      border: "#304430",
      surface: "#2C3C2C",
      searchBg: "#202C20",
      textMuted: "#6A8A6A",
      textFooter: "#5A7A5A",
      buttonBg: "#7CB87C",
      buttonText: "#1A2E1A",
      footerBg: "#111E11",
      badgeBg: "#7CB87C",
      badgeText: "#1A2E1A",
      specBadgeBg: "#2C3C2C",
      reviewBg: "#202C20",
      navBorder: "#283828",
      textSecondary: "#7A9A7A",
      textSubtle: "#5A7A5A",
      borderLight: "#283828",
      borderInput: "#304430",
      borderMid: "#283828",
      ratingBarBg: "#283828",
      ratingStar: "#7CB87C",
      paginationBg: "#2C3C2C",
      textSummerSale: "#6A8A6A",
      textBreadcrumb: "#5A7A5A",
      tabActive: "#7CB87C",
      categoryActiveBg: "#7CB87C",
      categoryActiveText: "#1A2E1A",
      bookmarkBg: "#5A9A5A",
      walletBg: "#2C3C2C",
      popularBg0: "#2C4830",
      popularBg1: "#243C28",
      popularBg2: "#1C3020",
      popularBg3: "#142418",
      popularText0: "#D4E8D4",
      popularText1: "#D4E8D4",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 15. DURAZNO PASTEL — Peach pastel + ivory, playful feminine
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "durazno-pastel",
    name: "Durazno Pastel",
    description: "Durazno pastel y marfil — juguetón, dulce y acogedor",
    style: "playful",
    preview: ["#F4926A", "#5A2818", "#FFF8F4", "#FFE8DC", "#FFB090"],
    colors: {
      primary: "#F4926A",
      secondary: "#5A2818",
      background: "#FFF8F4",
      textPrimary: "#5A2818",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFE8DC",
      border: "#FFD0C0",
      surface: "#FFE8DC",
      searchBg: "#FFE8DC",
      textMuted: "#9A5440",
      textFooter: "#BA7460",
      buttonBg: "#F4926A",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#F4926A",
      badgeText: "#FFFFFF",
      specBadgeBg: "#FFE8DC",
      reviewBg: "#FFF8F4",
      navBorder: "#FFD0C0",
      textSecondary: "#9A5440",
      textSubtle: "#BA7460",
      borderLight: "#FFDECC",
      borderInput: "#FFD0C0",
      borderMid: "#FFC0A8",
      ratingBarBg: "#FFD0C0",
      ratingStar: "#F4926A",
      paginationBg: "#FFE8DC",
      textSummerSale: "#9A5440",
      textBreadcrumb: "#BA7460",
      tabActive: "#5A2818",
      categoryActiveBg: "#5A2818",
      categoryActiveText: "#FFFFFF",
      bookmarkBg: "#FFB090",
      walletBg: "#5A2818",
      popularBg0: "#FFE8DC",
      popularBg1: "#FFD8C8",
      popularBg2: "#FFC8B4",
      popularBg3: "#FFB49C",
      popularText0: "#5A2818",
      popularText1: "#5A2818",
      popularText2: "#5A2818",
      popularText3: "#5A2818",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 16. MODERNO GRIS — Cool gray + bright orange pop, brutalist modern
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "moderno-gris",
    name: "Moderno Gris",
    description: "Gris neutro frío con pop de naranja — brutalismo moderno y directo",
    style: "brutalist",
    preview: ["#FF6B00", "#1C1C1C", "#F4F4F4", "#EBEBEB", "#FF9940"],
    colors: {
      primary: "#FF6B00",
      secondary: "#1C1C1C",
      background: "#F4F4F4",
      textPrimary: "#1C1C1C",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#EBEBEB",
      border: "#D0D0D0",
      surface: "#EBEBEB",
      searchBg: "#EBEBEB",
      textMuted: "#5A5A5A",
      textFooter: "#7A7A7A",
      buttonBg: "#FF6B00",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#FF6B00",
      badgeText: "#FFFFFF",
      specBadgeBg: "#EBEBEB",
      reviewBg: "#F4F4F4",
      navBorder: "#D0D0D0",
      textSecondary: "#5A5A5A",
      textSubtle: "#7A7A7A",
      borderLight: "#E4E4E4",
      borderInput: "#D0D0D0",
      borderMid: "#C4C4C4",
      ratingBarBg: "#D0D0D0",
      ratingStar: "#FF6B00",
      paginationBg: "#EBEBEB",
      textSummerSale: "#5A5A5A",
      textBreadcrumb: "#7A7A7A",
      tabActive: "#1C1C1C",
      categoryActiveBg: "#1C1C1C",
      categoryActiveText: "#FFFFFF",
      bookmarkBg: "#FF9940",
      walletBg: "#1C1C1C",
      popularBg0: "#EBEBEB",
      popularBg1: "#DCDCDC",
      popularBg2: "#CCCCCC",
      popularBg3: "#B8B8B8",
      popularText0: "#1C1C1C",
      popularText1: "#1C1C1C",
      popularText2: "#1C1C1C",
      popularText3: "#1C1C1C",
    },
  },
];
