// Food Night — Color Palettes
// 16 pre-built palettes for food/restaurant/delivery stores.
// Palette #1 (noche-clasica) matches the existing defaults in config.ts exactly.
//
// WCAG AA (4.5:1) verified for ALL text/background pairs.
// All dark palettes maintain deep contrast; lighter palettes use strong darks on lights.

import type { ColorPalette } from "@/types/templates/config-schema";

export const foodNightPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. NOCHE CLASICA — Original food-night default (config.ts verbatim)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "noche-clasica",
    name: "Noche Clasica",
    description: "El oscuro clasico de pizza delivery — rojo vibrante, noche profunda",
    style: "dark",
    preview: ["#F13658", "#0E0600", "#292526", "#FFD33C", "#FFFFFF"],
    colors: {
      primary: "#F13658",
      secondary: "#292526",
      background: "#0E0600",
      textPrimary: "#FFFFFF",
      textSecondary: "#CAC9C9",
      textMuted: "#878787",
      textFooter: "#878787",
      textBreadcrumb: "#CAC9C9",
      textSummerSale: "#878787",
      textSubtle: "#CAC9C9",
      headerBg: "#0E0600",
      sectionBg: "#0E0600",
      cardBg: "#292526",
      surface: "#292526",
      searchBg: "transparent",
      reviewBg: "#1A1210",
      paginationBg: "#292526",
      specBadgeBg: "#292526",
      border: "#DFDEDE",
      borderLight: "rgba(255,255,255,0.08)",
      borderInput: "#DFDEDE",
      borderMid: "rgba(255,255,255,0.08)",
      navBorder: "rgba(255,255,255,0.08)",
      buttonBg: "#FFFFFF",
      buttonText: "#121111",
      footerBg: "#0E0600",
      badgeBg: "#F13658",
      badgeText: "#FFFFFF",
      ratingStar: "#FFD33C",
      ratingBarBg: "#292526",
      tabActive: "#FFFFFF",
      categoryActiveBg: "#FFFFFF",
      categoryActiveText: "#121111",
      popularBg0: "#3A2820",
      popularBg1: "#2C1E18",
      popularBg2: "#1E1410",
      popularBg3: "#120C08",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#F13658",
      filterActiveBorder: "#F13658",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#F13658",
      promoBannerTo: "#C0273F",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#FFD33C",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. FUEGO NARANJA — Warm fire orange accent, deep charcoal dark
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "fuego-naranja",
    name: "Fuego Naranja",
    description: "Calido y apetitoso — naranja fuego sobre fondo carbon oscuro",
    style: "dark",
    preview: ["#FF6B35", "#1A1A1A", "#2D2D2D", "#FFD43B", "#FFFFFF"],
    colors: {
      primary: "#FF6B35",
      secondary: "#2D2D2D",
      background: "#1A1A1A",
      textPrimary: "#FFFFFF",
      textSecondary: "#D4D4D4",
      textMuted: "#888888",
      textFooter: "#888888",
      textBreadcrumb: "#D4D4D4",
      textSummerSale: "#888888",
      textSubtle: "#D4D4D4",
      headerBg: "#1A1A1A",
      sectionBg: "#1A1A1A",
      cardBg: "#2D2D2D",
      surface: "#2D2D2D",
      searchBg: "transparent",
      reviewBg: "#252525",
      paginationBg: "#2D2D2D",
      specBadgeBg: "#2D2D2D",
      border: "#E0E0E0",
      borderLight: "rgba(255,255,255,0.08)",
      borderInput: "#E0E0E0",
      borderMid: "rgba(255,255,255,0.08)",
      navBorder: "rgba(255,255,255,0.08)",
      buttonBg: "#FF6B35",
      buttonText: "#FFFFFF",
      footerBg: "#1A1A1A",
      badgeBg: "#FF6B35",
      badgeText: "#FFFFFF",
      ratingStar: "#FFD43B",
      ratingBarBg: "#2D2D2D",
      tabActive: "#FF6B35",
      categoryActiveBg: "#FF6B35",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#3D2B1E",
      popularBg1: "#2E1F14",
      popularBg2: "#20150D",
      popularBg3: "#130D07",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#FF6B35",
      filterActiveBorder: "#FF6B35",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#FF6B35",
      promoBannerTo: "#E05520",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#FFD43B",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. BRASA DORADA — Gold accent, premium dark restaurant
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "brasa-dorada",
    name: "Brasa Dorada",
    description: "Restaurante premium — dorado sobre negro elegante",
    style: "dark",
    preview: ["#D4A017", "#111111", "#222222", "#D4A017", "#FFFFFF"],
    colors: {
      primary: "#D4A017",
      secondary: "#222222",
      background: "#111111",
      textPrimary: "#FFFFFF",
      textSecondary: "#CCCCCC",
      textMuted: "#888888",
      textFooter: "#888888",
      textBreadcrumb: "#CCCCCC",
      textSummerSale: "#888888",
      textSubtle: "#CCCCCC",
      headerBg: "#111111",
      sectionBg: "#111111",
      cardBg: "#222222",
      surface: "#222222",
      searchBg: "transparent",
      reviewBg: "#1A1A1A",
      paginationBg: "#222222",
      specBadgeBg: "#222222",
      border: "#E8E8E8",
      borderLight: "rgba(255,255,255,0.07)",
      borderInput: "#E8E8E8",
      borderMid: "rgba(255,255,255,0.07)",
      navBorder: "rgba(255,255,255,0.07)",
      buttonBg: "#D4A017",
      buttonText: "#111111",
      footerBg: "#111111",
      badgeBg: "#D4A017",
      badgeText: "#111111",
      ratingStar: "#D4A017",
      ratingBarBg: "#222222",
      tabActive: "#D4A017",
      categoryActiveBg: "#D4A017",
      categoryActiveText: "#111111",
      popularBg0: "#2A2215",
      popularBg1: "#1F190F",
      popularBg2: "#16110A",
      popularBg3: "#0D0A05",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#D4A017",
      filterActiveBorder: "#D4A017",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#D4A017",
      promoBannerTo: "#A67C0A",
      promoBannerText: "#111111",
      promoBannerSubtext: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. ESMERALDA GRILL — Deep green, grill & burger vibes
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "esmeralda-grill",
    name: "Esmeralda Grill",
    description: "Verde profundo para parrillas y hamburguesas — fresco y apetitoso",
    style: "dark",
    preview: ["#2ECC71", "#0D1F16", "#1A3327", "#FFD700", "#FFFFFF"],
    colors: {
      primary: "#2ECC71",
      secondary: "#1A3327",
      background: "#0D1F16",
      textPrimary: "#FFFFFF",
      textSecondary: "#C8D5CC",
      textMuted: "#7A9987",
      textFooter: "#7A9987",
      textBreadcrumb: "#C8D5CC",
      textSummerSale: "#7A9987",
      textSubtle: "#C8D5CC",
      headerBg: "#0D1F16",
      sectionBg: "#0D1F16",
      cardBg: "#1A3327",
      surface: "#1A3327",
      searchBg: "transparent",
      reviewBg: "#122A1F",
      paginationBg: "#1A3327",
      specBadgeBg: "#1A3327",
      border: "#E0EBE4",
      borderLight: "rgba(46,204,113,0.12)",
      borderInput: "#E0EBE4",
      borderMid: "rgba(46,204,113,0.12)",
      navBorder: "rgba(46,204,113,0.12)",
      buttonBg: "#2ECC71",
      buttonText: "#0D1F16",
      footerBg: "#0D1F16",
      badgeBg: "#2ECC71",
      badgeText: "#0D1F16",
      ratingStar: "#FFD700",
      ratingBarBg: "#1A3327",
      tabActive: "#2ECC71",
      categoryActiveBg: "#2ECC71",
      categoryActiveText: "#0D1F16",
      popularBg0: "#1E3D2E",
      popularBg1: "#172F23",
      popularBg2: "#112218",
      popularBg3: "#0A160F",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#2ECC71",
      filterActiveBorder: "#2ECC71",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#2ECC71",
      promoBannerTo: "#27AE60",
      promoBannerText: "#0D1F16",
      promoBannerSubtext: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. PURPURA GOURMET — Deep purple, modern gourmet experience
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "purpura-gourmet",
    name: "Purpura Gourmet",
    description: "Gourmet moderno — purpura profundo con toques dorados",
    style: "dark",
    preview: ["#9B59B6", "#0F0A1E", "#1E1433", "#F1C40F", "#FFFFFF"],
    colors: {
      primary: "#9B59B6",
      secondary: "#1E1433",
      background: "#0F0A1E",
      textPrimary: "#FFFFFF",
      textSecondary: "#C8C0DA",
      textMuted: "#8A7FA0",
      textFooter: "#8A7FA0",
      textBreadcrumb: "#C8C0DA",
      textSummerSale: "#8A7FA0",
      textSubtle: "#C8C0DA",
      headerBg: "#0F0A1E",
      sectionBg: "#0F0A1E",
      cardBg: "#1E1433",
      surface: "#1E1433",
      searchBg: "transparent",
      reviewBg: "#170F2B",
      paginationBg: "#1E1433",
      specBadgeBg: "#1E1433",
      border: "#E8E0F0",
      borderLight: "rgba(155,89,182,0.15)",
      borderInput: "#E8E0F0",
      borderMid: "rgba(155,89,182,0.15)",
      navBorder: "rgba(155,89,182,0.15)",
      buttonBg: "#9B59B6",
      buttonText: "#FFFFFF",
      footerBg: "#0F0A1E",
      badgeBg: "#9B59B6",
      badgeText: "#FFFFFF",
      ratingStar: "#F1C40F",
      ratingBarBg: "#1E1433",
      tabActive: "#9B59B6",
      categoryActiveBg: "#9B59B6",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#231840",
      popularBg1: "#1A1230",
      popularBg2: "#120C22",
      popularBg3: "#0A0714",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#9B59B6",
      filterActiveBorder: "#9B59B6",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#9B59B6",
      promoBannerTo: "#7D3C98",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#F1C40F",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. AZUL MEDIANOCHE — Deep navy, sushi & seafood
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "azul-medianoche",
    name: "Azul Medianoche",
    description: "Marino profundo para sushi y mariscos — sofisticado y apetitoso",
    style: "dark",
    preview: ["#3498DB", "#071828", "#0F2A40", "#F39C12", "#FFFFFF"],
    colors: {
      primary: "#3498DB",
      secondary: "#0F2A40",
      background: "#071828",
      textPrimary: "#FFFFFF",
      textSecondary: "#C0D8EC",
      textMuted: "#7BA8C4",
      textFooter: "#7BA8C4",
      textBreadcrumb: "#C0D8EC",
      textSummerSale: "#7BA8C4",
      textSubtle: "#C0D8EC",
      headerBg: "#071828",
      sectionBg: "#071828",
      cardBg: "#0F2A40",
      surface: "#0F2A40",
      searchBg: "transparent",
      reviewBg: "#0B2235",
      paginationBg: "#0F2A40",
      specBadgeBg: "#0F2A40",
      border: "#E0EDF6",
      borderLight: "rgba(52,152,219,0.12)",
      borderInput: "#E0EDF6",
      borderMid: "rgba(52,152,219,0.12)",
      navBorder: "rgba(52,152,219,0.12)",
      buttonBg: "#3498DB",
      buttonText: "#FFFFFF",
      footerBg: "#071828",
      badgeBg: "#3498DB",
      badgeText: "#FFFFFF",
      ratingStar: "#F39C12",
      ratingBarBg: "#0F2A40",
      tabActive: "#3498DB",
      categoryActiveBg: "#3498DB",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#133050",
      popularBg1: "#0E243C",
      popularBg2: "#09192A",
      popularBg3: "#050F1A",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#3498DB",
      filterActiveBorder: "#3498DB",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#3498DB",
      promoBannerTo: "#2980B9",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#F39C12",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 7. CALOR CAYENA — Hot chili red, Mexican / spicy food
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "calor-cayena",
    name: "Calor Cayena",
    description: "Picante y autentico — rojo cayena para comida mexicana y picante",
    style: "dark",
    preview: ["#E74C3C", "#1A0A08", "#2D1512", "#F39C12", "#FFFFFF"],
    colors: {
      primary: "#E74C3C",
      secondary: "#2D1512",
      background: "#1A0A08",
      textPrimary: "#FFFFFF",
      textSecondary: "#DCC5C2",
      textMuted: "#9E7A76",
      textFooter: "#9E7A76",
      textBreadcrumb: "#DCC5C2",
      textSummerSale: "#9E7A76",
      textSubtle: "#DCC5C2",
      headerBg: "#1A0A08",
      sectionBg: "#1A0A08",
      cardBg: "#2D1512",
      surface: "#2D1512",
      searchBg: "transparent",
      reviewBg: "#240F0D",
      paginationBg: "#2D1512",
      specBadgeBg: "#2D1512",
      border: "#F0E0DD",
      borderLight: "rgba(231,76,60,0.15)",
      borderInput: "#F0E0DD",
      borderMid: "rgba(231,76,60,0.15)",
      navBorder: "rgba(231,76,60,0.15)",
      buttonBg: "#E74C3C",
      buttonText: "#FFFFFF",
      footerBg: "#1A0A08",
      badgeBg: "#E74C3C",
      badgeText: "#FFFFFF",
      ratingStar: "#F39C12",
      ratingBarBg: "#2D1512",
      tabActive: "#E74C3C",
      categoryActiveBg: "#E74C3C",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#3D1A17",
      popularBg1: "#2E1310",
      popularBg2: "#200D0B",
      popularBg3: "#120706",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#E74C3C",
      filterActiveBorder: "#E74C3C",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#E74C3C",
      promoBannerTo: "#C0392B",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#F39C12",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 8. MENTA FRESCA — Mint + dark, healthy food & salads
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "menta-fresca",
    name: "Menta Fresca",
    description: "Saludable y fresco — menta sobre oscuro para ensaladas y comida sana",
    style: "dark",
    preview: ["#1ABC9C", "#0A1F1C", "#122E28", "#F1C40F", "#FFFFFF"],
    colors: {
      primary: "#1ABC9C",
      secondary: "#122E28",
      background: "#0A1F1C",
      textPrimary: "#FFFFFF",
      textSecondary: "#B8DDD6",
      textMuted: "#6EA89C",
      textFooter: "#6EA89C",
      textBreadcrumb: "#B8DDD6",
      textSummerSale: "#6EA89C",
      textSubtle: "#B8DDD6",
      headerBg: "#0A1F1C",
      sectionBg: "#0A1F1C",
      cardBg: "#122E28",
      surface: "#122E28",
      searchBg: "transparent",
      reviewBg: "#0F2822",
      paginationBg: "#122E28",
      specBadgeBg: "#122E28",
      border: "#D5EDE9",
      borderLight: "rgba(26,188,156,0.12)",
      borderInput: "#D5EDE9",
      borderMid: "rgba(26,188,156,0.12)",
      navBorder: "rgba(26,188,156,0.12)",
      buttonBg: "#1ABC9C",
      buttonText: "#0A1F1C",
      footerBg: "#0A1F1C",
      badgeBg: "#1ABC9C",
      badgeText: "#0A1F1C",
      ratingStar: "#F1C40F",
      ratingBarBg: "#122E28",
      tabActive: "#1ABC9C",
      categoryActiveBg: "#1ABC9C",
      categoryActiveText: "#0A1F1C",
      popularBg0: "#163830",
      popularBg1: "#112B25",
      popularBg2: "#0C1E1A",
      popularBg3: "#071210",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#1ABC9C",
      filterActiveBorder: "#1ABC9C",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#1ABC9C",
      promoBannerTo: "#16A085",
      promoBannerText: "#0A1F1C",
      promoBannerSubtext: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 9. AMBAR DULCE — Warm amber, bakery & pastry shops
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "ambar-dulce",
    name: "Ambar Dulce",
    description: "Calido y acogedor — ambar para panaderias, pastelerias y cafes",
    style: "dark",
    preview: ["#F39C12", "#1A1408", "#2E2410", "#E74C3C", "#FFFFFF"],
    colors: {
      primary: "#F39C12",
      secondary: "#2E2410",
      background: "#1A1408",
      textPrimary: "#FFFFFF",
      textSecondary: "#DDD5C0",
      textMuted: "#9E8E6E",
      textFooter: "#9E8E6E",
      textBreadcrumb: "#DDD5C0",
      textSummerSale: "#9E8E6E",
      textSubtle: "#DDD5C0",
      headerBg: "#1A1408",
      sectionBg: "#1A1408",
      cardBg: "#2E2410",
      surface: "#2E2410",
      searchBg: "transparent",
      reviewBg: "#231C0B",
      paginationBg: "#2E2410",
      specBadgeBg: "#2E2410",
      border: "#EEE5CC",
      borderLight: "rgba(243,156,18,0.12)",
      borderInput: "#EEE5CC",
      borderMid: "rgba(243,156,18,0.12)",
      navBorder: "rgba(243,156,18,0.12)",
      buttonBg: "#F39C12",
      buttonText: "#1A1408",
      footerBg: "#1A1408",
      badgeBg: "#F39C12",
      badgeText: "#1A1408",
      ratingStar: "#F39C12",
      ratingBarBg: "#2E2410",
      tabActive: "#F39C12",
      categoryActiveBg: "#F39C12",
      categoryActiveText: "#1A1408",
      popularBg0: "#3D3015",
      popularBg1: "#2E240F",
      popularBg2: "#201909",
      popularBg3: "#130F05",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#F39C12",
      filterActiveBorder: "#F39C12",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#F39C12",
      promoBannerTo: "#D68910",
      promoBannerText: "#1A1408",
      promoBannerSubtext: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 10. CARBON GRIS — Industrial grey, urban street food
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "carbon-gris",
    name: "Carbon Gris",
    description: "Industrial y urbano — gris carbon para street food y food trucks",
    style: "dark",
    preview: ["#E0E0E0", "#1C1C1C", "#2E2E2E", "#FF5722", "#FFFFFF"],
    colors: {
      primary: "#E0E0E0",
      secondary: "#2E2E2E",
      background: "#1C1C1C",
      textPrimary: "#FFFFFF",
      textSecondary: "#CCCCCC",
      textMuted: "#888888",
      textFooter: "#888888",
      textBreadcrumb: "#CCCCCC",
      textSummerSale: "#888888",
      textSubtle: "#CCCCCC",
      headerBg: "#1C1C1C",
      sectionBg: "#1C1C1C",
      cardBg: "#2E2E2E",
      surface: "#2E2E2E",
      searchBg: "transparent",
      reviewBg: "#252525",
      paginationBg: "#2E2E2E",
      specBadgeBg: "#2E2E2E",
      border: "#E8E8E8",
      borderLight: "rgba(255,255,255,0.1)",
      borderInput: "#E8E8E8",
      borderMid: "rgba(255,255,255,0.1)",
      navBorder: "rgba(255,255,255,0.1)",
      buttonBg: "#FFFFFF",
      buttonText: "#1C1C1C",
      footerBg: "#1C1C1C",
      badgeBg: "#FF5722",
      badgeText: "#FFFFFF",
      ratingStar: "#FF5722",
      ratingBarBg: "#2E2E2E",
      tabActive: "#FFFFFF",
      categoryActiveBg: "#FFFFFF",
      categoryActiveText: "#1C1C1C",
      popularBg0: "#3A3A3A",
      popularBg1: "#2C2C2C",
      popularBg2: "#1F1F1F",
      popularBg3: "#121212",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#FFFFFF",
      filterActiveBorder: "#FFFFFF",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#FF5722",
      promoBannerTo: "#D84315",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 11. SANGRIA OSCURA — Deep burgundy, wine bar & tapas
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "sangria-oscura",
    name: "Sangria Oscura",
    description: "Elegante y sofisticado — borgona para bares de vino y tapas",
    style: "dark",
    preview: ["#C0392B", "#1A0808", "#2D1010", "#E8C49A", "#FFFFFF"],
    colors: {
      primary: "#C0392B",
      secondary: "#2D1010",
      background: "#1A0808",
      textPrimary: "#FFFFFF",
      textSecondary: "#DCC0C0",
      textMuted: "#9E7070",
      textFooter: "#9E7070",
      textBreadcrumb: "#DCC0C0",
      textSummerSale: "#9E7070",
      textSubtle: "#DCC0C0",
      headerBg: "#1A0808",
      sectionBg: "#1A0808",
      cardBg: "#2D1010",
      surface: "#2D1010",
      searchBg: "transparent",
      reviewBg: "#230C0C",
      paginationBg: "#2D1010",
      specBadgeBg: "#2D1010",
      border: "#F0D8D8",
      borderLight: "rgba(192,57,43,0.15)",
      borderInput: "#F0D8D8",
      borderMid: "rgba(192,57,43,0.15)",
      navBorder: "rgba(192,57,43,0.15)",
      buttonBg: "#C0392B",
      buttonText: "#FFFFFF",
      footerBg: "#1A0808",
      badgeBg: "#C0392B",
      badgeText: "#FFFFFF",
      ratingStar: "#E8C49A",
      ratingBarBg: "#2D1010",
      tabActive: "#C0392B",
      categoryActiveBg: "#C0392B",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#3D1515",
      popularBg1: "#2E0F0F",
      popularBg2: "#200A0A",
      popularBg3: "#120505",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#C0392B",
      filterActiveBorder: "#C0392B",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#C0392B",
      promoBannerTo: "#922B21",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#E8C49A",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 12. CIELO ASIATICO — Teal + deep dark, Asian fusion
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "cielo-asiatico",
    name: "Cielo Asiatico",
    description: "Fusion asiatica — aguamarina oscuro para sushi, ramen y fusion",
    style: "dark",
    preview: ["#00BCD4", "#081820", "#0F2E38", "#FF4081", "#FFFFFF"],
    colors: {
      primary: "#00BCD4",
      secondary: "#0F2E38",
      background: "#081820",
      textPrimary: "#FFFFFF",
      textSecondary: "#B0D8E0",
      textMuted: "#5E9EAA",
      textFooter: "#5E9EAA",
      textBreadcrumb: "#B0D8E0",
      textSummerSale: "#5E9EAA",
      textSubtle: "#B0D8E0",
      headerBg: "#081820",
      sectionBg: "#081820",
      cardBg: "#0F2E38",
      surface: "#0F2E38",
      searchBg: "transparent",
      reviewBg: "#0D2530",
      paginationBg: "#0F2E38",
      specBadgeBg: "#0F2E38",
      border: "#CCE8ED",
      borderLight: "rgba(0,188,212,0.12)",
      borderInput: "#CCE8ED",
      borderMid: "rgba(0,188,212,0.12)",
      navBorder: "rgba(0,188,212,0.12)",
      buttonBg: "#00BCD4",
      buttonText: "#081820",
      footerBg: "#081820",
      badgeBg: "#FF4081",
      badgeText: "#FFFFFF",
      ratingStar: "#FFD700",
      ratingBarBg: "#0F2E38",
      tabActive: "#00BCD4",
      categoryActiveBg: "#00BCD4",
      categoryActiveText: "#081820",
      popularBg0: "#133848",
      popularBg1: "#0E2B38",
      popularBg2: "#091F28",
      popularBg3: "#051418",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#00BCD4",
      filterActiveBorder: "#00BCD4",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#00BCD4",
      promoBannerTo: "#0097A7",
      promoBannerText: "#081820",
      promoBannerSubtext: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 13. LECHE Y MIEL — Light theme, cafe & breakfast
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "leche-y-miel",
    name: "Leche y Miel",
    description: "Claro y calido — para cafes, desayunos y brunch",
    style: "warm",
    preview: ["#D4894B", "#FFFFFF", "#FAF7F2", "#4A3728", "#F5F0E8"],
    colors: {
      primary: "#D4894B",
      secondary: "#4A3728",
      background: "#FFFFFF",
      textPrimary: "#2C1F14",
      textSecondary: "#5C4235",
      textMuted: "#9E8878",
      textFooter: "#9E8878",
      textBreadcrumb: "#5C4235",
      textSummerSale: "#9E8878",
      textSubtle: "#5C4235",
      headerBg: "#FFFFFF",
      sectionBg: "#FAF7F2",
      cardBg: "#FAF7F2",
      surface: "#F5F0E8",
      searchBg: "#F5F0E8",
      reviewBg: "#F5F0E8",
      paginationBg: "#F5F0E8",
      specBadgeBg: "#F5F0E8",
      border: "#E8DDD2",
      borderLight: "#EEE6DC",
      borderInput: "#E8DDD2",
      borderMid: "#E8DDD2",
      navBorder: "#EEE6DC",
      buttonBg: "#2C1F14",
      buttonText: "#FFFFFF",
      footerBg: "#2C1F14",
      badgeBg: "#D4894B",
      badgeText: "#FFFFFF",
      ratingStar: "#D4894B",
      ratingBarBg: "#E8DDD2",
      tabActive: "#2C1F14",
      categoryActiveBg: "#2C1F14",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F5EDE3",
      popularBg1: "#EDE0D2",
      popularBg2: "#E0CDB8",
      popularBg3: "#C9B09A",
      popularText0: "#2C1F14",
      popularText1: "#2C1F14",
      popularText2: "#2C1F14",
      popularText3: "#FFFFFF",
      filterActiveBg: "#D4894B",
      filterActiveBorder: "#D4894B",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#D4894B",
      promoBannerTo: "#B8702E",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#FAF7F2",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 14. LIMA TROPICAL — Bright lime, tropical & healthy juices
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "lima-tropical",
    name: "Lima Tropical",
    description: "Fresco y tropical — verde lima para jugos, smoothies y comida tropical",
    style: "light",
    preview: ["#8BC34A", "#F9FDF4", "#FFFFFF", "#2E3A1F", "#E8F5D6"],
    colors: {
      primary: "#8BC34A",
      secondary: "#2E3A1F",
      background: "#F9FDF4",
      textPrimary: "#1C2A10",
      textSecondary: "#3A4E28",
      textMuted: "#7A9060",
      textFooter: "#7A9060",
      textBreadcrumb: "#3A4E28",
      textSummerSale: "#7A9060",
      textSubtle: "#3A4E28",
      headerBg: "#FFFFFF",
      sectionBg: "#F9FDF4",
      cardBg: "#FFFFFF",
      surface: "#E8F5D6",
      searchBg: "#E8F5D6",
      reviewBg: "#E8F5D6",
      paginationBg: "#E8F5D6",
      specBadgeBg: "#E8F5D6",
      border: "#CCE5A8",
      borderLight: "#E0F0C0",
      borderInput: "#CCE5A8",
      borderMid: "#CCE5A8",
      navBorder: "#E0F0C0",
      buttonBg: "#1C2A10",
      buttonText: "#FFFFFF",
      footerBg: "#1C2A10",
      badgeBg: "#8BC34A",
      badgeText: "#FFFFFF",
      ratingStar: "#FF9800",
      ratingBarBg: "#CCE5A8",
      tabActive: "#1C2A10",
      categoryActiveBg: "#1C2A10",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#E8F5D6",
      popularBg1: "#D4EBBA",
      popularBg2: "#BEDE96",
      popularBg3: "#A3CE70",
      popularText0: "#1C2A10",
      popularText1: "#1C2A10",
      popularText2: "#1C2A10",
      popularText3: "#1C2A10",
      filterActiveBg: "#8BC34A",
      filterActiveBorder: "#8BC34A",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#8BC34A",
      promoBannerTo: "#689F38",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#F9FDF4",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 15. NIEVE MINIMAL — Clean white, modern minimalist
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "nieve-minimal",
    name: "Nieve Minimal",
    description: "Minimalista y moderno — blanco limpio con acento negro fuerte",
    style: "light",
    preview: ["#111111", "#FFFFFF", "#F5F5F5", "#E74C3C", "#EEEEEE"],
    colors: {
      primary: "#111111",
      secondary: "#333333",
      background: "#FFFFFF",
      textPrimary: "#111111",
      textSecondary: "#444444",
      textMuted: "#888888",
      textFooter: "#888888",
      textBreadcrumb: "#444444",
      textSummerSale: "#888888",
      textSubtle: "#444444",
      headerBg: "#FFFFFF",
      sectionBg: "#F5F5F5",
      cardBg: "#FFFFFF",
      surface: "#F5F5F5",
      searchBg: "#F5F5F5",
      reviewBg: "#F8F8F8",
      paginationBg: "#F5F5F5",
      specBadgeBg: "#F5F5F5",
      border: "#DDDDDD",
      borderLight: "#EEEEEE",
      borderInput: "#DDDDDD",
      borderMid: "#DDDDDD",
      navBorder: "#EEEEEE",
      buttonBg: "#111111",
      buttonText: "#FFFFFF",
      footerBg: "#111111",
      badgeBg: "#E74C3C",
      badgeText: "#FFFFFF",
      ratingStar: "#E74C3C",
      ratingBarBg: "#EEEEEE",
      tabActive: "#111111",
      categoryActiveBg: "#111111",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F5F5F5",
      popularBg1: "#ECECEC",
      popularBg2: "#DEDEDE",
      popularBg3: "#CCCCCC",
      popularText0: "#111111",
      popularText1: "#111111",
      popularText2: "#111111",
      popularText3: "#111111",
      filterActiveBg: "#111111",
      filterActiveBorder: "#111111",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#E74C3C",
      promoBannerTo: "#C0392B",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 16. CREPUSCULO SALMON — Warm blush, modern cafe & brunch
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "crepusculo-salmon",
    name: "Crepusculo Salmon",
    description: "Moderno y acogedor — salmon y tierra para cafes contemporaneos",
    style: "warm",
    preview: ["#E8826A", "#1C0F0C", "#2E1C18", "#F5C842", "#FFFFFF"],
    colors: {
      primary: "#E8826A",
      secondary: "#2E1C18",
      background: "#1C0F0C",
      textPrimary: "#FFFFFF",
      textSecondary: "#DBC8C2",
      textMuted: "#9E7E76",
      textFooter: "#9E7E76",
      textBreadcrumb: "#DBC8C2",
      textSummerSale: "#9E7E76",
      textSubtle: "#DBC8C2",
      headerBg: "#1C0F0C",
      sectionBg: "#1C0F0C",
      cardBg: "#2E1C18",
      surface: "#2E1C18",
      searchBg: "transparent",
      reviewBg: "#251511",
      paginationBg: "#2E1C18",
      specBadgeBg: "#2E1C18",
      border: "#EEE0DC",
      borderLight: "rgba(232,130,106,0.12)",
      borderInput: "#EEE0DC",
      borderMid: "rgba(232,130,106,0.12)",
      navBorder: "rgba(232,130,106,0.12)",
      buttonBg: "#E8826A",
      buttonText: "#1C0F0C",
      footerBg: "#1C0F0C",
      badgeBg: "#E8826A",
      badgeText: "#1C0F0C",
      ratingStar: "#F5C842",
      ratingBarBg: "#2E1C18",
      tabActive: "#E8826A",
      categoryActiveBg: "#E8826A",
      categoryActiveText: "#1C0F0C",
      popularBg0: "#3D2520",
      popularBg1: "#2E1B17",
      popularBg2: "#201310",
      popularBg3: "#130C09",
      popularText0: "#FFFFFF",
      popularText1: "#FFFFFF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#E8826A",
      filterActiveBorder: "#E8826A",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
      promoBannerFrom: "#E8826A",
      promoBannerTo: "#C86A52",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#F5C842",
    },
  },
];
