// Pets Modern — Color Palettes
// 16 pre-built palettes designed by Valentina (UI/UX).
// Palette #1 (naranja-mascota) matches the existing defaults in config.ts exactly.
// All color tokens are defined per palette for full harmony.
//
// WCAG AA (4.5:1) verified for ALL text/background pairs.
// Dark palettes: noche-premium, bosque-profundo, neon-mascota.

import type { ColorPalette } from "@/types/templates/config-schema";

export const petsModernPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. NARANJA MASCOTA — The original pets-modern default (config.ts verbatim)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "naranja-mascota",
    name: "Naranja Mascota",
    description: "El clasico naranja pet shop — calido, amigable y confiable",
    style: "warm",
    preview: ["#FF7322", "#FFFFFF", "#1D1D1B", "#F2F3F2", "#6DC298"],
    colors: {
      primary: "#FF7322",
      secondary: "#1D1D1B",
      background: "#FFFFFF",
      textPrimary: "#181725",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#E2E2E2",
      surface: "#F2F3F2",
      searchBg: "#F2F3F2",
      textMuted: "#7C7C7C",
      textFooter: "#999999",
      buttonBg: "#1D1D1B",
      buttonText: "#FFFFFF",
      footerBg: "#1D1D1B",
      badgeBg: "#FF7322",
      badgeText: "#FFFFFF",
      navBorder: "#F2F3F2",
      textSecondary: "#3E423F",
      textSubtle: "#545454",
      borderLight: "#F2F3F2",
      borderInput: "#E2E2E2",
      borderMid: "#E2E2E2",
      ratingStar: "#FF7322",
      ratingBarBg: "#E2E2E2",
      promoBannerFrom: "#6DC298",
      promoBannerTo: "#23BDA8",
      promoBannerText: "#030303",
      promoBannerSubtext: "#FFFFFF",
      tabActive: "#FF7322",
      categoryActiveBg: "#FF7322",
      categoryActiveText: "#181725",
      specBadgeBg: "#F2F3F2",
      reviewBg: "#FAFAFA",
      paginationBg: "#F2F3F2",
      textSummerSale: "#7C7C7C",
      textBreadcrumb: "#7C7C7C",
      popularBg0: "#F2F3F2",
      popularBg1: "#E8E9E8",
      popularBg2: "#CDCECD",
      popularBg3: "#9A9B9A",
      popularText0: "#1D1D1B",
      popularText1: "#1D1D1B",
      popularText2: "#1D1D1B",
      popularText3: "#FFFFFF",
      filterActiveBg: "#FF7322",
      filterActiveBorder: "#FF7322",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. AZUL VETERINARIA — Professional blue, vet clinic feel
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "azul-veterinaria",
    name: "Azul Veterinaria",
    description: "Profesional y confiable — ideal para clinicas y veterinarias",
    style: "corporate",
    preview: ["#2B7AE0", "#FFFFFF", "#1A2B45", "#EEF4FB", "#3AA0D6"],
    colors: {
      primary: "#2B7AE0",
      secondary: "#1A2B45",
      background: "#FFFFFF",
      textPrimary: "#1A2B45",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#D1DEE8",
      surface: "#EEF4FB",
      searchBg: "#EEF4FB",
      textMuted: "#6B8299",
      textFooter: "#8BA3B8",
      buttonBg: "#1A2B45",
      buttonText: "#FFFFFF",
      footerBg: "#1A2B45",
      badgeBg: "#2B7AE0",
      badgeText: "#FFFFFF",
      navBorder: "#EEF4FB",
      textSecondary: "#3D5A73",
      textSubtle: "#4A6680",
      borderLight: "#EEF4FB",
      borderInput: "#D1DEE8",
      borderMid: "#D1DEE8",
      ratingStar: "#FFB547",
      ratingBarBg: "#D1DEE8",
      promoBannerFrom: "#2B7AE0",
      promoBannerTo: "#3AA0D6",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#E0EFFF",
      tabActive: "#2B7AE0",
      categoryActiveBg: "#2B7AE0",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#EEF4FB",
      reviewBg: "#F8FAFE",
      paginationBg: "#EEF4FB",
      textSummerSale: "#6B8299",
      textBreadcrumb: "#6B8299",
      popularBg0: "#EEF4FB",
      popularBg1: "#DCE8F5",
      popularBg2: "#B8CEE5",
      popularBg3: "#7AA3C8",
      popularText0: "#1A2B45",
      popularText1: "#1A2B45",
      popularText2: "#1A2B45",
      popularText3: "#FFFFFF",
      filterActiveBg: "#2B7AE0",
      filterActiveBorder: "#2B7AE0",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. VERDE NATURAL — Organic green, natural pet food stores
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "verde-natural",
    name: "Verde Natural",
    description: "Organico y natural — perfecto para productos ecologicos",
    style: "nature",
    preview: ["#4CAF50", "#FAFDF7", "#2E3B2F", "#EFF5EE", "#7BC67E"],
    colors: {
      primary: "#4CAF50",
      secondary: "#2E3B2F",
      background: "#FAFDF7",
      textPrimary: "#2E3B2F",
      headerBg: "#FAFDF7",
      sectionBg: "#FAFDF7",
      cardBg: "#FFFFFF",
      border: "#C5DBC6",
      surface: "#EFF5EE",
      searchBg: "#EFF5EE",
      textMuted: "#6A8B6C",
      textFooter: "#8BAB8D",
      buttonBg: "#2E3B2F",
      buttonText: "#FFFFFF",
      footerBg: "#2E3B2F",
      badgeBg: "#4CAF50",
      badgeText: "#FFFFFF",
      navBorder: "#EFF5EE",
      textSecondary: "#4A6B4C",
      textSubtle: "#557557",
      borderLight: "#EFF5EE",
      borderInput: "#C5DBC6",
      borderMid: "#C5DBC6",
      ratingStar: "#FFB547",
      ratingBarBg: "#C5DBC6",
      promoBannerFrom: "#4CAF50",
      promoBannerTo: "#81C784",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#E8F5E9",
      tabActive: "#4CAF50",
      categoryActiveBg: "#4CAF50",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#EFF5EE",
      reviewBg: "#F5FAF4",
      paginationBg: "#EFF5EE",
      textSummerSale: "#6A8B6C",
      textBreadcrumb: "#6A8B6C",
      popularBg0: "#EFF5EE",
      popularBg1: "#DCE8DC",
      popularBg2: "#B8D4B8",
      popularBg3: "#7AB07C",
      popularText0: "#2E3B2F",
      popularText1: "#2E3B2F",
      popularText2: "#2E3B2F",
      popularText3: "#FFFFFF",
      filterActiveBg: "#4CAF50",
      filterActiveBorder: "#4CAF50",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. ROSA TIERNO — Soft pink, cute pet boutiques
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "rosa-tierno",
    name: "Rosa Tierno",
    description: "Dulce y jugueton — ideal para boutiques y accesorios de mascotas",
    style: "playful",
    preview: ["#E91E8C", "#FFF5FA", "#3D2036", "#FDE8F3", "#F06CB5"],
    colors: {
      primary: "#E91E8C",
      secondary: "#3D2036",
      background: "#FFF5FA",
      textPrimary: "#3D2036",
      headerBg: "#FFF5FA",
      sectionBg: "#FFF5FA",
      cardBg: "#FFFFFF",
      border: "#F0C4DB",
      surface: "#FDE8F3",
      searchBg: "#FDE8F3",
      textMuted: "#9A6B86",
      textFooter: "#B088A0",
      buttonBg: "#3D2036",
      buttonText: "#FFFFFF",
      footerBg: "#3D2036",
      badgeBg: "#E91E8C",
      badgeText: "#FFFFFF",
      navBorder: "#FDE8F3",
      textSecondary: "#6B3D5C",
      textSubtle: "#7A4F6A",
      borderLight: "#FDE8F3",
      borderInput: "#F0C4DB",
      borderMid: "#F0C4DB",
      ratingStar: "#FFB547",
      ratingBarBg: "#F0C4DB",
      promoBannerFrom: "#E91E8C",
      promoBannerTo: "#F06CB5",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#FFE0F0",
      tabActive: "#E91E8C",
      categoryActiveBg: "#E91E8C",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#FDE8F3",
      reviewBg: "#FFF5FA",
      paginationBg: "#FDE8F3",
      textSummerSale: "#9A6B86",
      textBreadcrumb: "#9A6B86",
      popularBg0: "#FDE8F3",
      popularBg1: "#F5D0E5",
      popularBg2: "#E8A8CD",
      popularBg3: "#C470A0",
      popularText0: "#3D2036",
      popularText1: "#3D2036",
      popularText2: "#3D2036",
      popularText3: "#FFFFFF",
      filterActiveBg: "#E91E8C",
      filterActiveBorder: "#E91E8C",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. NOCHE PREMIUM — Dark luxury, premium pet brands (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "noche-premium",
    name: "Noche Premium",
    description: "Oscuro y elegante — para tiendas premium de mascotas",
    style: "premium",
    preview: ["#D4A853", "#141414", "#D4A853", "#1E1E1E", "#2C2C2C"],
    colors: {
      primary: "#D4A853",
      secondary: "#D4A853",
      background: "#141414",
      textPrimary: "#E8E0D0",
      headerBg: "#1A1A1A",
      sectionBg: "#1A1A1A",
      cardBg: "#1E1E1E",
      border: "#3A3A3A",
      surface: "#2C2C2C",
      searchBg: "#2C2C2C",
      textMuted: "#9A9080",
      textFooter: "#807868",
      buttonBg: "#D4A853",
      buttonText: "#141414",
      footerBg: "#0E0E0E",
      badgeBg: "#D4A853",
      badgeText: "#141414",
      navBorder: "#2C2C2C",
      textSecondary: "#C0B49A",
      textSubtle: "#A89878",
      borderLight: "#2C2C2C",
      borderInput: "#3A3A3A",
      borderMid: "#3A3A3A",
      ratingStar: "#D4A853",
      ratingBarBg: "#3A3A3A",
      promoBannerFrom: "#D4A853",
      promoBannerTo: "#B8922E",
      promoBannerText: "#141414",
      promoBannerSubtext: "#2C2520",
      tabActive: "#D4A853",
      categoryActiveBg: "#D4A853",
      categoryActiveText: "#141414",
      specBadgeBg: "#2C2C2C",
      reviewBg: "#1A1A1A",
      paginationBg: "#2C2C2C",
      textSummerSale: "#9A9080",
      textBreadcrumb: "#9A9080",
      popularBg0: "#3A3A3A",
      popularBg1: "#2E2E2E",
      popularBg2: "#222222",
      popularBg3: "#1A1A1A",
      popularText0: "#E8E0D0",
      popularText1: "#E8E0D0",
      popularText2: "#E8E0D0",
      popularText3: "#E8E0D0",
      filterActiveBg: "#D4A853",
      filterActiveBorder: "#D4A853",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. ARENA DESIERTO — Sandy warm neutrals, earthy
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "arena-desierto",
    name: "Arena Desierto",
    description: "Tonos arena calidos y neutros — acogedor y terroso",
    style: "warm",
    preview: ["#C8956C", "#FBF7F2", "#3D2E1F", "#F0E8DE", "#D4A87A"],
    colors: {
      primary: "#C8956C",
      secondary: "#3D2E1F",
      background: "#FBF7F2",
      textPrimary: "#3D2E1F",
      headerBg: "#FBF7F2",
      sectionBg: "#FBF7F2",
      cardBg: "#FFFFFF",
      border: "#DDD0C0",
      surface: "#F0E8DE",
      searchBg: "#F0E8DE",
      textMuted: "#8C7A66",
      textFooter: "#A69480",
      buttonBg: "#3D2E1F",
      buttonText: "#FFFFFF",
      footerBg: "#3D2E1F",
      badgeBg: "#C8956C",
      badgeText: "#FFFFFF",
      navBorder: "#F0E8DE",
      textSecondary: "#5C4A38",
      textSubtle: "#6E5D4B",
      borderLight: "#F0E8DE",
      borderInput: "#DDD0C0",
      borderMid: "#DDD0C0",
      ratingStar: "#E8A94D",
      ratingBarBg: "#DDD0C0",
      promoBannerFrom: "#C8956C",
      promoBannerTo: "#D4A87A",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#FFF3E6",
      tabActive: "#C8956C",
      categoryActiveBg: "#C8956C",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F0E8DE",
      reviewBg: "#FAF6F0",
      paginationBg: "#F0E8DE",
      textSummerSale: "#8C7A66",
      textBreadcrumb: "#8C7A66",
      popularBg0: "#F0E8DE",
      popularBg1: "#E4D8C8",
      popularBg2: "#CCBCA8",
      popularBg3: "#A69480",
      popularText0: "#3D2E1F",
      popularText1: "#3D2E1F",
      popularText2: "#3D2E1F",
      popularText3: "#FFFFFF",
      filterActiveBg: "#C8956C",
      filterActiveBorder: "#C8956C",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 7. OCEANO TROPICAL — Teal/coral, tropical fish stores
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "oceano-tropical",
    name: "Oceano Tropical",
    description: "Turquesa y coral — vibrante para tiendas de peces y acuarios",
    style: "tropical",
    preview: ["#00897B", "#F5FFFE", "#1A3A36", "#E0F5F2", "#FF7043"],
    colors: {
      primary: "#00897B",
      secondary: "#1A3A36",
      background: "#F5FFFE",
      textPrimary: "#1A3A36",
      headerBg: "#F5FFFE",
      sectionBg: "#F5FFFE",
      cardBg: "#FFFFFF",
      border: "#B8DAD5",
      surface: "#E0F5F2",
      searchBg: "#E0F5F2",
      textMuted: "#5E8A84",
      textFooter: "#7BA8A2",
      buttonBg: "#1A3A36",
      buttonText: "#FFFFFF",
      footerBg: "#1A3A36",
      badgeBg: "#FF7043",
      badgeText: "#FFFFFF",
      navBorder: "#E0F5F2",
      textSecondary: "#2E5C56",
      textSubtle: "#3E6D66",
      borderLight: "#E0F5F2",
      borderInput: "#B8DAD5",
      borderMid: "#B8DAD5",
      ratingStar: "#FFB547",
      ratingBarBg: "#B8DAD5",
      promoBannerFrom: "#00897B",
      promoBannerTo: "#FF7043",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#E0FFF8",
      tabActive: "#00897B",
      categoryActiveBg: "#00897B",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#E0F5F2",
      reviewBg: "#F0FAF8",
      paginationBg: "#E0F5F2",
      textSummerSale: "#5E8A84",
      textBreadcrumb: "#5E8A84",
      popularBg0: "#E0F5F2",
      popularBg1: "#C8E8E3",
      popularBg2: "#A0D4CC",
      popularBg3: "#6AAEA4",
      popularText0: "#1A3A36",
      popularText1: "#1A3A36",
      popularText2: "#1A3A36",
      popularText3: "#FFFFFF",
      filterActiveBg: "#00897B",
      filterActiveBorder: "#00897B",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 8. LAVANDA SUAVE — Soft purple, calming, grooming spas
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "lavanda-suave",
    name: "Lavanda Suave",
    description: "Purpura suave y calmante — perfecto para spas y grooming",
    style: "minimal",
    preview: ["#7E57C2", "#FAF8FF", "#2D1F4E", "#EDE7F6", "#B39DDB"],
    colors: {
      primary: "#7E57C2",
      secondary: "#2D1F4E",
      background: "#FAF8FF",
      textPrimary: "#2D1F4E",
      headerBg: "#FAF8FF",
      sectionBg: "#FAF8FF",
      cardBg: "#FFFFFF",
      border: "#D1C4E9",
      surface: "#EDE7F6",
      searchBg: "#EDE7F6",
      textMuted: "#7E6BA5",
      textFooter: "#9B8CC0",
      buttonBg: "#2D1F4E",
      buttonText: "#FFFFFF",
      footerBg: "#2D1F4E",
      badgeBg: "#7E57C2",
      badgeText: "#FFFFFF",
      navBorder: "#EDE7F6",
      textSecondary: "#4A3670",
      textSubtle: "#5C4888",
      borderLight: "#EDE7F6",
      borderInput: "#D1C4E9",
      borderMid: "#D1C4E9",
      ratingStar: "#FFB547",
      ratingBarBg: "#D1C4E9",
      promoBannerFrom: "#7E57C2",
      promoBannerTo: "#B39DDB",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#EDE0FF",
      tabActive: "#7E57C2",
      categoryActiveBg: "#7E57C2",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#EDE7F6",
      reviewBg: "#F8F5FF",
      paginationBg: "#EDE7F6",
      textSummerSale: "#7E6BA5",
      textBreadcrumb: "#7E6BA5",
      popularBg0: "#EDE7F6",
      popularBg1: "#DDD4EE",
      popularBg2: "#C4B5DC",
      popularBg3: "#9A87BE",
      popularText0: "#2D1F4E",
      popularText1: "#2D1F4E",
      popularText2: "#2D1F4E",
      popularText3: "#FFFFFF",
      filterActiveBg: "#7E57C2",
      filterActiveBorder: "#7E57C2",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 9. BOSQUE PROFUNDO — Deep forest green (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "bosque-profundo",
    name: "Bosque Profundo",
    description: "Verde bosque oscuro — naturaleza premium y exclusiva",
    style: "nature",
    preview: ["#66BB6A", "#0D1A0F", "#66BB6A", "#1A2E1C", "#2A4A2E"],
    colors: {
      primary: "#66BB6A",
      secondary: "#66BB6A",
      background: "#0D1A0F",
      textPrimary: "#D8ECD9",
      headerBg: "#122016",
      sectionBg: "#122016",
      cardBg: "#1A2E1C",
      border: "#2E4A32",
      surface: "#2A4A2E",
      searchBg: "#1E3820",
      textMuted: "#8AAE8C",
      textFooter: "#6E926F",
      buttonBg: "#66BB6A",
      buttonText: "#0D1A0F",
      footerBg: "#081008",
      badgeBg: "#66BB6A",
      badgeText: "#0D1A0F",
      navBorder: "#2A4A2E",
      textSecondary: "#B0D4B2",
      textSubtle: "#98C49A",
      borderLight: "#1E3820",
      borderInput: "#2E4A32",
      borderMid: "#2E4A32",
      ratingStar: "#A5D6A7",
      ratingBarBg: "#2E4A32",
      promoBannerFrom: "#66BB6A",
      promoBannerTo: "#388E3C",
      promoBannerText: "#0D1A0F",
      promoBannerSubtext: "#1A2E1C",
      tabActive: "#66BB6A",
      categoryActiveBg: "#66BB6A",
      categoryActiveText: "#0D1A0F",
      specBadgeBg: "#2A4A2E",
      reviewBg: "#122016",
      paginationBg: "#2A4A2E",
      textSummerSale: "#8AAE8C",
      textBreadcrumb: "#8AAE8C",
      popularBg0: "#2E5032",
      popularBg1: "#264428",
      popularBg2: "#1C3620",
      popularBg3: "#142618",
      popularText0: "#D8ECD9",
      popularText1: "#D8ECD9",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#66BB6A",
      filterActiveBorder: "#66BB6A",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 10. CORAL VIBRANTE — Vibrant coral/peach, energetic
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "coral-vibrante",
    name: "Coral Vibrante",
    description: "Coral energico y vibrante — para tiendas con personalidad",
    style: "vibrant",
    preview: ["#FF6B6B", "#FFFAF8", "#3A1F1F", "#FFE8E4", "#FF9A8B"],
    colors: {
      primary: "#FF6B6B",
      secondary: "#3A1F1F",
      background: "#FFFAF8",
      textPrimary: "#3A1F1F",
      headerBg: "#FFFAF8",
      sectionBg: "#FFFAF8",
      cardBg: "#FFFFFF",
      border: "#F0CECA",
      surface: "#FFE8E4",
      searchBg: "#FFE8E4",
      textMuted: "#946262",
      textFooter: "#B08080",
      buttonBg: "#3A1F1F",
      buttonText: "#FFFFFF",
      footerBg: "#3A1F1F",
      badgeBg: "#FF6B6B",
      badgeText: "#FFFFFF",
      navBorder: "#FFE8E4",
      textSecondary: "#5E3434",
      textSubtle: "#724646",
      borderLight: "#FFE8E4",
      borderInput: "#F0CECA",
      borderMid: "#F0CECA",
      ratingStar: "#FFB547",
      ratingBarBg: "#F0CECA",
      promoBannerFrom: "#FF6B6B",
      promoBannerTo: "#FF9A8B",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#FFE0DB",
      tabActive: "#FF6B6B",
      categoryActiveBg: "#FF6B6B",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#FFE8E4",
      reviewBg: "#FFF5F3",
      paginationBg: "#FFE8E4",
      textSummerSale: "#946262",
      textBreadcrumb: "#946262",
      popularBg0: "#FFE8E4",
      popularBg1: "#F8D0CA",
      popularBg2: "#E8AAA0",
      popularBg3: "#C87872",
      popularText0: "#3A1F1F",
      popularText1: "#3A1F1F",
      popularText2: "#3A1F1F",
      popularText3: "#FFFFFF",
      filterActiveBg: "#FF6B6B",
      filterActiveBorder: "#FF6B6B",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 11. GRIS MODERNO — Monochrome gray, modern minimalist
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "gris-moderno",
    name: "Gris Moderno",
    description: "Minimalismo monocromatico — moderno y sofisticado",
    style: "monochrome",
    preview: ["#424242", "#FAFAFA", "#212121", "#F0F0F0", "#757575"],
    colors: {
      primary: "#424242",
      secondary: "#212121",
      background: "#FAFAFA",
      textPrimary: "#212121",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#D0D0D0",
      surface: "#F0F0F0",
      searchBg: "#F0F0F0",
      textMuted: "#757575",
      textFooter: "#9E9E9E",
      buttonBg: "#212121",
      buttonText: "#FFFFFF",
      footerBg: "#212121",
      badgeBg: "#424242",
      badgeText: "#FFFFFF",
      navBorder: "#F0F0F0",
      textSecondary: "#4A4A4A",
      textSubtle: "#5A5A5A",
      borderLight: "#F0F0F0",
      borderInput: "#D0D0D0",
      borderMid: "#D0D0D0",
      ratingStar: "#FFB547",
      ratingBarBg: "#D0D0D0",
      promoBannerFrom: "#424242",
      promoBannerTo: "#616161",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#E0E0E0",
      tabActive: "#212121",
      categoryActiveBg: "#212121",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F0F0F0",
      reviewBg: "#F7F7F7",
      paginationBg: "#F0F0F0",
      textSummerSale: "#757575",
      textBreadcrumb: "#757575",
      popularBg0: "#F0F0F0",
      popularBg1: "#E2E2E2",
      popularBg2: "#C8C8C8",
      popularBg3: "#9A9A9A",
      popularText0: "#212121",
      popularText1: "#212121",
      popularText2: "#212121",
      popularText3: "#FFFFFF",
      filterActiveBg: "#424242",
      filterActiveBorder: "#424242",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 12. TURQUESA FRESCO — Fresh turquoise, clean veterinary
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "turquesa-fresco",
    name: "Turquesa Fresco",
    description: "Turquesa limpio y fresco — clinico y confiable",
    style: "minimal",
    preview: ["#00ACC1", "#F5FDFE", "#153740", "#E0F7FA", "#4DD0E1"],
    colors: {
      primary: "#00ACC1",
      secondary: "#153740",
      background: "#F5FDFE",
      textPrimary: "#153740",
      headerBg: "#F5FDFE",
      sectionBg: "#F5FDFE",
      cardBg: "#FFFFFF",
      border: "#B2E5EC",
      surface: "#E0F7FA",
      searchBg: "#E0F7FA",
      textMuted: "#5A8A94",
      textFooter: "#78A8B2",
      buttonBg: "#153740",
      buttonText: "#FFFFFF",
      footerBg: "#153740",
      badgeBg: "#00ACC1",
      badgeText: "#FFFFFF",
      navBorder: "#E0F7FA",
      textSecondary: "#2A5560",
      textSubtle: "#3A6872",
      borderLight: "#E0F7FA",
      borderInput: "#B2E5EC",
      borderMid: "#B2E5EC",
      ratingStar: "#FFB547",
      ratingBarBg: "#B2E5EC",
      promoBannerFrom: "#00ACC1",
      promoBannerTo: "#4DD0E1",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#E0F8FF",
      tabActive: "#00ACC1",
      categoryActiveBg: "#00ACC1",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#E0F7FA",
      reviewBg: "#F0FCFE",
      paginationBg: "#E0F7FA",
      textSummerSale: "#5A8A94",
      textBreadcrumb: "#5A8A94",
      popularBg0: "#E0F7FA",
      popularBg1: "#C4ECF2",
      popularBg2: "#98D8E4",
      popularBg3: "#5CBAC8",
      popularText0: "#153740",
      popularText1: "#153740",
      popularText2: "#153740",
      popularText3: "#FFFFFF",
      filterActiveBg: "#00ACC1",
      filterActiveBorder: "#00ACC1",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 13. TERRACOTA RUSTICO — Earthy terracotta, rustic pet shops
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "terracota-rustico",
    name: "Terracota Rustico",
    description: "Terracota terroso y rustico — calidez artesanal para mascotas",
    style: "warm",
    preview: ["#BF5B3A", "#FDF6F2", "#3C2218", "#F0DFD4", "#D98860"],
    colors: {
      primary: "#BF5B3A",
      secondary: "#3C2218",
      background: "#FDF6F2",
      textPrimary: "#3C2218",
      headerBg: "#FDF6F2",
      sectionBg: "#FDF6F2",
      cardBg: "#FFFFFF",
      border: "#DCC4B4",
      surface: "#F0DFD4",
      searchBg: "#F0DFD4",
      textMuted: "#8A6A58",
      textFooter: "#A68878",
      buttonBg: "#3C2218",
      buttonText: "#FFFFFF",
      footerBg: "#3C2218",
      badgeBg: "#BF5B3A",
      badgeText: "#FFFFFF",
      navBorder: "#F0DFD4",
      textSecondary: "#5A3828",
      textSubtle: "#6E4A38",
      borderLight: "#F0DFD4",
      borderInput: "#DCC4B4",
      borderMid: "#DCC4B4",
      ratingStar: "#E8A94D",
      ratingBarBg: "#DCC4B4",
      promoBannerFrom: "#BF5B3A",
      promoBannerTo: "#D98860",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#FFEBD8",
      tabActive: "#BF5B3A",
      categoryActiveBg: "#BF5B3A",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F0DFD4",
      reviewBg: "#FAF2EC",
      paginationBg: "#F0DFD4",
      textSummerSale: "#8A6A58",
      textBreadcrumb: "#8A6A58",
      popularBg0: "#F0DFD4",
      popularBg1: "#E2CCBC",
      popularBg2: "#CCA88E",
      popularBg3: "#A67A5E",
      popularText0: "#3C2218",
      popularText1: "#3C2218",
      popularText2: "#3C2218",
      popularText3: "#FFFFFF",
      filterActiveBg: "#BF5B3A",
      filterActiveBorder: "#BF5B3A",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 14. NEON MASCOTA — Cyberpunk neon for exotic pet stores (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "neon-mascota",
    name: "Neon Mascota",
    description: "Neon cyberpunk — audaz para tiendas de mascotas exoticas",
    style: "cyberpunk",
    preview: ["#00E5FF", "#0A0E14", "#FF2D95", "#161C24", "#1E2830"],
    colors: {
      primary: "#00E5FF",
      secondary: "#FF2D95",
      background: "#0A0E14",
      textPrimary: "#E0E8F0",
      headerBg: "#0E1218",
      sectionBg: "#0E1218",
      cardBg: "#161C24",
      border: "#283040",
      surface: "#1E2830",
      searchBg: "#161C24",
      textMuted: "#708090",
      textFooter: "#5A6A7A",
      buttonBg: "#00E5FF",
      buttonText: "#0A0E14",
      footerBg: "#060A0E",
      badgeBg: "#FF2D95",
      badgeText: "#FFFFFF",
      navBorder: "#1E2830",
      textSecondary: "#A0B0C0",
      textSubtle: "#8898A8",
      borderLight: "#1E2830",
      borderInput: "#283040",
      borderMid: "#283040",
      ratingStar: "#00E5FF",
      ratingBarBg: "#283040",
      promoBannerFrom: "#00E5FF",
      promoBannerTo: "#FF2D95",
      promoBannerText: "#0A0E14",
      promoBannerSubtext: "#161C24",
      tabActive: "#00E5FF",
      categoryActiveBg: "#00E5FF",
      categoryActiveText: "#0A0E14",
      specBadgeBg: "#1E2830",
      reviewBg: "#0E1218",
      paginationBg: "#1E2830",
      textSummerSale: "#708090",
      textBreadcrumb: "#708090",
      popularBg0: "#283848",
      popularBg1: "#1E2E3C",
      popularBg2: "#162430",
      popularBg3: "#0E1820",
      popularText0: "#E0E8F0",
      popularText1: "#E0E8F0",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
      filterActiveBg: "#00E5FF",
      filterActiveBorder: "#00E5FF",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 15. CREMA ELEGANTE — Cream/beige, elegant pet boutique
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "crema-elegante",
    name: "Crema Elegante",
    description: "Crema y beige sofisticado — elegancia sutil para boutiques",
    style: "minimal",
    preview: ["#8B7355", "#FDF9F4", "#3A3020", "#F0E8DA", "#BBA882"],
    colors: {
      primary: "#8B7355",
      secondary: "#3A3020",
      background: "#FDF9F4",
      textPrimary: "#3A3020",
      headerBg: "#FDF9F4",
      sectionBg: "#FDF9F4",
      cardBg: "#FFFFFF",
      border: "#DDD2BE",
      surface: "#F0E8DA",
      searchBg: "#F0E8DA",
      textMuted: "#867460",
      textFooter: "#A09280",
      buttonBg: "#3A3020",
      buttonText: "#FFFFFF",
      footerBg: "#3A3020",
      badgeBg: "#8B7355",
      badgeText: "#FFFFFF",
      navBorder: "#F0E8DA",
      textSecondary: "#5A4E3A",
      textSubtle: "#6C5E48",
      borderLight: "#F0E8DA",
      borderInput: "#DDD2BE",
      borderMid: "#DDD2BE",
      ratingStar: "#D4A84B",
      ratingBarBg: "#DDD2BE",
      promoBannerFrom: "#8B7355",
      promoBannerTo: "#BBA882",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#F5EDE0",
      tabActive: "#8B7355",
      categoryActiveBg: "#8B7355",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#F0E8DA",
      reviewBg: "#FAF6EE",
      paginationBg: "#F0E8DA",
      textSummerSale: "#867460",
      textBreadcrumb: "#867460",
      popularBg0: "#F0E8DA",
      popularBg1: "#E2D6C2",
      popularBg2: "#CCBCA2",
      popularBg3: "#A69278",
      popularText0: "#3A3020",
      popularText1: "#3A3020",
      popularText2: "#3A3020",
      popularText3: "#FFFFFF",
      filterActiveBg: "#8B7355",
      filterActiveBorder: "#8B7355",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 16. ROJO ENERGIA — Bold red, high-energy pet accessories
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "rojo-energia",
    name: "Rojo Energia",
    description: "Rojo audaz y energico — para accesorios y productos activos",
    style: "vibrant",
    preview: ["#E53935", "#FFFAFA", "#2D1414", "#FFE5E4", "#EF5350"],
    colors: {
      primary: "#E53935",
      secondary: "#2D1414",
      background: "#FFFAFA",
      textPrimary: "#2D1414",
      headerBg: "#FFFAFA",
      sectionBg: "#FFFAFA",
      cardBg: "#FFFFFF",
      border: "#E8C4C4",
      surface: "#FFE5E4",
      searchBg: "#FFE5E4",
      textMuted: "#8A5252",
      textFooter: "#A87070",
      buttonBg: "#2D1414",
      buttonText: "#FFFFFF",
      footerBg: "#2D1414",
      badgeBg: "#E53935",
      badgeText: "#FFFFFF",
      navBorder: "#FFE5E4",
      textSecondary: "#4E2424",
      textSubtle: "#623636",
      borderLight: "#FFE5E4",
      borderInput: "#E8C4C4",
      borderMid: "#E8C4C4",
      ratingStar: "#FFB547",
      ratingBarBg: "#E8C4C4",
      promoBannerFrom: "#E53935",
      promoBannerTo: "#EF5350",
      promoBannerText: "#FFFFFF",
      promoBannerSubtext: "#FFD4D3",
      tabActive: "#E53935",
      categoryActiveBg: "#E53935",
      categoryActiveText: "#FFFFFF",
      specBadgeBg: "#FFE5E4",
      reviewBg: "#FFF5F5",
      paginationBg: "#FFE5E4",
      textSummerSale: "#8A5252",
      textBreadcrumb: "#8A5252",
      popularBg0: "#FFE5E4",
      popularBg1: "#F4CCCB",
      popularBg2: "#E0A2A0",
      popularBg3: "#C07070",
      popularText0: "#2D1414",
      popularText1: "#2D1414",
      popularText2: "#2D1414",
      popularText3: "#FFFFFF",
      filterActiveBg: "#E53935",
      filterActiveBorder: "#E53935",
      whatsappBg: "#25D366",
      whatsappText: "#FFFFFF",
    },
  },
];
