// Beauty Soft — Color Palettes
// 1 default palette stub. Palette #1 matches config.ts defaults exactly.
// Additional palettes can be added following the palette-designer skill.

import type { ColorPalette } from "@/types/templates/config-schema";

export const beautySoftPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. GLOW — The original beauty-soft default (coral accent on soft gray)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "glow",
    name: "Glow",
    description: "Coral cálido sobre gris suave — belleza fresca y accesible",
    style: "warm",
    preview: ["#FF4428", "#F4F4F7", "#FFFFFF", "#000000", "#9DA2A6"],
    colors: {
      primary: "#FF4428",
      secondary: "#F5F4F7",
      background: "#F4F4F7",
      textPrimary: "#000000",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F4F4F7",
      border: "#E5E5EE",
      surface: "#D8D5D0",
      searchBg: "#F4F4F7",
      textMuted: "#9DA2A6",
      textFooter: "#B1B0B0",
      buttonBg: "#FF4428",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#FF4428",
      badgeText: "#FFFFFF",
      navBorder: "#E5E5EE",
      textSecondary: "#8A8A8A",
      textSubtle: "#949494",
      borderLight: "#E5E5EE",
      borderInput: "#E5E5EE",
      borderMid: "#B1B0B0",
      ratingStar: "#F97316",
      ratingBarBg: "#E5E5EE",
      paginationBg: "#F4F4F7",
      textBreadcrumb: "#9DA2A6",
      tabActive: "#FF4428",
      categoryActiveBg: "#FF4428",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#F6F5F5",
      discountBg: "#DBDADD",
      discountText: "#FFFFFF",
      popularBg0: "#F6F6F6",
      popularBg1: "#EAEAEA",
      popularBg2: "#CDCDCD",
      popularBg3: "#9A9A9A",
      popularText0: "#000000",
      popularText1: "#000000",
      popularText2: "#000000",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. ROSE BLUSH — Soft pink feminine
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "rose-blush",
    name: "Rosa Blush",
    description: "Rosa suave con acentos vibrantes — femenino y elegante",
    style: "playful",
    preview: ["#E91E8C", "#FDF2F8", "#FFFFFF", "#1A1A1A", "#D1A0B8"],
    colors: {
      primary: "#E91E8C",
      secondary: "#FCE4EC",
      background: "#FDF2F8",
      textPrimary: "#1A1A1A",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FDF2F8",
      border: "#F8BBD9",
      surface: "#E8B4CC",
      searchBg: "#FDF2F8",
      textMuted: "#AD7C9A",
      textFooter: "#C4A0B4",
      buttonBg: "#E91E8C",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#E91E8C",
      badgeText: "#FFFFFF",
      navBorder: "#F8BBD9",
      textSecondary: "#8D6073",
      textSubtle: "#A07085",
      borderLight: "#F8BBD9",
      borderInput: "#F4B8D0",
      borderMid: "#D4A0B8",
      ratingStar: "#F97316",
      ratingBarBg: "#F8BBD9",
      paginationBg: "#FDF2F8",
      textBreadcrumb: "#AD7C9A",
      tabActive: "#E91E8C",
      categoryActiveBg: "#E91E8C",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#FEF0F7",
      discountBg: "#F8BBD9",
      discountText: "#E91E8C",
      popularBg0: "#FEF0F7",
      popularBg1: "#FBD9EE",
      popularBg2: "#F4B0D5",
      popularBg3: "#E888B8",
      popularText0: "#1A1A1A",
      popularText1: "#1A1A1A",
      popularText2: "#1A1A1A",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. LAVENDER CALM — Soft purple wellness vibe
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "lavender-calm",
    name: "Lavanda Serena",
    description: "Lavanda calmante con tonos suaves — ideal para spa y bienestar",
    style: "minimal",
    preview: ["#7C3AED", "#F5F3FF", "#FFFFFF", "#1A1A2E", "#A78BCA"],
    colors: {
      primary: "#7C3AED",
      secondary: "#EDE9FE",
      background: "#F5F3FF",
      textPrimary: "#1A1A2E",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F5F3FF",
      border: "#DDD6FE",
      surface: "#C4B5FD",
      searchBg: "#F5F3FF",
      textMuted: "#7C6A99",
      textFooter: "#A78BCA",
      buttonBg: "#7C3AED",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#7C3AED",
      badgeText: "#FFFFFF",
      navBorder: "#DDD6FE",
      textSecondary: "#6D5B8A",
      textSubtle: "#8070A0",
      borderLight: "#EDE9FE",
      borderInput: "#DDD6FE",
      borderMid: "#C4B5FD",
      ratingStar: "#F97316",
      ratingBarBg: "#DDD6FE",
      paginationBg: "#F5F3FF",
      textBreadcrumb: "#7C6A99",
      tabActive: "#7C3AED",
      categoryActiveBg: "#7C3AED",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#F0EBFF",
      discountBg: "#DDD6FE",
      discountText: "#7C3AED",
      popularBg0: "#F0EBFF",
      popularBg1: "#E5DEFF",
      popularBg2: "#C9BEFA",
      popularBg3: "#A590EC",
      popularText0: "#1A1A2E",
      popularText1: "#1A1A2E",
      popularText2: "#1A1A2E",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. NIGHT BEAUTY — Dark premium para líneas de lujo
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "night-beauty",
    name: "Belleza Nocturna",
    description: "Fondo oscuro con acento coral — lujo y misterio femenino",
    style: "premium",
    preview: ["#FF4428", "#0F0F0F", "#1A1A1A", "#F0EEF4", "#3A3A3A"],
    colors: {
      primary: "#FF4428",
      secondary: "#1A1A1A",
      background: "#0F0F0F",
      textPrimary: "#F0EEF4",
      headerBg: "#1A1A1A",
      sectionBg: "#1A1A1A",
      cardBg: "#242424",
      border: "#333333",
      surface: "#2E2E2E",
      searchBg: "#242424",
      textMuted: "#8A8A8A",
      textFooter: "#666666",
      buttonBg: "#FF4428",
      buttonText: "#FFFFFF",
      footerBg: "#0F0F0F",
      badgeBg: "#FF4428",
      badgeText: "#FFFFFF",
      navBorder: "#333333",
      textSecondary: "#AAAAAA",
      textSubtle: "#888888",
      borderLight: "#2E2E2E",
      borderInput: "#444444",
      borderMid: "#3D3D3D",
      ratingStar: "#F97316",
      ratingBarBg: "#333333",
      paginationBg: "#242424",
      textBreadcrumb: "#888888",
      tabActive: "#FF4428",
      categoryActiveBg: "#FF4428",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#2A2A2A",
      discountBg: "#2E2E2E",
      discountText: "#FF4428",
      popularBg0: "#3A3A3A",
      popularBg1: "#2E2E2E",
      popularBg2: "#242424",
      popularBg3: "#1A1A1A",
      popularText0: "#F0EEF4",
      popularText1: "#F0EEF4",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. PEACH GLOW — Durazno cálido y amigable
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "peach-glow",
    name: "Durazno Glow",
    description: "Tonos durazno cálidos — tierno, accesible y femenino",
    style: "warm",
    preview: ["#FF6B35", "#FFF4EE", "#FFFFFF", "#2D1B0E", "#E8A080"],
    colors: {
      primary: "#FF6B35",
      secondary: "#FFE4D4",
      background: "#FFF4EE",
      textPrimary: "#2D1B0E",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFF4EE",
      border: "#FFD4B8",
      surface: "#F0B090",
      searchBg: "#FFF4EE",
      textMuted: "#A06040",
      textFooter: "#C49070",
      buttonBg: "#FF6B35",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#FF6B35",
      badgeText: "#FFFFFF",
      navBorder: "#FFD4B8",
      textSecondary: "#8A5030",
      textSubtle: "#A06040",
      borderLight: "#FFE4D4",
      borderInput: "#FFD4B8",
      borderMid: "#F0B898",
      ratingStar: "#F97316",
      ratingBarBg: "#FFD4B8",
      paginationBg: "#FFF4EE",
      textBreadcrumb: "#A06040",
      tabActive: "#FF6B35",
      categoryActiveBg: "#FF6B35",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#FFF0E8",
      discountBg: "#FFD4B8",
      discountText: "#FF6B35",
      popularBg0: "#FFF0E8",
      popularBg1: "#FFE4D4",
      popularBg2: "#FFC8A0",
      popularBg3: "#FFA070",
      popularText0: "#2D1B0E",
      popularText1: "#2D1B0E",
      popularText2: "#2D1B0E",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. MINT FRESH — Verde menta limpio para productos naturales
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "mint-fresh",
    name: "Menta Fresca",
    description: "Verde menta refrescante — natural, orgánico y limpio",
    style: "nature",
    preview: ["#10B981", "#F0FDF4", "#FFFFFF", "#064E3B", "#6EE7B7"],
    colors: {
      primary: "#10B981",
      secondary: "#D1FAE5",
      background: "#F0FDF4",
      textPrimary: "#064E3B",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F0FDF4",
      border: "#A7F3D0",
      surface: "#6EE7B7",
      searchBg: "#F0FDF4",
      textMuted: "#059669",
      textFooter: "#34D399",
      buttonBg: "#10B981",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#10B981",
      badgeText: "#FFFFFF",
      navBorder: "#A7F3D0",
      textSecondary: "#047857",
      textSubtle: "#065F46",
      borderLight: "#D1FAE5",
      borderInput: "#A7F3D0",
      borderMid: "#6EE7B7",
      ratingStar: "#F97316",
      ratingBarBg: "#A7F3D0",
      paginationBg: "#F0FDF4",
      textBreadcrumb: "#059669",
      tabActive: "#10B981",
      categoryActiveBg: "#10B981",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#ECFDF5",
      discountBg: "#D1FAE5",
      discountText: "#10B981",
      popularBg0: "#ECFDF5",
      popularBg1: "#D1FAE5",
      popularBg2: "#A7F3D0",
      popularBg3: "#6EE7B7",
      popularText0: "#064E3B",
      popularText1: "#064E3B",
      popularText2: "#064E3B",
      popularText3: "#064E3B",
    },
  },
];
