// Beauty Soft — Color Palettes
// 16 palettes for skincare/beauty stores.
// Palette #1 matches config.ts defaults exactly.
// ~75% light, ~25% dark. All WCAG AA compliant.

import type { ColorPalette } from "@/types/templates/config-schema";

export const beautySoftPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. CORAL SUAVE — The original beauty-soft default (coral accent on soft gray)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "coral-suave",
    name: "Coral Suave",
    description: "Coral cálido sobre gris suave — belleza fresca y accesible",
    style: "warm",
    preview: ["#FF4428", "#F4F4F7", "#FFFFFF", "#000000", "#9DA2A6"],
    colors: {
      primary: "#FF4428",
      secondary: "#F5F4F7",
      background: "#F4F4F7",
      textPrimary: "#000000",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F4F4F7",
      border: "#E5E5EE",
      surface: "#D8D5D0",
      searchBg: "#F4F4F7",
      textMuted: "#9DA2A6",
      textFooter: "#B1B0B0",
      buttonBg: "#FF4428",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#FF4428",
      badgeText: "#FFFFFF",
      navBorder: "#E5E5EE",
      textSecondary: "#8A8A8A",
      textSubtle: "#949494",
      borderLight: "#E5E5EE",
      borderInput: "#E5E5EE",
      borderMid: "#B1B0B0",
      ratingStar: "#F97316",
      ratingBarBg: "#E5E5EE",
      paginationBg: "#F4F4F7",
      textBreadcrumb: "#9DA2A6",
      tabActive: "#FF4428",
      categoryActiveBg: "#FF4428",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#F6F5F5",
      discountBg: "#DBDADD",
      discountText: "#FFFFFF",
      popularBg0: "#F6F6F6",
      popularBg1: "#EAEAEA",
      popularBg2: "#CDCDCD",
      popularBg3: "#9A9A9A",
      popularText0: "#000000",
      popularText1: "#000000",
      popularText2: "#000000",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. ROSA DELICADO — Soft pink, feminine
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "rosa-delicado",
    name: "Rosa Delicado",
    description: "Rosa suave con acentos vibrantes — femenino y delicado",
    style: "playful",
    preview: ["#E91E8C", "#FDF2F8", "#FFFFFF", "#1A1A1A", "#F8BBD9"],
    colors: {
      primary: "#E91E8C",
      secondary: "#FCE4EC",
      background: "#FDF2F8",
      textPrimary: "#1A1A1A",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FDF2F8",
      border: "#F8BBD9",
      surface: "#E8B4CC",
      searchBg: "#FDF2F8",
      textMuted: "#9A607A",
      textFooter: "#C4A0B4",
      buttonBg: "#E91E8C",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#E91E8C",
      badgeText: "#FFFFFF",
      navBorder: "#F8BBD9",
      textSecondary: "#6B3050",
      textSubtle: "#A07085",
      borderLight: "#F8BBD9",
      borderInput: "#F4B8D0",
      borderMid: "#D4A0B8",
      ratingStar: "#F97316",
      ratingBarBg: "#F8BBD9",
      paginationBg: "#FDF2F8",
      textBreadcrumb: "#9A607A",
      tabActive: "#E91E8C",
      categoryActiveBg: "#E91E8C",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#FEF0F7",
      discountBg: "#F8BBD9",
      discountText: "#FFFFFF",
      popularBg0: "#FEF0F7",
      popularBg1: "#FBD9EE",
      popularBg2: "#F4B0D5",
      popularBg3: "#E888B8",
      popularText0: "#1A1A1A",
      popularText1: "#1A1A1A",
      popularText2: "#1A1A1A",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. LAVANDA SPA — Lavender, calming spa
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "lavanda-spa",
    name: "Lavanda Spa",
    description: "Lavanda calmante con tonos suaves — ideal para spa y bienestar",
    style: "minimal",
    preview: ["#7C3AED", "#F5F3FF", "#FFFFFF", "#1A1A2E", "#DDD6FE"],
    colors: {
      primary: "#7C3AED",
      secondary: "#EDE9FE",
      background: "#F5F3FF",
      textPrimary: "#1A1A2E",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F5F3FF",
      border: "#DDD6FE",
      surface: "#C4B5FD",
      searchBg: "#F5F3FF",
      textMuted: "#6B5A8A",
      textFooter: "#A78BCA",
      buttonBg: "#7C3AED",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#7C3AED",
      badgeText: "#FFFFFF",
      navBorder: "#DDD6FE",
      textSecondary: "#4D3B6E",
      textSubtle: "#7060A0",
      borderLight: "#EDE9FE",
      borderInput: "#DDD6FE",
      borderMid: "#C4B5FD",
      ratingStar: "#F97316",
      ratingBarBg: "#DDD6FE",
      paginationBg: "#F5F3FF",
      textBreadcrumb: "#6B5A8A",
      tabActive: "#7C3AED",
      categoryActiveBg: "#7C3AED",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#F0EBFF",
      discountBg: "#DDD6FE",
      discountText: "#FFFFFF",
      popularBg0: "#F0EBFF",
      popularBg1: "#E5DEFF",
      popularBg2: "#C9BEFA",
      popularBg3: "#A590EC",
      popularText0: "#1A1A2E",
      popularText1: "#1A1A2E",
      popularText2: "#1A1A2E",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. VERDE ORGANICO — Green, organic beauty
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "verde-organico",
    name: "Verde Orgánico",
    description: "Verde natural para productos orgánicos y cosméticos limpios",
    style: "nature",
    preview: ["#2D7D46", "#F0FAF3", "#FFFFFF", "#1A3320", "#A7D7B4"],
    colors: {
      primary: "#2D7D46",
      secondary: "#D1FADF",
      background: "#F0FAF3",
      textPrimary: "#1A3320",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F0FAF3",
      border: "#BBF0CB",
      surface: "#88D9A0",
      searchBg: "#F0FAF3",
      textMuted: "#4A7A58",
      textFooter: "#7AB88A",
      buttonBg: "#2D7D46",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#2D7D46",
      badgeText: "#FFFFFF",
      navBorder: "#BBF0CB",
      textSecondary: "#2A5A38",
      textSubtle: "#507A60",
      borderLight: "#D1FADF",
      borderInput: "#BBF0CB",
      borderMid: "#88D9A0",
      ratingStar: "#F97316",
      ratingBarBg: "#BBF0CB",
      paginationBg: "#F0FAF3",
      textBreadcrumb: "#4A7A58",
      tabActive: "#2D7D46",
      categoryActiveBg: "#2D7D46",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#E8F8EC",
      discountBg: "#BBF0CB",
      discountText: "#FFFFFF",
      popularBg0: "#E8F8EC",
      popularBg1: "#D1FADF",
      popularBg2: "#A8E8BC",
      popularBg3: "#6ED090",
      popularText0: "#1A3320",
      popularText1: "#1A3320",
      popularText2: "#1A3320",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. NOCHE GLAMOUR — Dark glamour, gold accents (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "noche-glamour",
    name: "Noche Glamour",
    description: "Fondo oscuro con acento dorado — lujo, misterio y glamour",
    style: "premium",
    preview: ["#D4A843", "#0F0F0F", "#1A1A1A", "#F0EEF4", "#3A3030"],
    colors: {
      primary: "#D4A843",
      secondary: "#1A1A1A",
      background: "#0F0F0F",
      textPrimary: "#F0EEF4",
      headerBg: "#1A1A1A",
      sectionBg: "#1A1A1A",
      cardBg: "#242424",
      border: "#333333",
      surface: "#2E2E2E",
      searchBg: "#242424",
      textMuted: "#9A9A9A",
      textFooter: "#707070",
      buttonBg: "#D4A843",
      buttonText: "#0F0F0F",
      footerBg: "#0F0F0F",
      badgeBg: "#D4A843",
      badgeText: "#0F0F0F",
      navBorder: "#333333",
      textSecondary: "#C8C8C8",
      textSubtle: "#AAAAAA",
      borderLight: "#2E2E2E",
      borderInput: "#444444",
      borderMid: "#3D3D3D",
      ratingStar: "#D4A843",
      ratingBarBg: "#333333",
      paginationBg: "#242424",
      textBreadcrumb: "#9A9A9A",
      tabActive: "#D4A843",
      categoryActiveBg: "#D4A843",
      categoryActiveText: "#0F0F0F",
      iconPillBg: "#2A2A2A",
      discountBg: "#2E2E2E",
      discountText: "#D4A843",
      popularBg0: "#3A3A3A",
      popularBg1: "#2E2E2E",
      popularBg2: "#242424",
      popularBg3: "#1A1A1A",
      popularText0: "#F0EEF4",
      popularText1: "#F0EEF4",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. NUDE NATURAL — Nude/beige natural tones
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "nude-natural",
    name: "Nude Natural",
    description: "Tonos nude y beige naturales — piel, naturaleza y simplicidad",
    style: "minimal",
    preview: ["#A0744A", "#FAF5F0", "#FFFFFF", "#2A1F14", "#DDD0C0"],
    colors: {
      primary: "#A0744A",
      secondary: "#EDE0D0",
      background: "#FAF5F0",
      textPrimary: "#2A1F14",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FAF5F0",
      border: "#E8D8C8",
      surface: "#D8C8B0",
      searchBg: "#FAF5F0",
      textMuted: "#8A7060",
      textFooter: "#B0988A",
      buttonBg: "#A0744A",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#A0744A",
      badgeText: "#FFFFFF",
      navBorder: "#E8D8C8",
      textSecondary: "#5A4030",
      textSubtle: "#8A7060",
      borderLight: "#EDE0D0",
      borderInput: "#E8D8C8",
      borderMid: "#C8B0A0",
      ratingStar: "#F97316",
      ratingBarBg: "#E8D8C8",
      paginationBg: "#FAF5F0",
      textBreadcrumb: "#8A7060",
      tabActive: "#A0744A",
      categoryActiveBg: "#A0744A",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#F5F0EB",
      discountBg: "#E8D8C8",
      discountText: "#FFFFFF",
      popularBg0: "#F5F0EB",
      popularBg1: "#EDE0D0",
      popularBg2: "#D8C8B0",
      popularBg3: "#BCA898",
      popularText0: "#2A1F14",
      popularText1: "#2A1F14",
      popularText2: "#2A1F14",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 7. AZUL HIELO — Icy blue, clinical skincare
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "azul-hielo",
    name: "Azul Hielo",
    description: "Azul clínico sobre blanco puro — skincare científico y limpio",
    style: "corporate",
    preview: ["#0070CC", "#F0F6FF", "#FFFFFF", "#0A1A30", "#B8D4F0"],
    colors: {
      primary: "#0070CC",
      secondary: "#DBEFFE",
      background: "#F0F6FF",
      textPrimary: "#0A1A30",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F0F6FF",
      border: "#B8D4F0",
      surface: "#80B8E8",
      searchBg: "#F0F6FF",
      textMuted: "#4A6A90",
      textFooter: "#7A9AB8",
      buttonBg: "#0070CC",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#0070CC",
      badgeText: "#FFFFFF",
      navBorder: "#B8D4F0",
      textSecondary: "#1A4070",
      textSubtle: "#5080A8",
      borderLight: "#DBEFFE",
      borderInput: "#B8D4F0",
      borderMid: "#80B8E8",
      ratingStar: "#F97316",
      ratingBarBg: "#B8D4F0",
      paginationBg: "#F0F6FF",
      textBreadcrumb: "#4A6A90",
      tabActive: "#0070CC",
      categoryActiveBg: "#0070CC",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#E8F2FF",
      discountBg: "#B8D4F0",
      discountText: "#FFFFFF",
      popularBg0: "#E8F2FF",
      popularBg1: "#DBEFFE",
      popularBg2: "#B8D4F0",
      popularBg3: "#90B8E0",
      popularText0: "#0A1A30",
      popularText1: "#0A1A30",
      popularText2: "#0A1A30",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 8. MELOCOTON DORADO — Peach/golden warm
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "melocoton-dorado",
    name: "Melocotón Dorado",
    description: "Durazno y dorado cálido — luminoso, tierno y brillante",
    style: "warm",
    preview: ["#E8803A", "#FFF6EE", "#FFFFFF", "#2D1500", "#F0C090"],
    colors: {
      primary: "#E8803A",
      secondary: "#FFE8D0",
      background: "#FFF6EE",
      textPrimary: "#2D1500",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFF6EE",
      border: "#F8D8B8",
      surface: "#F0B880",
      searchBg: "#FFF6EE",
      textMuted: "#A06820",
      textFooter: "#C89860",
      buttonBg: "#E8803A",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#E8803A",
      badgeText: "#FFFFFF",
      navBorder: "#F8D8B8",
      textSecondary: "#7A3800",
      textSubtle: "#AA7030",
      borderLight: "#FFE8D0",
      borderInput: "#F8D8B8",
      borderMid: "#F0B880",
      ratingStar: "#E8803A",
      ratingBarBg: "#F8D8B8",
      paginationBg: "#FFF6EE",
      textBreadcrumb: "#A06820",
      tabActive: "#E8803A",
      categoryActiveBg: "#E8803A",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#FFF2E8",
      discountBg: "#F8D8B8",
      discountText: "#FFFFFF",
      popularBg0: "#FFF2E8",
      popularBg1: "#FFE8D0",
      popularBg2: "#F8C898",
      popularBg3: "#F0A060",
      popularText0: "#2D1500",
      popularText1: "#2D1500",
      popularText2: "#2D1500",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 9. MENTA FRESCA — Fresh mint green
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "menta-fresca",
    name: "Menta Fresca",
    description: "Verde menta refrescante — natural, orgánico y limpio",
    style: "nature",
    preview: ["#10B981", "#F0FDF4", "#FFFFFF", "#064E3B", "#6EE7B7"],
    colors: {
      primary: "#10B981",
      secondary: "#D1FAE5",
      background: "#F0FDF4",
      textPrimary: "#064E3B",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F0FDF4",
      border: "#A7F3D0",
      surface: "#6EE7B7",
      searchBg: "#F0FDF4",
      textMuted: "#047857",
      textFooter: "#34D399",
      buttonBg: "#10B981",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#10B981",
      badgeText: "#FFFFFF",
      navBorder: "#A7F3D0",
      textSecondary: "#065F46",
      textSubtle: "#078A60",
      borderLight: "#D1FAE5",
      borderInput: "#A7F3D0",
      borderMid: "#6EE7B7",
      ratingStar: "#F97316",
      ratingBarBg: "#A7F3D0",
      paginationBg: "#F0FDF4",
      textBreadcrumb: "#047857",
      tabActive: "#10B981",
      categoryActiveBg: "#10B981",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#ECFDF5",
      discountBg: "#D1FAE5",
      discountText: "#064E3B",
      popularBg0: "#ECFDF5",
      popularBg1: "#D1FAE5",
      popularBg2: "#A7F3D0",
      popularBg3: "#6EE7B7",
      popularText0: "#064E3B",
      popularText1: "#064E3B",
      popularText2: "#064E3B",
      popularText3: "#064E3B",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 10. BURDEOS LUJO — Burgundy luxury (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "burdeos-lujo",
    name: "Burdeos Lujo",
    description: "Burdeos profundo y oscuro — feminidad poderosa y lujo",
    style: "premium",
    preview: ["#C2185B", "#1A0A10", "#2A1018", "#F5E8EE", "#5A1530"],
    colors: {
      primary: "#C2185B",
      secondary: "#2A1018",
      background: "#120609",
      textPrimary: "#F5E8EE",
      headerBg: "#1A0A10",
      sectionBg: "#1A0A10",
      cardBg: "#2A1018",
      border: "#4A2030",
      surface: "#3A1828",
      searchBg: "#2A1018",
      textMuted: "#B09898",
      textFooter: "#806068",
      buttonBg: "#C2185B",
      buttonText: "#FFFFFF",
      footerBg: "#120609",
      badgeBg: "#C2185B",
      badgeText: "#FFFFFF",
      navBorder: "#4A2030",
      textSecondary: "#E0C0CC",
      textSubtle: "#C0A0AC",
      borderLight: "#3A1828",
      borderInput: "#5A2838",
      borderMid: "#502030",
      ratingStar: "#E91E63",
      ratingBarBg: "#4A2030",
      paginationBg: "#2A1018",
      textBreadcrumb: "#B09898",
      tabActive: "#C2185B",
      categoryActiveBg: "#C2185B",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#241018",
      discountBg: "#3A1828",
      discountText: "#C2185B",
      popularBg0: "#4A2030",
      popularBg1: "#3A1828",
      popularBg2: "#2A1018",
      popularBg3: "#1A0A10",
      popularText0: "#F5E8EE",
      popularText1: "#F5E8EE",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 11. BLANCO CLINICO — Pure white clinical
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "blanco-clinico",
    name: "Blanco Clínico",
    description: "Blanco clínico puro — dermatología, ciencia y pureza",
    style: "minimal",
    preview: ["#1A6BC2", "#FFFFFF", "#F8F8F8", "#111111", "#E0E0E0"],
    colors: {
      primary: "#1A6BC2",
      secondary: "#EBF4FF",
      background: "#FFFFFF",
      textPrimary: "#111111",
      headerBg: "#FFFFFF",
      sectionBg: "#F8F8F8",
      cardBg: "#FFFFFF",
      border: "#E0E0E0",
      surface: "#CCCCCC",
      searchBg: "#F8F8F8",
      textMuted: "#707070",
      textFooter: "#909090",
      buttonBg: "#1A6BC2",
      buttonText: "#FFFFFF",
      footerBg: "#F8F8F8",
      badgeBg: "#1A6BC2",
      badgeText: "#FFFFFF",
      navBorder: "#E0E0E0",
      textSecondary: "#333333",
      textSubtle: "#606060",
      borderLight: "#EEEEEE",
      borderInput: "#D8D8D8",
      borderMid: "#BCBCBC",
      ratingStar: "#F97316",
      ratingBarBg: "#E0E0E0",
      paginationBg: "#F8F8F8",
      textBreadcrumb: "#707070",
      tabActive: "#1A6BC2",
      categoryActiveBg: "#1A6BC2",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#F5F5F5",
      discountBg: "#E0E0E0",
      discountText: "#111111",
      popularBg0: "#F5F5F5",
      popularBg1: "#EBEBEB",
      popularBg2: "#D8D8D8",
      popularBg3: "#BCBCBC",
      popularText0: "#111111",
      popularText1: "#111111",
      popularText2: "#111111",
      popularText3: "#111111",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 12. TERRACOTA TIERRA — Earthy terracotta
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "terracota-tierra",
    name: "Terracota Tierra",
    description: "Terracota y arcilla — belleza natural, tierra y artesanal",
    style: "warm",
    preview: ["#B5451B", "#FBF3EE", "#FFFFFF", "#2A1008", "#E8B090"],
    colors: {
      primary: "#B5451B",
      secondary: "#F5D8C8",
      background: "#FBF3EE",
      textPrimary: "#2A1008",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FBF3EE",
      border: "#F0D0B8",
      surface: "#E8B090",
      searchBg: "#FBF3EE",
      textMuted: "#8A5030",
      textFooter: "#B07858",
      buttonBg: "#B5451B",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#B5451B",
      badgeText: "#FFFFFF",
      navBorder: "#F0D0B8",
      textSecondary: "#5A2810",
      textSubtle: "#9A6848",
      borderLight: "#F5D8C8",
      borderInput: "#F0D0B8",
      borderMid: "#E0A880",
      ratingStar: "#F97316",
      ratingBarBg: "#F0D0B8",
      paginationBg: "#FBF3EE",
      textBreadcrumb: "#8A5030",
      tabActive: "#B5451B",
      categoryActiveBg: "#B5451B",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#F8F0E8",
      discountBg: "#F0D0B8",
      discountText: "#FFFFFF",
      popularBg0: "#F8F0E8",
      popularBg1: "#F5D8C8",
      popularBg2: "#E8B090",
      popularBg3: "#D0885A",
      popularText0: "#2A1008",
      popularText1: "#2A1008",
      popularText2: "#2A1008",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 13. LILA MODERNO — Modern lilac
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "lila-moderno",
    name: "Lila Moderno",
    description: "Lila contemporáneo — cosmética joven, fresca y trendy",
    style: "playful",
    preview: ["#9C4DCC", "#FAF5FF", "#FFFFFF", "#2A103A", "#D4B0E8"],
    colors: {
      primary: "#9C4DCC",
      secondary: "#EDD9FF",
      background: "#FAF5FF",
      textPrimary: "#2A103A",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FAF5FF",
      border: "#DDB8F8",
      surface: "#C898F0",
      searchBg: "#FAF5FF",
      textMuted: "#7A50A0",
      textFooter: "#A880CC",
      buttonBg: "#9C4DCC",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#9C4DCC",
      badgeText: "#FFFFFF",
      navBorder: "#DDB8F8",
      textSecondary: "#4A1860",
      textSubtle: "#8860B0",
      borderLight: "#EDD9FF",
      borderInput: "#DDB8F8",
      borderMid: "#C898F0",
      ratingStar: "#F97316",
      ratingBarBg: "#DDB8F8",
      paginationBg: "#FAF5FF",
      textBreadcrumb: "#7A50A0",
      tabActive: "#9C4DCC",
      categoryActiveBg: "#9C4DCC",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#F5EEFF",
      discountBg: "#DDB8F8",
      discountText: "#FFFFFF",
      popularBg0: "#F5EEFF",
      popularBg1: "#EDD9FF",
      popularBg2: "#D4B0F0",
      popularBg3: "#B888E0",
      popularText0: "#2A103A",
      popularText1: "#2A103A",
      popularText2: "#2A103A",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 14. NEGRO CHIC — Black chic cosmetics (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "negro-chic",
    name: "Negro Chic",
    description: "Negro absoluto con coral vibrante — cosmética chic y poderosa",
    style: "premium",
    preview: ["#FF4040", "#0A0A0A", "#161616", "#F8F8F8", "#2A2A2A"],
    colors: {
      primary: "#FF4040",
      secondary: "#161616",
      background: "#0A0A0A",
      textPrimary: "#F8F8F8",
      headerBg: "#161616",
      sectionBg: "#161616",
      cardBg: "#202020",
      border: "#303030",
      surface: "#282828",
      searchBg: "#202020",
      textMuted: "#888888",
      textFooter: "#606060",
      buttonBg: "#FF4040",
      buttonText: "#FFFFFF",
      footerBg: "#0A0A0A",
      badgeBg: "#FF4040",
      badgeText: "#FFFFFF",
      navBorder: "#303030",
      textSecondary: "#C8C8C8",
      textSubtle: "#A0A0A0",
      borderLight: "#282828",
      borderInput: "#404040",
      borderMid: "#383838",
      ratingStar: "#FF4040",
      ratingBarBg: "#303030",
      paginationBg: "#202020",
      textBreadcrumb: "#888888",
      tabActive: "#FF4040",
      categoryActiveBg: "#FF4040",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#242424",
      discountBg: "#282828",
      discountText: "#FF4040",
      popularBg0: "#363636",
      popularBg1: "#2A2A2A",
      popularBg2: "#202020",
      popularBg3: "#161616",
      popularText0: "#F8F8F8",
      popularText1: "#F8F8F8",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 15. CREMA VAINILLA — Vanilla cream soft
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "crema-vainilla",
    name: "Crema Vainilla",
    description: "Crema y vainilla suave — cuidado delicado, calidez y dulzura",
    style: "warm",
    preview: ["#C8892A", "#FFFBF0", "#FFFFFF", "#2A1A00", "#F0D898"],
    colors: {
      primary: "#C8892A",
      secondary: "#F5DFA0",
      background: "#FFFBF0",
      textPrimary: "#2A1A00",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFBF0",
      border: "#F0DFB8",
      surface: "#E8C878",
      searchBg: "#FFFBF0",
      textMuted: "#907030",
      textFooter: "#C0A060",
      buttonBg: "#C8892A",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#C8892A",
      badgeText: "#FFFFFF",
      navBorder: "#F0DFB8",
      textSecondary: "#5A3800",
      textSubtle: "#A07A30",
      borderLight: "#F5DFA0",
      borderInput: "#F0DFB8",
      borderMid: "#E8C878",
      ratingStar: "#F97316",
      ratingBarBg: "#F0DFB8",
      paginationBg: "#FFFBF0",
      textBreadcrumb: "#907030",
      tabActive: "#C8892A",
      categoryActiveBg: "#C8892A",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#FFFAEC",
      discountBg: "#F0DFB8",
      discountText: "#FFFFFF",
      popularBg0: "#FFFAEC",
      popularBg1: "#F5DFA0",
      popularBg2: "#E8C878",
      popularBg3: "#D8AA50",
      popularText0: "#2A1A00",
      popularText1: "#2A1A00",
      popularText2: "#2A1A00",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 16. TURQUESA TROPICAL — Tropical turquoise
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "turquesa-tropical",
    name: "Turquesa Tropical",
    description: "Turquesa vibrante y tropical — fresco, energético y veraniego",
    style: "tropical",
    preview: ["#00968A", "#F0FFFE", "#FFFFFF", "#003330", "#80D8D4"],
    colors: {
      primary: "#00968A",
      secondary: "#B2EFE8",
      background: "#F0FFFE",
      textPrimary: "#003330",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F0FFFE",
      border: "#80D8D4",
      surface: "#4CC8C0",
      searchBg: "#F0FFFE",
      textMuted: "#2A7068",
      textFooter: "#60A8A0",
      buttonBg: "#00968A",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#00968A",
      badgeText: "#FFFFFF",
      navBorder: "#80D8D4",
      textSecondary: "#005848",
      textSubtle: "#3A8880",
      borderLight: "#B2EFE8",
      borderInput: "#80D8D4",
      borderMid: "#4CC8C0",
      ratingStar: "#F97316",
      ratingBarBg: "#80D8D4",
      paginationBg: "#F0FFFE",
      textBreadcrumb: "#2A7068",
      tabActive: "#00968A",
      categoryActiveBg: "#00968A",
      categoryActiveText: "#FFFFFF",
      iconPillBg: "#E8FFFD",
      discountBg: "#B2EFE8",
      discountText: "#003330",
      popularBg0: "#E8FFFD",
      popularBg1: "#B2EFE8",
      popularBg2: "#80D8D4",
      popularBg3: "#4CC8C0",
      popularText0: "#003330",
      popularText1: "#003330",
      popularText2: "#003330",
      popularText3: "#003330",
    },
  },
];
