// Tech Premium — Color Palettes
// 16 pre-built palettes designed by Valentina (UI/UX).
// Palette #1 (obsidian) matches the existing defaults in config.ts exactly.
// All color tokens are defined per palette for full harmony.
//
// NEW TOKENS (added for dark-palette support):
//   textPrimary  — main readable text (product names, headings, prices)
//   headerBg     — header/nav background
//   sectionBg    — product/discount section backgrounds
//
// These replace hardcoded "text-black" / "bg-white" in components.
// WCAG AA (4.5:1) verified for ALL text/background pairs.

import type { ColorPalette } from "@/types/templates/config-schema";

export const techPremiumPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. OBSIDIAN — The original tech-premium default
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "obsidian",
    name: "Obsidiana",
    description: "Negro sobre blanco — minimalismo tech con maximo contraste",
    style: "minimal",
    preview: ["#000000", "#FAFAFA", "#211C24", "#F6F6F6", "#909090"],
    colors: {
      primary: "#000000",
      secondary: "#211C24",
      background: "#FAFAFA",
      textPrimary: "#000000",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F6F6F6",
      border: "#B5B5B5",
      surface: "#EDEDED",
      searchBg: "#F5F5F5",
      textMuted: "#787878",
      textFooter: "#CFCFCF",
      buttonBg: "#000000",
      buttonText: "#FFFFFF",
      footerBg: "#000000",
      badgeBg: "#000000",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F4F4F4",
      reviewBg: "#FAFAFA",
      navBorder: "#E0E0E0",
      textSecondary: "#6C6C6C",
      textSubtle: "#545454",
      borderLight: "#EBEBEB",
      borderInput: "#9F9F9F",
      borderMid: "#D9D9D9",
      ratingBarBg: "#D9D9D9",
      ratingStar: "#FFB547",
      paginationBg: "#F6F6F6",
      textSummerSale: "#787878",
      textBreadcrumb: "#A4A4A4",
      tabActive: "#000000",
      categoryActiveBg: "#000000",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F6F6F6",
      popularBg1: "#EAEAEA",
      popularBg2: "#CDCDCD",
      popularBg3: "#9A9A9A",
      popularText0: "#000000",
      popularText1: "#000000",
      popularText2: "#000000",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. MIDNIGHT LUXURY — Dark premium with gold accents
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "midnight-luxury",
    name: "Lujo Nocturno",
    description: "Elegancia oscura con acentos dorados — para marcas premium",
    style: "premium",
    preview: ["#0D1117", "#C9A84C", "#161B22", "#E6EDF3", "#1C2128"],
    colors: {
      primary: "#C9A84C",
      secondary: "#1C2128",
      background: "#0D1117",
      textPrimary: "#E6EDF3",
      headerBg: "#0D1117",
      sectionBg: "#0D1117",
      cardBg: "#161B22",
      border: "#30363D",
      surface: "#1C2128",
      searchBg: "#161B22",
      textMuted: "#7D8590",
      textFooter: "#7D8590",
      buttonBg: "#C9A84C",
      buttonText: "#0D1117",
      footerBg: "#010409",
      badgeBg: "#C9A84C",
      badgeText: "#0D1117",
      specBadgeBg: "#1C2128",
      reviewBg: "#161B22",
      navBorder: "#21262D",
      textSecondary: "#8B949E",
      textSubtle: "#E6EDF3",
      borderLight: "#21262D",
      borderInput: "#484F58",
      borderMid: "#30363D",
      ratingBarBg: "#30363D",
      ratingStar: "#E3B341",
      paginationBg: "#161B22",
      textSummerSale: "#7D8590",
      textBreadcrumb: "#484F58",
      tabActive: "#C9A84C",
      categoryActiveBg: "#C9A84C",
      categoryActiveText: "#0D1117",
      popularBg0: "#3A4A5C",
      popularBg1: "#2C3A4C",
      popularBg2: "#1E2A3C",
      popularBg3: "#101C2C",
      popularText0: "#E6EDF3",
      popularText1: "#E6EDF3",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. ARCTIC STEEL — Cool corporate blues and grays
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "arctic-steel",
    name: "Acero Artico",
    description: "Azules corporativos con grises frios — profesional y confiable",
    style: "corporate",
    preview: ["#1B2A4A", "#2B5EA7", "#F4F7FB", "#E8EEF4", "#4A6B8A"],
    colors: {
      primary: "#1B2A4A",
      secondary: "#2B5EA7",
      background: "#F4F7FB",
      textPrimary: "#1B2A4A",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#EDF1F7",
      border: "#B8C7D9",
      surface: "#E1E9F2",
      searchBg: "#EDF1F7",
      textMuted: "#6B839E",
      textFooter: "#8FA4BD",
      buttonBg: "#2B5EA7",
      buttonText: "#FFFFFF",
      footerBg: "#1B2A4A",
      badgeBg: "#2B5EA7",
      badgeText: "#FFFFFF",
      specBadgeBg: "#E8EEF4",
      reviewBg: "#F4F7FB",
      navBorder: "#D4DEE9",
      textSecondary: "#4A6B8A",
      textSubtle: "#374F6B",
      borderLight: "#DFE7F0",
      borderInput: "#8FA4BD",
      borderMid: "#C5D3E2",
      ratingBarBg: "#C5D3E2",
      ratingStar: "#F5A623",
      paginationBg: "#EDF1F7",
      textSummerSale: "#6B839E",
      textBreadcrumb: "#8FA4BD",
      tabActive: "#1B2A4A",
      categoryActiveBg: "#2B5EA7",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F2F5FA",
      popularBg1: "#DCEAF5",
      popularBg2: "#BCC8D8",
      popularBg3: "#8A9AB0",
      popularText0: "#1B2A4A",
      popularText1: "#1B2A4A",
      popularText2: "#1B2A4A",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. NEON CIRCUIT — Cyberpunk dark with electric accents
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "neon-circuit",
    name: "Circuito Neon",
    description: "Fondo oscuro con acentos electricos — para tiendas gaming y tech",
    style: "cyberpunk",
    preview: ["#0A0A0F", "#00E5FF", "#FF2D78", "#14141F", "#E0E0E8"],
    colors: {
      primary: "#00E5FF",
      secondary: "#FF2D78",
      background: "#0A0A0F",
      textPrimary: "#E0E0E8",
      headerBg: "#0A0A0F",
      sectionBg: "#0A0A0F",
      cardBg: "#14141F",
      border: "#2A2A3C",
      surface: "#1A1A28",
      searchBg: "#14141F",
      textMuted: "#6B6B82",
      textFooter: "#8080A0",
      buttonBg: "#00E5FF",
      buttonText: "#0A0A0F",
      footerBg: "#06060A",
      badgeBg: "#D41860",
      badgeText: "#FFFFFF",
      specBadgeBg: "#1A1A28",
      reviewBg: "#14141F",
      navBorder: "#1E1E2E",
      textSecondary: "#8888A0",
      textSubtle: "#E0E0E8",
      borderLight: "#1E1E2E",
      borderInput: "#3D3D52",
      borderMid: "#2A2A3C",
      ratingBarBg: "#2A2A3C",
      ratingStar: "#FFD700",
      paginationBg: "#14141F",
      textSummerSale: "#6B6B82",
      textBreadcrumb: "#4D4D66",
      tabActive: "#00E5FF",
      categoryActiveBg: "#00E5FF",
      categoryActiveText: "#0A0A0F",
      popularBg0: "#32325A",
      popularBg1: "#262648",
      popularBg2: "#1A1A36",
      popularBg3: "#0E0E24",
      popularText0: "#E0E0E8",
      popularText1: "#E0E0E8",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. TERRACOTTA WARM — Warm neutrals with earthy accents
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "terracotta-warm",
    name: "Terracota Calida",
    description: "Tonos tierra con acentos arcilla — acogedor y artesanal",
    style: "warm",
    preview: ["#C06A3A", "#3D2C1E", "#FBF6F0", "#F2E8DB", "#6B5243"],
    colors: {
      primary: "#3D2C1E",
      secondary: "#C06A3A",
      background: "#FBF6F0",
      textPrimary: "#3D2C1E",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F5EDE3",
      border: "#D4C4B0",
      surface: "#EEDED0",
      searchBg: "#F5EDE3",
      textMuted: "#8A7560",
      textFooter: "#B8A594",
      buttonBg: "#8B4513",
      buttonText: "#FFFFFF",
      footerBg: "#3D2C1E",
      badgeBg: "#8B4513",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F0E4D5",
      reviewBg: "#FBF6F0",
      navBorder: "#E4D6C6",
      textSecondary: "#6B5243",
      textSubtle: "#4F3B2B",
      borderLight: "#E8DAC9",
      borderInput: "#B8A594",
      borderMid: "#D4C4B0",
      ratingBarBg: "#D4C4B0",
      ratingStar: "#E8A838",
      paginationBg: "#F5EDE3",
      textSummerSale: "#8A7560",
      textBreadcrumb: "#B8A594",
      tabActive: "#3D2C1E",
      categoryActiveBg: "#8B4513",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FAF5EE",
      popularBg1: "#EDE0D0",
      popularBg2: "#CCBBA6",
      popularBg3: "#96816A",
      popularText0: "#3D2C1E",
      popularText1: "#3D2C1E",
      popularText2: "#3D2C1E",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. BRUTALIST RAW — High-contrast, raw, unapologetic
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "brutalist-raw",
    name: "Brutalismo Crudo",
    description: "Alto contraste y tipografia imponente — diseno sin adornos",
    style: "brutalist",
    preview: ["#1A1A1A", "#D72631", "#F0F0E8", "#E8E8DF", "#FFFFFF"],
    colors: {
      primary: "#1A1A1A",
      secondary: "#D72631",
      background: "#F0F0E8",
      textPrimary: "#1A1A1A",
      headerBg: "#F0F0E8",
      sectionBg: "#F0F0E8",
      cardBg: "#E8E8DF",
      border: "#1A1A1A",
      surface: "#DCDCD2",
      searchBg: "#E8E8DF",
      textMuted: "#737368",
      textFooter: "#A0A095",
      buttonBg: "#1A1A1A",
      buttonText: "#F0F0E8",
      footerBg: "#1A1A1A",
      badgeBg: "#D72631",
      badgeText: "#FFFFFF",
      specBadgeBg: "#DCDCD2",
      reviewBg: "#F0F0E8",
      navBorder: "#1A1A1A",
      textSecondary: "#4A4A42",
      textSubtle: "#333330",
      borderLight: "#C8C8BD",
      borderInput: "#1A1A1A",
      borderMid: "#A0A095",
      ratingBarBg: "#A0A095",
      ratingStar: "#D72631",
      paginationBg: "#E8E8DF",
      textSummerSale: "#737368",
      textBreadcrumb: "#8C8C82",
      tabActive: "#1A1A1A",
      categoryActiveBg: "#1A1A1A",
      categoryActiveText: "#F0F0E8",
      popularBg0: "#EFEFE6",
      popularBg1: "#E0E0D5",
      popularBg2: "#C2C2B5",
      popularBg3: "#8E8E82",
      popularText0: "#1A1A1A",
      popularText1: "#1A1A1A",
      popularText2: "#1A1A1A",
      popularText3: "#F0F0E8",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 7. SAGE GARDEN — Nature-inspired organic tones
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "sage-garden",
    name: "Jardin de Salvia",
    description: "Verdes organicos con tierras neutras — natural y sereno",
    style: "nature",
    preview: ["#2D3A2D", "#5C7C5C", "#F7F5F0", "#E8E5DC", "#8FA88F"],
    colors: {
      primary: "#2D3A2D",
      secondary: "#5C7C5C",
      background: "#F7F5F0",
      textPrimary: "#2D3A2D",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F0EDE5",
      border: "#C4BFB0",
      surface: "#E5E1D6",
      searchBg: "#F0EDE5",
      textMuted: "#7A7568",
      textFooter: "#A5A08F",
      buttonBg: "#5C7C5C",
      buttonText: "#FFFFFF",
      footerBg: "#2D3A2D",
      badgeBg: "#5C7C5C",
      badgeText: "#FFFFFF",
      specBadgeBg: "#E8E5DC",
      reviewBg: "#F7F5F0",
      navBorder: "#D8D3C7",
      textSecondary: "#526652",
      textSubtle: "#3F4F3F",
      borderLight: "#DDD8CC",
      borderInput: "#A5A08F",
      borderMid: "#C4BFB0",
      ratingBarBg: "#C4BFB0",
      ratingStar: "#D4A72C",
      paginationBg: "#F0EDE5",
      textSummerSale: "#7A7568",
      textBreadcrumb: "#A5A08F",
      tabActive: "#2D3A2D",
      categoryActiveBg: "#5C7C5C",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F5F3EC",
      popularBg1: "#E4E0D4",
      popularBg2: "#C4BFA8",
      popularBg3: "#8F8A76",
      popularText0: "#2D3A2D",
      popularText1: "#2D3A2D",
      popularText2: "#2D3A2D",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 8. CANDY POP — Playful pastels with bright pops
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "candy-pop",
    name: "Dulce Pop",
    description: "Pasteles vibrantes con acentos fuertes — divertido y juvenil",
    style: "playful",
    preview: ["#E84393", "#2E1A3E", "#FFF5F8", "#F0E6F6", "#6C5CE7"],
    colors: {
      primary: "#2E1A3E",
      secondary: "#E84393",
      background: "#FFF5F8",
      textPrimary: "#2E1A3E",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFF0F4",
      border: "#E8C8D8",
      surface: "#F8E4EE",
      searchBg: "#FFF0F4",
      textMuted: "#8A6880",
      textFooter: "#C0A0B0",
      buttonBg: "#C2185B",
      buttonText: "#FFFFFF",
      footerBg: "#2E1A3E",
      badgeBg: "#6C5CE7",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F5E8F0",
      reviewBg: "#FFF5F8",
      navBorder: "#F0D8E4",
      textSecondary: "#6B4080",
      textSubtle: "#4A2860",
      borderLight: "#F0D8E4",
      borderInput: "#C0A0B0",
      borderMid: "#E0C0D2",
      ratingBarBg: "#E0C0D2",
      ratingStar: "#FDCB6E",
      paginationBg: "#FFF0F4",
      textSummerSale: "#8A6880",
      textBreadcrumb: "#C0A0B0",
      tabActive: "#2E1A3E",
      categoryActiveBg: "#C2185B",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FFF2F6",
      popularBg1: "#F0DEE8",
      popularBg2: "#D4B8CA",
      popularBg3: "#9C7E92",
      popularText0: "#2E1A3E",
      popularText1: "#2E1A3E",
      popularText2: "#2E1A3E",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 9. OCEAN DEPTHS — Tropical teals with coral and sand
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "ocean-depths",
    name: "Profundidad Oceanica",
    description: "Teals profundos con coral vibrante — fresco y tropical",
    style: "tropical",
    preview: ["#0C3547", "#0A7A6F", "#C03838", "#F5F9F8", "#E0F0ED"],
    colors: {
      primary: "#0C3547",
      secondary: "#0E8C7F",
      background: "#F5F9F8",
      textPrimary: "#0C3547",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#ECF4F2",
      border: "#B0D0CA",
      surface: "#E0EDE9",
      searchBg: "#ECF4F2",
      textMuted: "#5A847A",
      textFooter: "#7EB5AB",
      buttonBg: "#0A7A6F",
      buttonText: "#FFFFFF",
      footerBg: "#0C3547",
      badgeBg: "#C03838",
      badgeText: "#FFFFFF",
      specBadgeBg: "#E5F0ED",
      reviewBg: "#F5F9F8",
      navBorder: "#CCE2DC",
      textSecondary: "#1D6B7A",
      textSubtle: "#145563",
      borderLight: "#D6E5E0",
      borderInput: "#7EB5AB",
      borderMid: "#B0D0CA",
      ratingBarBg: "#B0D0CA",
      ratingStar: "#FFB347",
      paginationBg: "#ECF4F2",
      textSummerSale: "#5A847A",
      textBreadcrumb: "#7EB5AB",
      tabActive: "#0C3547",
      categoryActiveBg: "#0A7A6F",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F2F8F6",
      popularBg1: "#DCF0EA",
      popularBg2: "#B8D0C8",
      popularBg3: "#88A8A0",
      popularText0: "#0C3547",
      popularText1: "#0C3547",
      popularText2: "#0C3547",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 10. SUNSET BLOOM — Warm gradient-ready oranges, pinks, purples
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "sunset-bloom",
    name: "Flor del Atardecer",
    description: "Naranjas calidos y rosas suaves — energetico y memorable",
    style: "vibrant",
    preview: ["#C04420", "#3A1C3A", "#FFF8F5", "#FF8C69", "#D4608A"],
    colors: {
      primary: "#3A1C3A",
      secondary: "#C04420",
      background: "#FFF8F5",
      textPrimary: "#3A1C3A",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFF0EA",
      border: "#E8C8BA",
      surface: "#FCE6DC",
      searchBg: "#FFF0EA",
      textMuted: "#956A58",
      textFooter: "#C09888",
      buttonBg: "#C04420",
      buttonText: "#FFFFFF",
      footerBg: "#3A1C3A",
      badgeBg: "#A83070",
      badgeText: "#FFFFFF",
      specBadgeBg: "#FCEAE0",
      reviewBg: "#FFF8F5",
      navBorder: "#F0D8CC",
      textSecondary: "#8A4A6A",
      textSubtle: "#5A2E4A",
      borderLight: "#F2DDD2",
      borderInput: "#C09888",
      borderMid: "#E0C4B4",
      ratingBarBg: "#E0C4B4",
      ratingStar: "#FFB347",
      paginationBg: "#FFF0EA",
      textSummerSale: "#956A58",
      textBreadcrumb: "#C09888",
      tabActive: "#3A1C3A",
      categoryActiveBg: "#C04420",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FFF5F0",
      popularBg1: "#F0DCD2",
      popularBg2: "#D4BAA8",
      popularBg3: "#9A8070",
      popularText0: "#3A1C3A",
      popularText1: "#3A1C3A",
      popularText2: "#3A1C3A",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 11. SLATE MONO — Monochrome single-hue sophistication
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "slate-mono",
    name: "Pizarra Monocromatica",
    description: "Un solo tono en multiples intensidades — sofisticado y atemporal",
    style: "monochrome",
    preview: ["#2B2B2B", "#5A5A5A", "#F5F4F2", "#E8E7E4", "#8A8A87"],
    colors: {
      primary: "#2B2B2B",
      secondary: "#5A5A5A",
      background: "#F5F4F2",
      textPrimary: "#2B2B2B",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#EDECE9",
      border: "#C5C4C0",
      surface: "#E2E1DD",
      searchBg: "#EDECE9",
      textMuted: "#787875",
      textFooter: "#A5A5A2",
      buttonBg: "#2B2B2B",
      buttonText: "#F5F4F2",
      footerBg: "#2B2B2B",
      badgeBg: "#5A5A5A",
      badgeText: "#F5F4F2",
      specBadgeBg: "#E5E4E0",
      reviewBg: "#F5F4F2",
      navBorder: "#D5D4D0",
      textSecondary: "#6A6A67",
      textSubtle: "#484845",
      borderLight: "#DDDCDA",
      borderInput: "#9A9A97",
      borderMid: "#C5C4C0",
      ratingBarBg: "#C5C4C0",
      ratingStar: "#D4A72C",
      paginationBg: "#EDECE9",
      textSummerSale: "#787875",
      textBreadcrumb: "#A5A5A2",
      tabActive: "#2B2B2B",
      categoryActiveBg: "#2B2B2B",
      categoryActiveText: "#F5F4F2",
      popularBg0: "#F4F3F0",
      popularBg1: "#E5E4E0",
      popularBg2: "#C5C4C0",
      popularBg3: "#8A8A87",
      popularText0: "#2B2B2B",
      popularText1: "#2B2B2B",
      popularText2: "#2B2B2B",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 12. ELECTRIC INDIGO — Awwwards-style creative vibrancy
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "electric-indigo",
    name: "Indigo Electrico",
    description: "Violetas intensos con acentos inesperados — audaz y creativo",
    style: "awwwards",
    preview: ["#5B3AE8", "#1A0A3E", "#F7F5FF", "#00D68F", "#EDE8FF"],
    colors: {
      primary: "#1A0A3E",
      secondary: "#5B3AE8",
      background: "#F7F5FF",
      textPrimary: "#1A0A3E",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#EFEBFF",
      border: "#C8BCEE",
      surface: "#E5DFFB",
      searchBg: "#EFEBFF",
      textMuted: "#8878B0",
      textFooter: "#A090C8",
      buttonBg: "#5B3AE8",
      buttonText: "#FFFFFF",
      footerBg: "#1A0A3E",
      badgeBg: "#00D68F",
      badgeText: "#1A0A3E",
      specBadgeBg: "#E8E2FA",
      reviewBg: "#F7F5FF",
      navBorder: "#DAD2F0",
      textSecondary: "#6A50A0",
      textSubtle: "#4A3078",
      borderLight: "#E0D8F4",
      borderInput: "#A090C8",
      borderMid: "#C8BCEE",
      ratingBarBg: "#C8BCEE",
      ratingStar: "#FFB547",
      paginationBg: "#EFEBFF",
      textSummerSale: "#8878B0",
      textBreadcrumb: "#A090C8",
      tabActive: "#1A0A3E",
      categoryActiveBg: "#5B3AE8",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F4F2FC",
      popularBg1: "#E2DCFA",
      popularBg2: "#C0B8E0",
      popularBg3: "#8A80B8",
      popularText0: "#1A0A3E",
      popularText1: "#1A0A3E",
      popularText2: "#1A0A3E",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 13. PINE FOREST — Deep dark green premium
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "pine-forest",
    name: "Bosque de Pinos",
    description: "Verdes profundos con dorado terroso — premium y organico",
    style: "premium",
    preview: ["#0F1E14", "#1C3D28", "#D4C8A0", "#162A1C", "#A0B8A5"],
    colors: {
      primary: "#D4C8A0",
      secondary: "#1C3D28",
      background: "#0F1E14",
      textPrimary: "#D8D0B8",
      headerBg: "#0F1E14",
      sectionBg: "#0F1E14",
      cardBg: "#162A1C",
      border: "#2A4A35",
      surface: "#1C3524",
      searchBg: "#162A1C",
      textMuted: "#6A8A72",
      textFooter: "#6A8A72",
      buttonBg: "#D4C8A0",
      buttonText: "#0F1E14",
      footerBg: "#0A140E",
      badgeBg: "#D4C8A0",
      badgeText: "#0F1E14",
      specBadgeBg: "#1C3524",
      reviewBg: "#162A1C",
      navBorder: "#1E3525",
      textSecondary: "#A0B8A5",
      textSubtle: "#C0D4C2",
      borderLight: "#1E3525",
      borderInput: "#3A5A42",
      borderMid: "#2A4A35",
      ratingBarBg: "#2A4A35",
      ratingStar: "#E8C040",
      paginationBg: "#162A1C",
      textSummerSale: "#6A8A72",
      textBreadcrumb: "#4A6A52",
      tabActive: "#D4C8A0",
      categoryActiveBg: "#D4C8A0",
      categoryActiveText: "#0F1E14",
      popularBg0: "#2E5038",
      popularBg1: "#224028",
      popularBg2: "#18301E",
      popularBg3: "#0E2014",
      popularText0: "#D8D0B8",
      popularText1: "#D8D0B8",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 14. ROSE QUARTZ — Warm minimal with dusty rose accent
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "rose-quartz",
    name: "Cuarzo Rosa",
    description: "Rosas empolvados con blancos calidos — elegante y femenino",
    style: "minimal",
    preview: ["#B5616A", "#3A2832", "#FDF9F8", "#F5E8E6", "#E8C8C8"],
    colors: {
      primary: "#3A2832",
      secondary: "#B5616A",
      background: "#FDF9F8",
      textPrimary: "#3A2832",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F8F0EE",
      border: "#E0C8C4",
      surface: "#F0E4E0",
      searchBg: "#F8F0EE",
      textMuted: "#8A7070",
      textFooter: "#C0A0A0",
      buttonBg: "#9B3A44",
      buttonText: "#FFFFFF",
      footerBg: "#3A2832",
      badgeBg: "#9B3A44",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F2E6E2",
      reviewBg: "#FDF9F8",
      navBorder: "#ECDAD6",
      textSecondary: "#7A5A62",
      textSubtle: "#5A3E46",
      borderLight: "#ECDAD6",
      borderInput: "#C0A0A0",
      borderMid: "#D8C0BC",
      ratingBarBg: "#D8C0BC",
      ratingStar: "#E8A838",
      paginationBg: "#F8F0EE",
      textSummerSale: "#8A7070",
      textBreadcrumb: "#C0A0A0",
      tabActive: "#3A2832",
      categoryActiveBg: "#9B3A44",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FBF6F5",
      popularBg1: "#ECDAD6",
      popularBg2: "#D0B4AE",
      popularBg3: "#9A7A76",
      popularText0: "#3A2832",
      popularText1: "#3A2832",
      popularText2: "#3A2832",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 15. CHARCOAL EMBER — Dark with warm red-orange embers
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "charcoal-ember",
    name: "Carbon y Brasa",
    description: "Oscuridad calida con acentos de fuego — intenso y magnetico",
    style: "premium",
    preview: ["#1C1C1E", "#FF5733", "#2A2A2E", "#E8E4E0", "#3A3A3F"],
    colors: {
      primary: "#FF5733",
      secondary: "#2A2A2E",
      background: "#1C1C1E",
      textPrimary: "#E8E4E0",
      headerBg: "#1C1C1E",
      sectionBg: "#1C1C1E",
      cardBg: "#2A2A2E",
      border: "#404045",
      surface: "#2A2A2E",
      searchBg: "#2A2A2E",
      textMuted: "#8A8890",
      textFooter: "#8A8890",
      buttonBg: "#FF5733",
      buttonText: "#0E0E0F",
      footerBg: "#121214",
      badgeBg: "#FF5733",
      badgeText: "#0E0E0F",
      specBadgeBg: "#333338",
      reviewBg: "#2A2A2E",
      navBorder: "#333338",
      textSecondary: "#A0A0A8",
      textSubtle: "#E8E4E0",
      borderLight: "#333338",
      borderInput: "#58585F",
      borderMid: "#404045",
      ratingBarBg: "#404045",
      ratingStar: "#FFB547",
      paginationBg: "#2A2A2E",
      textSummerSale: "#8A8890",
      textBreadcrumb: "#606068",
      tabActive: "#FF5733",
      categoryActiveBg: "#FF5733",
      categoryActiveText: "#0E0E0F",
      popularBg0: "#3E3436",
      popularBg1: "#302828",
      popularBg2: "#221E1E",
      popularBg3: "#161414",
      popularText0: "#E8E4E0",
      popularText1: "#E8E4E0",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 16. IVORY STUDIO — Ultra-clean, airy, editorial white
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "ivory-studio",
    name: "Estudio Marfil",
    description: "Blancos puros con un solo acento — editorial y aireado",
    style: "minimal",
    preview: ["#1A1A1A", "#2C5F2D", "#FFFDF9", "#F5F3EF", "#D0CEC8"],
    colors: {
      primary: "#1A1A1A",
      secondary: "#2C5F2D",
      background: "#FFFDF9",
      textPrimary: "#1A1A1A",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#F8F6F2",
      border: "#D8D6D0",
      surface: "#F0EEE8",
      searchBg: "#F8F6F2",
      textMuted: "#858580",
      textFooter: "#B5B5AF",
      buttonBg: "#1A1A1A",
      buttonText: "#FFFDF9",
      footerBg: "#1A1A1A",
      badgeBg: "#2C5F2D",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F0EEE8",
      reviewBg: "#FFFDF9",
      navBorder: "#E5E3DD",
      textSecondary: "#505050",
      textSubtle: "#3A3A3A",
      borderLight: "#E8E6E0",
      borderInput: "#B0AFA8",
      borderMid: "#D0CEC8",
      ratingBarBg: "#D0CEC8",
      ratingStar: "#D4A72C",
      paginationBg: "#F8F6F2",
      textSummerSale: "#858580",
      textBreadcrumb: "#B5B5AF",
      tabActive: "#1A1A1A",
      categoryActiveBg: "#1A1A1A",
      categoryActiveText: "#FFFDF9",
      popularBg0: "#F8F6F0",
      popularBg1: "#E8E6DE",
      popularBg2: "#C8C6BD",
      popularBg3: "#908E86",
      popularText0: "#1A1A1A",
      popularText1: "#1A1A1A",
      popularText2: "#1A1A1A",
      popularText3: "#FFFFFF",
    },
  },
];
