export type * from "./primitives";
export type * from "./sections";
export type * from "./customization-sections";
export type * from "./template-config";
export type * from "./store-customization";
export type * from "./resolved-config";
export type * from "./config-schema";
export type * from "./typography";
export type * from "./structural-variants";
export type * from "./manifest";
export { isRepeatableSection } from "./config-schema";
