// Decor Warm — Color Palettes
// 16 palettes for home decor stores.
// Palette #1 matches config.ts defaults exactly.
// ~75% light, ~25% dark. All WCAG AA compliant.
// Extra tokens: peach, linen, darkBrown, darkMode, iconInactive

import type { ColorPalette } from "@/types/templates/config-schema";

export const decorWarmPalettes: ColorPalette[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. MELOCOTÓN CÁLIDO — The original decor-warm default (peach/warm on white)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "melocoton-calido",
    name: "Melocotón Cálido",
    description: "Melocotón suave sobre blanco — hogar acogedor y luminoso",
    style: "warm",
    preview: ["#CC7861", "#F4B5A4", "#FAF0E6", "#FFFFFF", "#363130"],
    colors: {
      primary: "#CC7861",
      secondary: "#FAF0E6",
      background: "#FFFFFF",
      textPrimary: "#363130",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#F0E8E4",
      surface: "#FAF0E6",
      searchBg: "#FFFFFF",
      textMuted: "#A0A0A0",
      textFooter: "#A0A0A0",
      buttonBg: "#F4B5A4",
      buttonText: "#CC7861",
      footerBg: "#FFFFFF",
      badgeBg: "#F4B5A4",
      badgeText: "#CC7861",
      navBorder: "#F0E8E4",
      textSecondary: "#4B4544",
      textSubtle: "#DCBEB6",
      borderLight: "#F0E8E4",
      borderInput: "#E8D8D4",
      borderMid: "#E8D8D4",
      ratingStar: "#CC7861",
      ratingBarBg: "#F0E8E4",
      paginationBg: "#FAF0E6",
      textBreadcrumb: "#A0A0A0",
      tabActive: "#CC7861",
      categoryActiveBg: "#F4B5A4",
      categoryActiveText: "#FFFFFF",
      peach: "#F4B5A4",
      linen: "#FAF0E6",
      darkBrown: "#391713",
      darkMode: "#363130",
      iconInactive: "#DCBEB6",
      popularBg0: "#F6F6F6",
      popularBg1: "#EAEAEA",
      popularBg2: "#CDCDCD",
      popularBg3: "#9A9A9A",
      popularText0: "#000000",
      popularText1: "#000000",
      popularText2: "#000000",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. SALVIA NATURAL — Sage green natural
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "salvia-natural",
    name: "Salvia Natural",
    description: "Verde salvia suave — decoración natural, plantas y bienestar en el hogar",
    style: "nature",
    preview: ["#6A8C5A", "#F3F7F0", "#E8F2E2", "#1A2A14", "#B0CCA0"],
    colors: {
      primary: "#6A8C5A",
      secondary: "#E8F2E2",
      background: "#F3F7F0",
      textPrimary: "#1A2A14",
      headerBg: "#F3F7F0",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#C8E0BC",
      surface: "#E8F2E2",
      searchBg: "#FFFFFF",
      textMuted: "#5A7848",
      textFooter: "#7A9868",
      buttonBg: "#B8D4A8",
      buttonText: "#3A6028",
      footerBg: "#FFFFFF",
      badgeBg: "#B8D4A8",
      badgeText: "#3A6028",
      navBorder: "#C8E0BC",
      textSecondary: "#3A5030",
      textSubtle: "#9AB88A",
      borderLight: "#D8EED0",
      borderInput: "#C8E0BC",
      borderMid: "#B0CCA0",
      ratingStar: "#6A8C5A",
      ratingBarBg: "#C8E0BC",
      paginationBg: "#E8F2E2",
      textBreadcrumb: "#5A7848",
      tabActive: "#6A8C5A",
      categoryActiveBg: "#B8D4A8",
      categoryActiveText: "#FFFFFF",
      peach: "#B8D4A8",
      linen: "#E8F2E2",
      darkBrown: "#1A2A14",
      darkMode: "#2A3A20",
      iconInactive: "#9AB88A",
      popularBg0: "#EEF6E8",
      popularBg1: "#DFF0D4",
      popularBg2: "#C0D8A8",
      popularBg3: "#98C078",
      popularText0: "#1A2A14",
      popularText1: "#1A2A14",
      popularText2: "#1A2A14",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. TERRACOTA BOHEMIO — Bohemian terracotta
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "terracota-bohemio",
    name: "Terracota Bohemio",
    description: "Terracota y arcilla boho — calidez artesanal y decoración étnica",
    style: "warm",
    preview: ["#B8502A", "#FBF0E8", "#F5E0D0", "#2A0E00", "#E8A880"],
    colors: {
      primary: "#B8502A",
      secondary: "#F5E0D0",
      background: "#FBF0E8",
      textPrimary: "#2A0E00",
      headerBg: "#FBF0E8",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#F0D0B8",
      surface: "#F5E0D0",
      searchBg: "#FFFFFF",
      textMuted: "#8A5030",
      textFooter: "#B07858",
      buttonBg: "#E8A880",
      buttonText: "#B8502A",
      footerBg: "#FFFFFF",
      badgeBg: "#E8A880",
      badgeText: "#B8502A",
      navBorder: "#F0D0B8",
      textSecondary: "#5A2810",
      textSubtle: "#C09070",
      borderLight: "#F5D8C0",
      borderInput: "#F0D0B8",
      borderMid: "#E0A870",
      ratingStar: "#B8502A",
      ratingBarBg: "#F0D0B8",
      paginationBg: "#F5E0D0",
      textBreadcrumb: "#8A5030",
      tabActive: "#B8502A",
      categoryActiveBg: "#E8A880",
      categoryActiveText: "#FFFFFF",
      peach: "#E8A880",
      linen: "#F5E0D0",
      darkBrown: "#2A0E00",
      darkMode: "#3A1A08",
      iconInactive: "#C09070",
      popularBg0: "#F8EEE4",
      popularBg1: "#F0D8C0",
      popularBg2: "#E0B890",
      popularBg3: "#C89060",
      popularText0: "#2A0E00",
      popularText1: "#2A0E00",
      popularText2: "#2A0E00",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. AZUL COSTERO — Coastal blue
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "azul-costero",
    name: "Azul Costero",
    description: "Azul costero y arena — hogar marino, fresco y luminoso",
    style: "tropical",
    preview: ["#2A7A9A", "#F0F8FF", "#E0F0F8", "#001828", "#90C8E0"],
    colors: {
      primary: "#2A7A9A",
      secondary: "#E0F0F8",
      background: "#F0F8FF",
      textPrimary: "#001828",
      headerBg: "#F0F8FF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#B0D8EE",
      surface: "#E0F0F8",
      searchBg: "#FFFFFF",
      textMuted: "#3A6880",
      textFooter: "#609880",
      buttonBg: "#90C8E0",
      buttonText: "#2A7A9A",
      footerBg: "#FFFFFF",
      badgeBg: "#90C8E0",
      badgeText: "#2A7A9A",
      navBorder: "#B0D8EE",
      textSecondary: "#003848",
      textSubtle: "#88B8D0",
      borderLight: "#C8E8F5",
      borderInput: "#B0D8EE",
      borderMid: "#80B8D0",
      ratingStar: "#2A7A9A",
      ratingBarBg: "#B0D8EE",
      paginationBg: "#E0F0F8",
      textBreadcrumb: "#3A6880",
      tabActive: "#2A7A9A",
      categoryActiveBg: "#90C8E0",
      categoryActiveText: "#FFFFFF",
      peach: "#90C8E0",
      linen: "#E0F0F8",
      darkBrown: "#001828",
      darkMode: "#003040",
      iconInactive: "#88B8D0",
      popularBg0: "#E8F5FF",
      popularBg1: "#D0E8F8",
      popularBg2: "#A8D0EC",
      popularBg3: "#78B8E0",
      popularText0: "#001828",
      popularText1: "#001828",
      popularText2: "#001828",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. NOCHE ELEGANTE — Dark elegant home (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "noche-elegante",
    name: "Noche Elegante",
    description: "Fondo oscuro con acento dorado — hogar de lujo, nocturnidad y drama",
    style: "premium",
    preview: ["#C8A048", "#0C0A07", "#181510", "#F0ECE4", "#302A20"],
    colors: {
      primary: "#C8A048",
      secondary: "#181510",
      background: "#0C0A07",
      textPrimary: "#F0ECE4",
      headerBg: "#181510",
      sectionBg: "#181510",
      cardBg: "#242018",
      border: "#38322A",
      surface: "#2E2820",
      searchBg: "#242018",
      textMuted: "#A09888",
      textFooter: "#706858",
      buttonBg: "#DDB860",
      buttonText: "#1A1408",
      footerBg: "#0C0A07",
      badgeBg: "#DDB860",
      badgeText: "#1A1408",
      navBorder: "#38322A",
      textSecondary: "#D0C8B8",
      textSubtle: "#B0A890",
      borderLight: "#2E2820",
      borderInput: "#484038",
      borderMid: "#3E3830",
      ratingStar: "#C8A048",
      ratingBarBg: "#38322A",
      paginationBg: "#242018",
      textBreadcrumb: "#A09888",
      tabActive: "#C8A048",
      categoryActiveBg: "#DDB860",
      categoryActiveText: "#1A1408",
      peach: "#DDB860",
      linen: "#2E2820",
      darkBrown: "#0C0A07",
      darkMode: "#0C0A07",
      iconInactive: "#706858",
      popularBg0: "#3A3228",
      popularBg1: "#2E2820",
      popularBg2: "#242018",
      popularBg3: "#181510",
      popularText0: "#F0ECE4",
      popularText1: "#F0ECE4",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. ARENA DESIERTO — Desert sand warm
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "arena-desierto",
    name: "Arena Desierto",
    description: "Arena y desierto cálido — minimalismo árido, terracota suave",
    style: "warm",
    preview: ["#C09060", "#FFFAF3", "#F8F0E0", "#1A1000", "#E0C890"],
    colors: {
      primary: "#C09060",
      secondary: "#F0E0C0",
      background: "#FFFAF3",
      textPrimary: "#1A1000",
      headerBg: "#FFFAF3",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#ECD8B8",
      surface: "#F0E0C0",
      searchBg: "#FFFFFF",
      textMuted: "#8A7040",
      textFooter: "#B09870",
      buttonBg: "#E0C890",
      buttonText: "#A07020",
      footerBg: "#FFFFFF",
      badgeBg: "#E0C890",
      badgeText: "#A07020",
      navBorder: "#ECD8B8",
      textSecondary: "#3A2800",
      textSubtle: "#C0A870",
      borderLight: "#F0E0C0",
      borderInput: "#ECD8B8",
      borderMid: "#D8B880",
      ratingStar: "#C09060",
      ratingBarBg: "#ECD8B8",
      paginationBg: "#F0E0C0",
      textBreadcrumb: "#8A7040",
      tabActive: "#C09060",
      categoryActiveBg: "#E0C890",
      categoryActiveText: "#FFFFFF",
      peach: "#E0C890",
      linen: "#F0E0C0",
      darkBrown: "#1A1000",
      darkMode: "#2A2010",
      iconInactive: "#C0A870",
      popularBg0: "#F8F0E0",
      popularBg1: "#F0E0C0",
      popularBg2: "#E0C890",
      popularBg3: "#C8A860",
      popularText0: "#1A1000",
      popularText1: "#1A1000",
      popularText2: "#1A1000",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 7. OLIVA MEDITERRANEO — Olive Mediterranean
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "oliva-mediterraneo",
    name: "Oliva Mediterráneo",
    description: "Oliva mediterráneo — decoración europea, aceite de oliva y tradición",
    style: "nature",
    preview: ["#7A8A40", "#F5F5E8", "#EEEED8", "#181800", "#C0C880"],
    colors: {
      primary: "#7A8A40",
      secondary: "#EEEED8",
      background: "#F5F5E8",
      textPrimary: "#181800",
      headerBg: "#F5F5E8",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#D8D8A8",
      surface: "#EEEED8",
      searchBg: "#FFFFFF",
      textMuted: "#5A6030",
      textFooter: "#8A9060",
      buttonBg: "#C0C880",
      buttonText: "#485018",
      footerBg: "#FFFFFF",
      badgeBg: "#C0C880",
      badgeText: "#485018",
      navBorder: "#D8D8A8",
      textSecondary: "#302800",
      textSubtle: "#A0A860",
      borderLight: "#E4E4C0",
      borderInput: "#D8D8A8",
      borderMid: "#B8B870",
      ratingStar: "#7A8A40",
      ratingBarBg: "#D8D8A8",
      paginationBg: "#EEEED8",
      textBreadcrumb: "#5A6030",
      tabActive: "#7A8A40",
      categoryActiveBg: "#C0C880",
      categoryActiveText: "#FFFFFF",
      peach: "#C0C880",
      linen: "#EEEED8",
      darkBrown: "#181800",
      darkMode: "#282810",
      iconInactive: "#A0A860",
      popularBg0: "#ECECE0",
      popularBg1: "#E0E0C8",
      popularBg2: "#C8C8A0",
      popularBg3: "#AAAA78",
      popularText0: "#181800",
      popularText1: "#181800",
      popularText2: "#181800",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 8. ROSA EMPOLVADO — Dusty rose
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "rosa-empolvado",
    name: "Rosa Empolvado",
    description: "Rosa empolvado sobre blanco — hogar romántico, femenino y delicado",
    style: "playful",
    preview: ["#C07888", "#FFF5F7", "#FAE8EC", "#280810", "#E8B8C8"],
    colors: {
      primary: "#C07888",
      secondary: "#F0D0DC",
      background: "#FFF5F7",
      textPrimary: "#280810",
      headerBg: "#FFF5F7",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#F0CCDC",
      surface: "#F0D0DC",
      searchBg: "#FFFFFF",
      textMuted: "#9A5868",
      textFooter: "#C09098",
      buttonBg: "#E8B8C8",
      buttonText: "#A05060",
      footerBg: "#FFFFFF",
      badgeBg: "#E8B8C8",
      badgeText: "#A05060",
      navBorder: "#F0CCDC",
      textSecondary: "#4A1820",
      textSubtle: "#D0A0B0",
      borderLight: "#F5D8E4",
      borderInput: "#F0CCDC",
      borderMid: "#DBA0B8",
      ratingStar: "#C07888",
      ratingBarBg: "#F0CCDC",
      paginationBg: "#F0D0DC",
      textBreadcrumb: "#9A5868",
      tabActive: "#C07888",
      categoryActiveBg: "#E8B8C8",
      categoryActiveText: "#FFFFFF",
      peach: "#E8B8C8",
      linen: "#F0D0DC",
      darkBrown: "#280810",
      darkMode: "#381220",
      iconInactive: "#D0A0B0",
      popularBg0: "#FCF0F4",
      popularBg1: "#F5DCEA",
      popularBg2: "#E8BECE",
      popularBg3: "#D498B0",
      popularText0: "#280810",
      popularText1: "#280810",
      popularText2: "#280810",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 9. CARBON INDUSTRIAL — Industrial dark (DARK)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "carbon-industrial",
    name: "Carbón Industrial",
    description: "Carbón oscuro con acento naranja — decoración industrial, loft y moderno",
    style: "brutalist",
    preview: ["#E87030", "#0E0E0E", "#181818", "#F0F0F0", "#2A2A2A"],
    colors: {
      primary: "#E87030",
      secondary: "#181818",
      background: "#0E0E0E",
      textPrimary: "#F0F0F0",
      headerBg: "#181818",
      sectionBg: "#181818",
      cardBg: "#242424",
      border: "#383838",
      surface: "#2E2E2E",
      searchBg: "#242424",
      textMuted: "#9A9A9A",
      textFooter: "#686868",
      buttonBg: "#FF8840",
      buttonText: "#0E0E0E",
      footerBg: "#0E0E0E",
      badgeBg: "#FF8840",
      badgeText: "#0E0E0E",
      navBorder: "#383838",
      textSecondary: "#D8D8D8",
      textSubtle: "#B0B0B0",
      borderLight: "#2E2E2E",
      borderInput: "#484848",
      borderMid: "#404040",
      ratingStar: "#E87030",
      ratingBarBg: "#383838",
      paginationBg: "#242424",
      textBreadcrumb: "#9A9A9A",
      tabActive: "#E87030",
      categoryActiveBg: "#FF8840",
      categoryActiveText: "#0E0E0E",
      peach: "#FF8840",
      linen: "#2E2E2E",
      darkBrown: "#0E0E0E",
      darkMode: "#0E0E0E",
      iconInactive: "#686868",
      popularBg0: "#3A3A3A",
      popularBg1: "#2E2E2E",
      popularBg2: "#242424",
      popularBg3: "#181818",
      popularText0: "#F0F0F0",
      popularText1: "#F0F0F0",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 10. CREMA ESCANDINAVO — Scandinavian cream
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "crema-escandinavo",
    name: "Crema Escandinavo",
    description: "Crema y blanco nórdico — minimalismo escandinavo, hygge y funcional",
    style: "minimal",
    preview: ["#4A4A5A", "#FAFAFA", "#F0F0F0", "#111118", "#D8D8E0"],
    colors: {
      primary: "#4A4A5A",
      secondary: "#E8E8F0",
      background: "#FAFAFA",
      textPrimary: "#111118",
      headerBg: "#FAFAFA",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#E0E0E8",
      surface: "#F0F0F0",
      searchBg: "#FFFFFF",
      textMuted: "#6A6A7A",
      textFooter: "#A0A0B0",
      buttonBg: "#D8D8E8",
      buttonText: "#2A2A3A",
      footerBg: "#FFFFFF",
      badgeBg: "#D8D8E8",
      badgeText: "#2A2A3A",
      navBorder: "#E0E0E8",
      textSecondary: "#2A2A3A",
      textSubtle: "#B8B8C8",
      borderLight: "#E8E8F0",
      borderInput: "#E0E0E8",
      borderMid: "#C8C8D8",
      ratingStar: "#4A4A5A",
      ratingBarBg: "#E0E0E8",
      paginationBg: "#F0F0F0",
      textBreadcrumb: "#6A6A7A",
      tabActive: "#4A4A5A",
      categoryActiveBg: "#D8D8E8",
      categoryActiveText: "#2A2A3A",
      peach: "#D8D8E8",
      linen: "#F0F0F0",
      darkBrown: "#111118",
      darkMode: "#1A1A28",
      iconInactive: "#B8B8C8",
      popularBg0: "#F2F2F8",
      popularBg1: "#E4E4EE",
      popularBg2: "#D0D0E0",
      popularBg3: "#B8B8CC",
      popularText0: "#111118",
      popularText1: "#111118",
      popularText2: "#111118",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 11. VERDE SELVA — Jungle green tropical
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "verde-selva",
    name: "Verde Selva",
    description: "Verde selva tropical — plantas, naturaleza exuberante y hogar vivo",
    style: "nature",
    preview: ["#286A38", "#F2FAF4", "#E0F2E4", "#0A1E10", "#90CCA0"],
    colors: {
      primary: "#286A38",
      secondary: "#E0F2E4",
      background: "#F2FAF4",
      textPrimary: "#0A1E10",
      headerBg: "#F2FAF4",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#A8D8B8",
      surface: "#E0F2E4",
      searchBg: "#FFFFFF",
      textMuted: "#2A6040",
      textFooter: "#60A070",
      buttonBg: "#90CCA0",
      buttonText: "#155028",
      footerBg: "#FFFFFF",
      badgeBg: "#90CCA0",
      badgeText: "#155028",
      navBorder: "#A8D8B8",
      textSecondary: "#0A3018",
      textSubtle: "#78B888",
      borderLight: "#C0E4CC",
      borderInput: "#A8D8B8",
      borderMid: "#80C090",
      ratingStar: "#286A38",
      ratingBarBg: "#A8D8B8",
      paginationBg: "#E0F2E4",
      textBreadcrumb: "#2A6040",
      tabActive: "#286A38",
      categoryActiveBg: "#90CCA0",
      categoryActiveText: "#FFFFFF",
      peach: "#90CCA0",
      linen: "#E0F2E4",
      darkBrown: "#0A1E10",
      darkMode: "#153020",
      iconInactive: "#78B888",
      popularBg0: "#E4F5E8",
      popularBg1: "#D0EDD8",
      popularBg2: "#A8D4B8",
      popularBg3: "#78B890",
      popularText0: "#0A1E10",
      popularText1: "#0A1E10",
      popularText2: "#0A1E10",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 12. MOSTAZA VINTAGE — Vintage mustard
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "mostaza-vintage",
    name: "Mostaza Vintage",
    description: "Mostaza vintage y retro — decoración años 70, bohemio y nostálgico",
    style: "warm",
    preview: ["#C8A020", "#FFFBF0", "#F8F0D0", "#1A1200", "#E8D090"],
    colors: {
      primary: "#C8A020",
      secondary: "#F0E0A0",
      background: "#FFFBF0",
      textPrimary: "#1A1200",
      headerBg: "#FFFBF0",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#ECD8A0",
      surface: "#F0E0A0",
      searchBg: "#FFFFFF",
      textMuted: "#8A7020",
      textFooter: "#B09040",
      buttonBg: "#E8D090",
      buttonText: "#7A5800",
      footerBg: "#FFFFFF",
      badgeBg: "#E8D090",
      badgeText: "#7A5800",
      navBorder: "#ECD8A0",
      textSecondary: "#3A2800",
      textSubtle: "#C0A840",
      borderLight: "#F0E0A0",
      borderInput: "#ECD8A0",
      borderMid: "#D8C060",
      ratingStar: "#C8A020",
      ratingBarBg: "#ECD8A0",
      paginationBg: "#F0E0A0",
      textBreadcrumb: "#8A7020",
      tabActive: "#C8A020",
      categoryActiveBg: "#E8D090",
      categoryActiveText: "#7A5800",
      peach: "#E8D090",
      linen: "#F0E0A0",
      darkBrown: "#1A1200",
      darkMode: "#2A1E00",
      iconInactive: "#C0A840",
      popularBg0: "#F8F0D8",
      popularBg1: "#F0E0A8",
      popularBg2: "#E0C870",
      popularBg3: "#C8A840",
      popularText0: "#1A1200",
      popularText1: "#1A1200",
      popularText2: "#1A1200",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 13. GRIS CEMENTO — Cement gray modern
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "gris-cemento",
    name: "Gris Cemento",
    description: "Gris cemento moderno — arquitectura, concreto y diseño contemporáneo",
    style: "corporate",
    preview: ["#5A6A78", "#F5F5F8", "#EBEBEE", "#0A0E12", "#C0C8D0"],
    colors: {
      primary: "#5A6A78",
      secondary: "#D0D8E0",
      background: "#F5F5F8",
      textPrimary: "#0A0E12",
      headerBg: "#F5F5F8",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#D0D8E0",
      surface: "#EBEBEE",
      searchBg: "#FFFFFF",
      textMuted: "#5A6878",
      textFooter: "#8A98A8",
      buttonBg: "#C0C8D0",
      buttonText: "#2A3A48",
      footerBg: "#FFFFFF",
      badgeBg: "#C0C8D0",
      badgeText: "#2A3A48",
      navBorder: "#D0D8E0",
      textSecondary: "#1A2838",
      textSubtle: "#98A8B8",
      borderLight: "#D8E0E8",
      borderInput: "#D0D8E0",
      borderMid: "#B8C0C8",
      ratingStar: "#5A6A78",
      ratingBarBg: "#D0D8E0",
      paginationBg: "#EBEBEE",
      textBreadcrumb: "#5A6878",
      tabActive: "#5A6A78",
      categoryActiveBg: "#C0C8D0",
      categoryActiveText: "#2A3A48",
      peach: "#C0C8D0",
      linen: "#EBEBEE",
      darkBrown: "#0A0E12",
      darkMode: "#151A20",
      iconInactive: "#98A8B8",
      popularBg0: "#E8ECF0",
      popularBg1: "#D8E0E8",
      popularBg2: "#C0C8D0",
      popularBg3: "#A0ACB8",
      popularText0: "#0A0E12",
      popularText1: "#0A0E12",
      popularText2: "#0A0E12",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 14. BURDEOS OTONO — Autumn burgundy
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "burdeos-otono",
    name: "Burdeos Otoño",
    description: "Burdeos otoñal — hogar cálido, vino tinto y decoración de temporada",
    style: "warm",
    preview: ["#8B2830", "#FFF5F5", "#F8E8E8", "#1A0008", "#D09898"],
    colors: {
      primary: "#8B2830",
      secondary: "#F0D0D0",
      background: "#FFF5F5",
      textPrimary: "#1A0008",
      headerBg: "#FFF5F5",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#EEDCDC",
      surface: "#F0D0D0",
      searchBg: "#FFFFFF",
      textMuted: "#8A5050",
      textFooter: "#B09090",
      buttonBg: "#D09898",
      buttonText: "#6A1820",
      footerBg: "#FFFFFF",
      badgeBg: "#D09898",
      badgeText: "#6A1820",
      navBorder: "#EEDCDC",
      textSecondary: "#3A0010",
      textSubtle: "#C08888",
      borderLight: "#F5E0E0",
      borderInput: "#EEDCDC",
      borderMid: "#D8B0B0",
      ratingStar: "#8B2830",
      ratingBarBg: "#EEDCDC",
      paginationBg: "#F0D0D0",
      textBreadcrumb: "#8A5050",
      tabActive: "#8B2830",
      categoryActiveBg: "#D09898",
      categoryActiveText: "#FFFFFF",
      peach: "#D09898",
      linen: "#F0D0D0",
      darkBrown: "#1A0008",
      darkMode: "#2A0018",
      iconInactive: "#C08888",
      popularBg0: "#FAF0F0",
      popularBg1: "#F0DCDC",
      popularBg2: "#E0BCBC",
      popularBg3: "#C89898",
      popularText0: "#1A0008",
      popularText1: "#1A0008",
      popularText2: "#1A0008",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 15. AZUL MARINO CLASICO — Classic navy
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "azul-marino-clasico",
    name: "Azul Marino Clásico",
    description: "Navy atemporal sobre blanco — hogar clásico, náutico y refinado",
    style: "corporate",
    preview: ["#1A3A5C", "#F5F8FF", "#E8EFF8", "#060E18", "#90A8C8"],
    colors: {
      primary: "#1A3A5C",
      secondary: "#D0DCF0",
      background: "#F5F8FF",
      textPrimary: "#060E18",
      headerBg: "#F5F8FF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#C0D0E8",
      surface: "#E8EFF8",
      searchBg: "#FFFFFF",
      textMuted: "#4A6080",
      textFooter: "#7898B8",
      buttonBg: "#90A8C8",
      buttonText: "#1A3A5C",
      footerBg: "#FFFFFF",
      badgeBg: "#90A8C8",
      badgeText: "#1A3A5C",
      navBorder: "#C0D0E8",
      textSecondary: "#0E2038",
      textSubtle: "#7898B8",
      borderLight: "#D0DCF0",
      borderInput: "#C0D0E8",
      borderMid: "#A0B8D0",
      ratingStar: "#1A3A5C",
      ratingBarBg: "#C0D0E8",
      paginationBg: "#E8EFF8",
      textBreadcrumb: "#4A6080",
      tabActive: "#1A3A5C",
      categoryActiveBg: "#90A8C8",
      categoryActiveText: "#FFFFFF",
      peach: "#90A8C8",
      linen: "#E8EFF8",
      darkBrown: "#060E18",
      darkMode: "#0E1E30",
      iconInactive: "#7898B8",
      popularBg0: "#EAF0F8",
      popularBg1: "#D8E4F4",
      popularBg2: "#B8C8E8",
      popularBg3: "#90A8D0",
      popularText0: "#060E18",
      popularText1: "#060E18",
      popularText2: "#060E18",
      popularText3: "#FFFFFF",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 16. BLANCO JAPONES — Japanese white zen
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "blanco-japones",
    name: "Blanco Japonés",
    description: "Blanco zen japonés — wabi-sabi, vacío y serenidad en el hogar",
    style: "minimal",
    preview: ["#3A3A3A", "#FFFFFF", "#F8F7F5", "#0A0A0A", "#D8D4D0"],
    colors: {
      primary: "#3A3A3A",
      secondary: "#E8E4E0",
      background: "#FFFFFF",
      textPrimary: "#0A0A0A",
      headerBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      border: "#E0DDD8",
      surface: "#F8F7F5",
      searchBg: "#FFFFFF",
      textMuted: "#787878",
      textFooter: "#A8A8A8",
      buttonBg: "#D8D4D0",
      buttonText: "#2A2A2A",
      footerBg: "#FFFFFF",
      badgeBg: "#D8D4D0",
      badgeText: "#2A2A2A",
      navBorder: "#E0DDD8",
      textSecondary: "#1A1A1A",
      textSubtle: "#B0ACAA",
      borderLight: "#E8E4E0",
      borderInput: "#E0DDD8",
      borderMid: "#C8C4C0",
      ratingStar: "#3A3A3A",
      ratingBarBg: "#E0DDD8",
      paginationBg: "#F8F7F5",
      textBreadcrumb: "#787878",
      tabActive: "#3A3A3A",
      categoryActiveBg: "#D8D4D0",
      categoryActiveText: "#2A2A2A",
      peach: "#D8D4D0",
      linen: "#F8F7F5",
      darkBrown: "#0A0A0A",
      darkMode: "#1A1A1A",
      iconInactive: "#B0ACAA",
      popularBg0: "#F4F3F0",
      popularBg1: "#ECEAE8",
      popularBg2: "#D8D4D0",
      popularBg3: "#C0BCB8",
      popularText0: "#0A0A0A",
      popularText1: "#0A0A0A",
      popularText2: "#0A0A0A",
      popularText3: "#FFFFFF",
    },
  },
];
