// Pets Classic Template — 16 Color Palettes
// Each palette defines ALL tokens used by the template.
// Palette #1 matches config.ts defaults exactly.

import type { ColorPalette } from "@/types/templates/config-schema";

export const petsClassicPalettes: ColorPalette[] = [
  // ── 1. Naranja Clásico (DEFAULT — matches config.ts) ─────────────────────
  {
    id: "naranja-clasico",
    name: "Naranja Clásico",
    description: "El look original de Pets Classic — cálido y energético",
    style: "warm",
    preview: ["#FFAF42", "#1A1A1A", "#FFFFFF", "#FFF5E6", "#F7F7F7"],
    colors: {
      primary: "#FFAF42",
      secondary: "#1A1A1A",
      background: "#FFFFFF",
      textPrimary: "#1A1A1A",
      textSecondary: "#555555",
      textMuted: "#999999",
      textSubtle: "#BBBBBB",
      textFooter: "#999999",
      textBreadcrumb: "#999999",
      textSummerSale: "#555555",
      headerBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      sectionBg: "#FFFFFF",
      surface: "#F7F7F7",
      searchBg: "#F9F9F9",
      border: "#EEEEEE",
      borderLight: "#F5F5F5",
      borderInput: "#DDDDDD",
      borderMid: "#E0E0E0",
      navBorder: "#EEEEEE",
      buttonBg: "#FFAF42",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#FFAF42",
      badgeText: "#FFFFFF",
      specBadgeBg: "#FFF5E6",
      reviewBg: "#F9F9F9",
      ratingStar: "#FFAF42",
      ratingBarBg: "#EEEEEE",
      paginationBg: "#F9F9F9",
      tabActive: "#FFAF42",
      categoryActiveBg: "#FFAF42",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F6F6F6",
      popularBg1: "#EAEAEA",
      popularBg2: "#CDCDCD",
      popularBg3: "#9A9A9A",
      popularText0: "#1A1A1A",
      popularText1: "#1A1A1A",
      popularText2: "#1A1A1A",
      popularText3: "#FFFFFF",
    },
  },

  // ── 2. Verde Salvia ───────────────────────────────────────────────────────
  {
    id: "verde-salvia",
    name: "Verde Salvia",
    description: "Natural y sereno — ideal para tiendas eco-friendly",
    style: "nature",
    preview: ["#5B8C5A", "#FFFFFF", "#F4F8F4", "#D4E8D3", "#2D4A2D"],
    colors: {
      primary: "#5B8C5A",
      secondary: "#2D4A2D",
      background: "#FFFFFF",
      textPrimary: "#1A2A1A",
      textSecondary: "#4A6B4A",
      textMuted: "#7A9B7A",
      textSubtle: "#AACBAA",
      textFooter: "#7A9B7A",
      textBreadcrumb: "#7A9B7A",
      textSummerSale: "#4A6B4A",
      headerBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      sectionBg: "#F8FBF8",
      surface: "#F0F7F0",
      searchBg: "#F4F8F4",
      border: "#D4E8D3",
      borderLight: "#E8F4E8",
      borderInput: "#C0D8BF",
      borderMid: "#D0E5CF",
      navBorder: "#D4E8D3",
      buttonBg: "#5B8C5A",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#5B8C5A",
      badgeText: "#FFFFFF",
      specBadgeBg: "#E8F4E8",
      reviewBg: "#F4F8F4",
      ratingStar: "#E8A020",
      ratingBarBg: "#D4E8D3",
      paginationBg: "#F4F8F4",
      tabActive: "#5B8C5A",
      categoryActiveBg: "#5B8C5A",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F0F7F0",
      popularBg1: "#D4E8D3",
      popularBg2: "#AACBAA",
      popularBg3: "#7A9B7A",
      popularText0: "#1A2A1A",
      popularText1: "#1A2A1A",
      popularText2: "#1A2A1A",
      popularText3: "#FFFFFF",
    },
  },

  // ── 3. Azul Océano ────────────────────────────────────────────────────────
  {
    id: "azul-oceano",
    name: "Azul Océano",
    description: "Fresco y confiable — evoca limpieza y salud",
    style: "corporate",
    preview: ["#2C7BE5", "#FFFFFF", "#F0F6FF", "#C8DFFE", "#1A4A8F"],
    colors: {
      primary: "#2C7BE5",
      secondary: "#1A4A8F",
      background: "#FFFFFF",
      textPrimary: "#0A1F3F",
      textSecondary: "#2A4F7F",
      textMuted: "#5A8ABF",
      textSubtle: "#8ABAEF",
      textFooter: "#5A8ABF",
      textBreadcrumb: "#5A8ABF",
      textSummerSale: "#2A4F7F",
      headerBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      sectionBg: "#F8FBFF",
      surface: "#F0F6FF",
      searchBg: "#F5F9FF",
      border: "#C8DFFE",
      borderLight: "#E0EEFF",
      borderInput: "#A8C8EE",
      borderMid: "#C0D8EE",
      navBorder: "#C8DFFE",
      buttonBg: "#2C7BE5",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#2C7BE5",
      badgeText: "#FFFFFF",
      specBadgeBg: "#E0EEFF",
      reviewBg: "#F5F9FF",
      ratingStar: "#FFAF42",
      ratingBarBg: "#C8DFFE",
      paginationBg: "#F5F9FF",
      tabActive: "#2C7BE5",
      categoryActiveBg: "#2C7BE5",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F0F6FF",
      popularBg1: "#C8DFFE",
      popularBg2: "#8ABAEF",
      popularBg3: "#5A8ABF",
      popularText0: "#0A1F3F",
      popularText1: "#0A1F3F",
      popularText2: "#0A1F3F",
      popularText3: "#FFFFFF",
    },
  },

  // ── 4. Rosa Suave ─────────────────────────────────────────────────────────
  {
    id: "rosa-suave",
    name: "Rosa Suave",
    description: "Tierno y cálido — perfecto para tiendas de mascotas pequeñas",
    style: "playful",
    preview: ["#E87C9C", "#FFFFFF", "#FFF0F5", "#FFD6E5", "#B04060"],
    colors: {
      primary: "#E87C9C",
      secondary: "#B04060",
      background: "#FFFFFF",
      textPrimary: "#2A0A18",
      textSecondary: "#6A2040",
      textMuted: "#A06080",
      textSubtle: "#C090B0",
      textFooter: "#A06080",
      textBreadcrumb: "#A06080",
      textSummerSale: "#6A2040",
      headerBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      sectionBg: "#FFF8FA",
      surface: "#FFF0F5",
      searchBg: "#FFF5F8",
      border: "#FFD6E5",
      borderLight: "#FFE8F0",
      borderInput: "#FFC0D5",
      borderMid: "#FFD0E0",
      navBorder: "#FFD6E5",
      buttonBg: "#E87C9C",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#E87C9C",
      badgeText: "#FFFFFF",
      specBadgeBg: "#FFE8F0",
      reviewBg: "#FFF5F8",
      ratingStar: "#FFAF42",
      ratingBarBg: "#FFD6E5",
      paginationBg: "#FFF5F8",
      tabActive: "#E87C9C",
      categoryActiveBg: "#E87C9C",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FFF0F5",
      popularBg1: "#FFD6E5",
      popularBg2: "#FFB0CC",
      popularBg3: "#C090B0",
      popularText0: "#2A0A18",
      popularText1: "#2A0A18",
      popularText2: "#2A0A18",
      popularText3: "#FFFFFF",
    },
  },

  // ── 5. Tierra Cálida ──────────────────────────────────────────────────────
  {
    id: "tierra-calida",
    name: "Tierra Cálida",
    description: "Orgánico y acogedor — inspirado en la naturaleza",
    style: "warm",
    preview: ["#C0682A", "#FFFFFF", "#FDF6F0", "#F0D0B8", "#7A3A14"],
    colors: {
      primary: "#C0682A",
      secondary: "#7A3A14",
      background: "#FFFFFF",
      textPrimary: "#2A1008",
      textSecondary: "#6A3018",
      textMuted: "#A06838",
      textSubtle: "#C0987A",
      textFooter: "#A06838",
      textBreadcrumb: "#A06838",
      textSummerSale: "#6A3018",
      headerBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      sectionBg: "#FDF6F0",
      surface: "#F8EDE4",
      searchBg: "#FDF0E8",
      border: "#F0D0B8",
      borderLight: "#F8E0CC",
      borderInput: "#E0B898",
      borderMid: "#E8C8A8",
      navBorder: "#F0D0B8",
      buttonBg: "#C0682A",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#C0682A",
      badgeText: "#FFFFFF",
      specBadgeBg: "#F8E0CC",
      reviewBg: "#FDF0E8",
      ratingStar: "#FFAF42",
      ratingBarBg: "#F0D0B8",
      paginationBg: "#FDF0E8",
      tabActive: "#C0682A",
      categoryActiveBg: "#C0682A",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F8EDE4",
      popularBg1: "#F0D0B8",
      popularBg2: "#E0B898",
      popularBg3: "#C0987A",
      popularText0: "#2A1008",
      popularText1: "#2A1008",
      popularText2: "#2A1008",
      popularText3: "#FFFFFF",
    },
  },

  // ── 6. Menta Fresca ───────────────────────────────────────────────────────
  {
    id: "menta-fresca",
    name: "Menta Fresca",
    description: "Refrescante y limpio — ideal para clínicas veterinarias",
    style: "minimal",
    preview: ["#2BBEA0", "#FFFFFF", "#F0FAFA", "#BCEEE7", "#1A7060"],
    colors: {
      primary: "#2BBEA0",
      secondary: "#1A7060",
      background: "#FFFFFF",
      textPrimary: "#0A2A28",
      textSecondary: "#2A6A60",
      textMuted: "#5A9A90",
      textSubtle: "#8ACAC0",
      textFooter: "#5A9A90",
      textBreadcrumb: "#5A9A90",
      textSummerSale: "#2A6A60",
      headerBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      sectionBg: "#F8FCFC",
      surface: "#F0FAFA",
      searchBg: "#F4FCFB",
      border: "#BCEEE7",
      borderLight: "#D8F4F0",
      borderInput: "#9ADFD8",
      borderMid: "#B0E8E0",
      navBorder: "#BCEEE7",
      buttonBg: "#2BBEA0",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#2BBEA0",
      badgeText: "#FFFFFF",
      specBadgeBg: "#D8F4F0",
      reviewBg: "#F4FCFB",
      ratingStar: "#FFAF42",
      ratingBarBg: "#BCEEE7",
      paginationBg: "#F4FCFB",
      tabActive: "#2BBEA0",
      categoryActiveBg: "#2BBEA0",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F0FAFA",
      popularBg1: "#BCEEE7",
      popularBg2: "#8ACAC0",
      popularBg3: "#5A9A90",
      popularText0: "#0A2A28",
      popularText1: "#0A2A28",
      popularText2: "#0A2A28",
      popularText3: "#FFFFFF",
    },
  },

  // ── 7. Lavanda Pastel ─────────────────────────────────────────────────────
  {
    id: "lavanda-pastel",
    name: "Lavanda Pastel",
    description: "Suave y sofisticado — elegante sin ser rígido",
    style: "playful",
    preview: ["#8B6FE0", "#FFFFFF", "#F8F5FF", "#D8CCFF", "#4A3080"],
    colors: {
      primary: "#8B6FE0",
      secondary: "#4A3080",
      background: "#FFFFFF",
      textPrimary: "#1A0A40",
      textSecondary: "#4A3080",
      textMuted: "#8870B0",
      textSubtle: "#B0A0D0",
      textFooter: "#8870B0",
      textBreadcrumb: "#8870B0",
      textSummerSale: "#4A3080",
      headerBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      sectionBg: "#FBF9FF",
      surface: "#F8F5FF",
      searchBg: "#F8F5FF",
      border: "#D8CCFF",
      borderLight: "#E8E0FF",
      borderInput: "#C0B0EE",
      borderMid: "#D0C0F8",
      navBorder: "#D8CCFF",
      buttonBg: "#8B6FE0",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#8B6FE0",
      badgeText: "#FFFFFF",
      specBadgeBg: "#E8E0FF",
      reviewBg: "#F8F5FF",
      ratingStar: "#FFAF42",
      ratingBarBg: "#D8CCFF",
      paginationBg: "#F8F5FF",
      tabActive: "#8B6FE0",
      categoryActiveBg: "#8B6FE0",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F8F5FF",
      popularBg1: "#D8CCFF",
      popularBg2: "#B0A0D0",
      popularBg3: "#8870B0",
      popularText0: "#1A0A40",
      popularText1: "#1A0A40",
      popularText2: "#1A0A40",
      popularText3: "#FFFFFF",
    },
  },

  // ── 8. Noche Oscura ───────────────────────────────────────────────────────
  {
    id: "noche-oscura",
    name: "Noche Oscura",
    description: "Premium y elegante — ideal para marcas de lujo para mascotas",
    style: "premium",
    preview: ["#FFAF42", "#0D1117", "#161B22", "#21262D", "#E6EDF3"],
    colors: {
      primary: "#FFAF42",
      secondary: "#E6EDF3",
      background: "#0D1117",
      textPrimary: "#E6EDF3",
      textSecondary: "#C9D1D9",
      textMuted: "#8B949E",
      textSubtle: "#6E7681",
      textFooter: "#8B949E",
      textBreadcrumb: "#8B949E",
      textSummerSale: "#C9D1D9",
      headerBg: "#161B22",
      cardBg: "#21262D",
      sectionBg: "#161B22",
      surface: "#30363D",
      searchBg: "#21262D",
      border: "#30363D",
      borderLight: "#21262D",
      borderInput: "#484F58",
      borderMid: "#3D444D",
      navBorder: "#30363D",
      buttonBg: "#FFAF42",
      buttonText: "#0D1117",
      footerBg: "#161B22",
      badgeBg: "#FFAF42",
      badgeText: "#0D1117",
      specBadgeBg: "#30363D",
      reviewBg: "#21262D",
      ratingStar: "#FFAF42",
      ratingBarBg: "#30363D",
      paginationBg: "#21262D",
      tabActive: "#FFAF42",
      categoryActiveBg: "#FFAF42",
      categoryActiveText: "#0D1117",
      popularBg0: "#3A4A5C",
      popularBg1: "#2C3A4C",
      popularBg2: "#1E2A3C",
      popularBg3: "#101C2C",
      popularText0: "#E6EDF3",
      popularText1: "#E6EDF3",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ── 9. Coral Tropical ─────────────────────────────────────────────────────
  {
    id: "coral-tropical",
    name: "Coral Tropical",
    description: "Vibrante y alegre — energía tropical para tu tienda",
    style: "tropical",
    preview: ["#FF6B6B", "#FFFFFF", "#FFF5F5", "#FFD0D0", "#CC3333"],
    colors: {
      primary: "#FF6B6B",
      secondary: "#CC3333",
      background: "#FFFFFF",
      textPrimary: "#2A0808",
      textSecondary: "#801818",
      textMuted: "#B06060",
      textSubtle: "#D09090",
      textFooter: "#B06060",
      textBreadcrumb: "#B06060",
      textSummerSale: "#801818",
      headerBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      sectionBg: "#FFFAFA",
      surface: "#FFF5F5",
      searchBg: "#FFF8F8",
      border: "#FFD0D0",
      borderLight: "#FFE0E0",
      borderInput: "#FFBBBB",
      borderMid: "#FFC8C8",
      navBorder: "#FFD0D0",
      buttonBg: "#FF6B6B",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#FF6B6B",
      badgeText: "#FFFFFF",
      specBadgeBg: "#FFE0E0",
      reviewBg: "#FFF8F8",
      ratingStar: "#FF9F1C",
      ratingBarBg: "#FFD0D0",
      paginationBg: "#FFF8F8",
      tabActive: "#FF6B6B",
      categoryActiveBg: "#FF6B6B",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FFF5F5",
      popularBg1: "#FFD0D0",
      popularBg2: "#FFB0B0",
      popularBg3: "#D09090",
      popularText0: "#2A0808",
      popularText1: "#2A0808",
      popularText2: "#2A0808",
      popularText3: "#FFFFFF",
    },
  },

  // ── 10. Cielo Celeste ─────────────────────────────────────────────────────
  {
    id: "cielo-celeste",
    name: "Cielo Celeste",
    description: "Fresco y amigable — connota cuidado y bienestar",
    style: "minimal",
    preview: ["#4FACDE", "#FFFFFF", "#F0F8FF", "#BBDDF5", "#1A6A9C"],
    colors: {
      primary: "#4FACDE",
      secondary: "#1A6A9C",
      background: "#FFFFFF",
      textPrimary: "#08202A",
      textSecondary: "#1A5A7A",
      textMuted: "#5A9ABF",
      textSubtle: "#8AC8E8",
      textFooter: "#5A9ABF",
      textBreadcrumb: "#5A9ABF",
      textSummerSale: "#1A5A7A",
      headerBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      sectionBg: "#F8FCFF",
      surface: "#F0F8FF",
      searchBg: "#F5FAFF",
      border: "#BBDDF5",
      borderLight: "#D0ECF8",
      borderInput: "#9CCAE8",
      borderMid: "#B0D8F0",
      navBorder: "#BBDDF5",
      buttonBg: "#4FACDE",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#4FACDE",
      badgeText: "#FFFFFF",
      specBadgeBg: "#D0ECF8",
      reviewBg: "#F5FAFF",
      ratingStar: "#FFAF42",
      ratingBarBg: "#BBDDF5",
      paginationBg: "#F5FAFF",
      tabActive: "#4FACDE",
      categoryActiveBg: "#4FACDE",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#F0F8FF",
      popularBg1: "#BBDDF5",
      popularBg2: "#8AC8E8",
      popularBg3: "#5A9ABF",
      popularText0: "#08202A",
      popularText1: "#08202A",
      popularText2: "#08202A",
      popularText3: "#FFFFFF",
    },
  },

  // ── 11. Carbón Moderno ────────────────────────────────────────────────────
  {
    id: "carbon-moderno",
    name: "Carbón Moderno",
    description: "Oscuro y sofisticado con acentos grises",
    style: "premium",
    preview: ["#6C757D", "#212529", "#2C3237", "#495057", "#F8F9FA"],
    colors: {
      primary: "#6C757D",
      secondary: "#343A40",
      background: "#212529",
      textPrimary: "#F8F9FA",
      textSecondary: "#DEE2E6",
      textMuted: "#ADB5BD",
      textSubtle: "#868E96",
      textFooter: "#ADB5BD",
      textBreadcrumb: "#ADB5BD",
      textSummerSale: "#DEE2E6",
      headerBg: "#2C3237",
      cardBg: "#343A40",
      sectionBg: "#2C3237",
      surface: "#495057",
      searchBg: "#343A40",
      border: "#495057",
      borderLight: "#3E444A",
      borderInput: "#6C757D",
      borderMid: "#565E64",
      navBorder: "#495057",
      buttonBg: "#6C757D",
      buttonText: "#FFFFFF",
      footerBg: "#2C3237",
      badgeBg: "#6C757D",
      badgeText: "#FFFFFF",
      specBadgeBg: "#495057",
      reviewBg: "#343A40",
      ratingStar: "#FFBF47",
      ratingBarBg: "#495057",
      paginationBg: "#343A40",
      tabActive: "#6C757D",
      categoryActiveBg: "#6C757D",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#3E4A52",
      popularBg1: "#323A42",
      popularBg2: "#262E36",
      popularBg3: "#1A2228",
      popularText0: "#F8F9FA",
      popularText1: "#F8F9FA",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ── 12. Violeta Neon ──────────────────────────────────────────────────────
  {
    id: "violeta-neon",
    name: "Violeta Neón",
    description: "Atrevido y vanguardista — para marcas juveniles de mascotas",
    style: "cyberpunk",
    preview: ["#BF5FFF", "#0D0A18", "#1A1028", "#28183C", "#E8D0FF"],
    colors: {
      primary: "#BF5FFF",
      secondary: "#8B2FCC",
      background: "#0D0A18",
      textPrimary: "#E8D0FF",
      textSecondary: "#D0A8FF",
      textMuted: "#9870B8",
      textSubtle: "#6840A0",
      textFooter: "#9870B8",
      textBreadcrumb: "#9870B8",
      textSummerSale: "#D0A8FF",
      headerBg: "#1A1028",
      cardBg: "#28183C",
      sectionBg: "#1A1028",
      surface: "#38204E",
      searchBg: "#28183C",
      border: "#38204E",
      borderLight: "#2A1840",
      borderInput: "#6040A0",
      borderMid: "#4A2870",
      navBorder: "#38204E",
      buttonBg: "#BF5FFF",
      buttonText: "#FFFFFF",
      footerBg: "#1A1028",
      badgeBg: "#BF5FFF",
      badgeText: "#FFFFFF",
      specBadgeBg: "#38204E",
      reviewBg: "#28183C",
      ratingStar: "#FF9F1C",
      ratingBarBg: "#38204E",
      paginationBg: "#28183C",
      tabActive: "#BF5FFF",
      categoryActiveBg: "#BF5FFF",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#40285C",
      popularBg1: "#32204A",
      popularBg2: "#24183A",
      popularBg3: "#18102A",
      popularText0: "#E8D0FF",
      popularText1: "#E8D0FF",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ── 13. Mandarina Vivo ────────────────────────────────────────────────────
  {
    id: "mandarina-vivo",
    name: "Mandarina Vivo",
    description: "Luminoso y optimista — lleno de energía y vitalidad",
    style: "vibrant",
    preview: ["#FF7A1A", "#FFFFFF", "#FFF7F0", "#FFD8BB", "#CC5200"],
    colors: {
      primary: "#FF7A1A",
      secondary: "#CC5200",
      background: "#FFFFFF",
      textPrimary: "#2A1000",
      textSecondary: "#7A3000",
      textMuted: "#C06020",
      textSubtle: "#E09060",
      textFooter: "#C06020",
      textBreadcrumb: "#C06020",
      textSummerSale: "#7A3000",
      headerBg: "#FFFFFF",
      cardBg: "#FFFFFF",
      sectionBg: "#FFFBF8",
      surface: "#FFF7F0",
      searchBg: "#FFF9F5",
      border: "#FFD8BB",
      borderLight: "#FFE8D0",
      borderInput: "#FFBB88",
      borderMid: "#FFCCA0",
      navBorder: "#FFD8BB",
      buttonBg: "#FF7A1A",
      buttonText: "#FFFFFF",
      footerBg: "#FFFFFF",
      badgeBg: "#FF7A1A",
      badgeText: "#FFFFFF",
      specBadgeBg: "#FFE8D0",
      reviewBg: "#FFF9F5",
      ratingStar: "#FFAF42",
      ratingBarBg: "#FFD8BB",
      paginationBg: "#FFF9F5",
      tabActive: "#FF7A1A",
      categoryActiveBg: "#FF7A1A",
      categoryActiveText: "#FFFFFF",
      popularBg0: "#FFF7F0",
      popularBg1: "#FFD8BB",
      popularBg2: "#FFBB88",
      popularBg3: "#E09060",
      popularText0: "#2A1000",
      popularText1: "#2A1000",
      popularText2: "#2A1000",
      popularText3: "#FFFFFF",
    },
  },

  // ── 14. Obsidiana Elegante ────────────────────────────────────────────────
  {
    id: "obsidiana-elegante",
    name: "Obsidiana Elegante",
    description: "Minimalista oscuro — para tiendas de accesorios premium",
    style: "monochrome",
    preview: ["#E8E8E8", "#111111", "#1A1A1A", "#2A2A2A", "#F5F5F5"],
    colors: {
      primary: "#E8E8E8",
      secondary: "#C0C0C0",
      background: "#111111",
      textPrimary: "#F5F5F5",
      textSecondary: "#D5D5D5",
      textMuted: "#A0A0A0",
      textSubtle: "#707070",
      textFooter: "#A0A0A0",
      textBreadcrumb: "#A0A0A0",
      textSummerSale: "#D5D5D5",
      headerBg: "#1A1A1A",
      cardBg: "#2A2A2A",
      sectionBg: "#1A1A1A",
      surface: "#383838",
      searchBg: "#2A2A2A",
      border: "#383838",
      borderLight: "#2A2A2A",
      borderInput: "#585858",
      borderMid: "#484848",
      navBorder: "#383838",
      buttonBg: "#E8E8E8",
      buttonText: "#111111",
      footerBg: "#1A1A1A",
      badgeBg: "#E8E8E8",
      badgeText: "#111111",
      specBadgeBg: "#383838",
      reviewBg: "#2A2A2A",
      ratingStar: "#FFAF42",
      ratingBarBg: "#383838",
      paginationBg: "#2A2A2A",
      tabActive: "#E8E8E8",
      categoryActiveBg: "#E8E8E8",
      categoryActiveText: "#111111",
      popularBg0: "#404040",
      popularBg1: "#323232",
      popularBg2: "#262626",
      popularBg3: "#1A1A1A",
      popularText0: "#F5F5F5",
      popularText1: "#F5F5F5",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },

  // ── 15. Crema Artesanal ───────────────────────────────────────────────────
  {
    id: "crema-artesanal",
    name: "Crema Artesanal",
    description: "Cálido y orgánico — ideal para marcas artesanales de mascotas",
    style: "warm",
    preview: ["#8B6340", "#FFFBF5", "#FFF3E5", "#E8D0B0", "#5A3A18"],
    colors: {
      primary: "#8B6340",
      secondary: "#5A3A18",
      background: "#FFFBF5",
      textPrimary: "#2A1808",
      textSecondary: "#5A3A18",
      textMuted: "#8B6848",
      textSubtle: "#B09878",
      textFooter: "#8B6848",
      textBreadcrumb: "#8B6848",
      textSummerSale: "#5A3A18",
      headerBg: "#FFFBF5",
      cardBg: "#FFF8F0",
      sectionBg: "#FFFBF5",
      surface: "#FFF3E5",
      searchBg: "#FFF5EA",
      border: "#E8D0B0",
      borderLight: "#F0DEC5",
      borderInput: "#D8C0A0",
      borderMid: "#E0C8A8",
      navBorder: "#E8D0B0",
      buttonBg: "#8B6340",
      buttonText: "#FFFBF5",
      footerBg: "#FFFBF5",
      badgeBg: "#8B6340",
      badgeText: "#FFFBF5",
      specBadgeBg: "#F0DEC5",
      reviewBg: "#FFF5EA",
      ratingStar: "#FFAF42",
      ratingBarBg: "#E8D0B0",
      paginationBg: "#FFF5EA",
      tabActive: "#8B6340",
      categoryActiveBg: "#8B6340",
      categoryActiveText: "#FFFBF5",
      popularBg0: "#FFF3E5",
      popularBg1: "#E8D0B0",
      popularBg2: "#D0B090",
      popularBg3: "#B09878",
      popularText0: "#2A1808",
      popularText1: "#2A1808",
      popularText2: "#2A1808",
      popularText3: "#FFFBF5",
    },
  },

  // ── 16. Esmeralda Oscuro ──────────────────────────────────────────────────
  {
    id: "esmeralda-oscuro",
    name: "Esmeralda Oscuro",
    description: "Profundo y natural — bosque nocturno para tiendas premium",
    style: "nature",
    preview: ["#2ECC71", "#0A1F14", "#0F2A1A", "#183D28", "#A8F0C8"],
    colors: {
      primary: "#2ECC71",
      secondary: "#27AE60",
      background: "#0A1F14",
      textPrimary: "#A8F0C8",
      textSecondary: "#78D8A0",
      textMuted: "#4AA878",
      textSubtle: "#2A7850",
      textFooter: "#4AA878",
      textBreadcrumb: "#4AA878",
      textSummerSale: "#78D8A0",
      headerBg: "#0F2A1A",
      cardBg: "#183D28",
      sectionBg: "#0F2A1A",
      surface: "#225038",
      searchBg: "#183D28",
      border: "#225038",
      borderLight: "#1A3022",
      borderInput: "#3A6A50",
      borderMid: "#2E5840",
      navBorder: "#225038",
      buttonBg: "#2ECC71",
      buttonText: "#0A1F14",
      footerBg: "#0F2A1A",
      badgeBg: "#2ECC71",
      badgeText: "#0A1F14",
      specBadgeBg: "#225038",
      reviewBg: "#183D28",
      ratingStar: "#FFAF42",
      ratingBarBg: "#225038",
      paginationBg: "#183D28",
      tabActive: "#2ECC71",
      categoryActiveBg: "#2ECC71",
      categoryActiveText: "#0A1F14",
      popularBg0: "#2A5040",
      popularBg1: "#1E4030",
      popularBg2: "#143020",
      popularBg3: "#0A2018",
      popularText0: "#A8F0C8",
      popularText1: "#A8F0C8",
      popularText2: "#FFFFFF",
      popularText3: "#FFFFFF",
    },
  },
];
